### ISSUE TITLE
Add xforms tests to CI (was: make xforms run with bb)

### ISSUE THREAD

**Issue by imrekoszo** [babashka/babashka#1000]
**Is your feature request related to a problem? Please describe.**
https://github.com/cgrand/xforms is a library of extra transducers, reducing fns, and transducing contexts, which greatly improves the quality of life when someone tries to maximize the use of transducers in clojure code.

**Describe the solution you'd like**
I would love to be able to use the `xforms` library in Babashka, extra points if it's available out of the box.

**Describe alternatives you've considered**
One alternative is to not use transducers in situations where it is clunky with what's available in clojure.core. This comes with unnecessary laziness and collection allocations but I guess that only becomes a bottleneck in heavily performance-sensitive code or code that runs a lot of times.

Another is to write those utility functions myself in a bb-compatible way, but there probably is a reason why xforms is not trivial code.

This isn't an urgent request by any means, and it is quite likely that the xforms library itself will need to be updated to support bb properly. One such piece of code is a [multi-class reify](https://github.com/cgrand/xforms/blob/62375212a8604daad631c9024e9dbe1db4ec276b/src/net/cgrand/xforms.cljc#L101). The lib has not recently been updated although there are a few open PRs, including one that fixes a handful of reflection warnings.

**Comment by borkdude** [comment]
I have an open PR at xforms [here](https://github.com/cgrand/xforms/pull/42). Feel free to respond there so it will get merged.

**Comment by borkdude** [comment]
Alternatively you can use the fork.

**Comment by imrekoszo** [comment]
Thank you!

**Comment by borkdude** [comment]
xforms is now compatible with bb. We can add its tests to bb CI.
