### ISSUE TITLE
roundrip from xml to edn and back is broken

### ISSUE THREAD

**Issue by digash** [babashka/babashka#1004]
**version**
0.6.0

**platform**
Linux

**problem**
`*data-readers*` not set for xml package, similar to #583 

**repro**

    bb '(print "<a><b>data</b><b>data1</b></a>")' | bb '(xml/parse *in*)' | bb '(read *input*)'

&#x2013;&#x2014; Error ---------------------------------------------------------------&#x2013;&#x2014;
Type:     clojure.lang.EdnReader$ReaderException
Message:  java.lang.RuntimeException: No reader function for tag xml/element
Location: 1:1

    echo "<a><b>data</b><b>data1</b></a>" | bb '(xml/parse *in*)' | bb '(read *in*)'

&#x2013;&#x2014; Error ---------------------------------------------------------------&#x2013;&#x2014;
Type:     java.lang.Exception
Message:  No reader function for tag xml/element
Location: 1:1

**expected behavior**

    echo "<a><b>data</b><b>data1</b></a>" | bb '(xml/parse *in*)' | clj -Sdeps '{:deps {org.clojure/data.xml {:mvn/version "0.2.0-alpha6"}}}' -e "(require 'clojure.data.xml) (read *in*)"

\#xml/element{:tag :a, :content [#xml/element{:tag :b, :content ["data"]} #xml/element{:tag :b, :content ["data1"]}]}

    clj -Sdeps '{:deps {org.clojure/data.xml {:mvn/version "0.2.0-alpha6"}}}' -e "*data-readers*"

\#:xml{ns #'clojure.data.xml.name/uri-symbol, element #'clojure.data.xml.node/tagged-element}

**Comment by bobisageek** [comment]
I think there may be two facets of this. It doesn't look like there's currently any handling of the clojure.data.xml readers. 

**Part 1 - using `*input*`**
To get to parity with the YAML feature and its usage of the ordered map reader, I'd say we should add the XML readers to the edn readers that are used to populate `*input*`... this should make the following possible:
```shell
$ echo '<a><b>data</b></a>' | bb "(xml/parse *in*)" | bb --stream -I "(pprint *input*)"
=> {:tag :a, :attrs {}, :content ({:tag :b, :attrs {}, :content ("data")})}
```

**Part 2 - `*data-readers*`**
As mentioned, if you start up a Clojure repl with some of the same deps that bb has "embedded" (namely clj-yaml, clojure.data.xml, and datascript), you end with `*data-readers*` having some entries, but that's not true in bb. So to use the core `read*` functions, we'd need to either populate `*data-readers*` as part of bb startup, or bind it before reading.

**Comment by borkdude** [comment]
With regards to 1: agreed.
With regards to 2: whatever the reference implementation, JVM Clojure, does, bb should also do.

**Comment by borkdude** [comment]
Thank you @bobisageek !
