### ISSUE TITLE
Consider only printing locals when --debug is provided

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#1015]
Sometimes it's awkward when secrets are printed in error output, in locals.
We can switch this off by default and only do this when `--debug` is provided.
Similar for data from ex-data fields.

/cc @mk

**Comment by mk** [comment]
This is great, thank you!

**Comment by borkdude** [comment]
Re-opening because we should also not show ex-data fields.

**Comment by mk** [comment]
Hmm, that sounds like it would limit the ability for a normal user to understand the error that's happening? I think surfacing the exception _with_ ex-data by default is reasonable and can be avoided by catching and re-throwing a exception with less data on it?

**Comment by borkdude** [comment]
Alright, will leave it like this then!
