### ISSUE TITLE
Additional opts to download pods & Clojure dependencies to specified directory

### ISSUE THREAD

**Issue by FieryCod** [babashka/babashka#1019]
Continuation of https://github.com/babashka/babashka/issues/801#issuecomment-831771693

**Is your feature request related to a problem? Please describe.**

Currently [HL](https://github.com/FieryCod/holy-lambda) provides set of babashka tasks. For babashka runtime/backend tasks allow to:

- download set of babashka pods specified in `:pods` entry to `.holy-lambda/pods` directory,
- download babashka Clojure dependencies into the specified directory. 

Pods and Jars have to be downloaded, and packed into the zip then transfered to AWS S3 before AWS Lambda deployment, since resolving/downloading during the first run of lambda significantly slows the initialization time.

Additionally pods have to be downloaded for amd64 Linux to correctly work on AWS Lambda environment, therefore HL leverages the Docker image for this.

**Current approach**:

Currently HL has to force the user to download the dependencies (for all backends) to special `.holy-lambda` directory via `hl:sync`. The command downloads both Clojure deps + Babashka pods. To make it work I had to specify bunch of the environment variables:

```
ENV CLJ_CACHE=/project/.holy-lambda/clojure
ENV CLJ_COFIG=/project/.holy-lambda/clojure
ENV CLOJURE_TOOLS_DIR=/project/.holy-lambda
ENV HOME=/project/.holy-lambda
ENV XDG_CACHE_HOME=/project/.holy-lambda
ENV XDG_CONFIG_HOME=/project/.holy-lambda
ENV XDG_DATA_HOME=/project/.holy-lambda
ENV GITLIBS=/project/.holy-lambda/.gitlibs/
```

Additionally `deps.edn` requires a keyword `:mvn/local-repo` to be specified. This is basically done only to support babashka backend, because for both Clojure & Native this is not really required (for consistency reasons Clojure & Backend) download the packages to local directory.

This is very troublesome approach, because:
- it makes working with most popular backends less convenient, 
- dependencies are downloaded via Docker (no caching),
- using local libraries requires mounting Docker volumes,
- it's hard to integrate HL with already existing projects 

**Describe the solution you'd like**

What I would like to achieve is to:
1. Deprecate `hl:sync` and remove `:mvn/local-repo` from `deps.edn`, instead add additional `hl:bb:deps` & `hl:bb:pods` (see below).
2. **I would like to specify the download folder for pods.** Preferably via `System.property`, so it's easy to set. I don't want to specify `XDG` environment variables for this, since to many tools are using it (potential downloads + mess in the user project). (this will be run in docker)
3. **I would like to specify the download folder for Clojure deps**. (local environment)

**Describe alternatives you've considered**

See above.

**Comment by borkdude** [comment]
Thanks for the issue.

> I would like to specify the download folder for Clojure deps

Is this for Clojure JVM usage or bb usage? I assume you mean dependencies to be used with bb scripts?

I will ask another user for feedback and hope to implement something that can satisfy more than one usage.

**Comment by FieryCod** [comment]
You're very welcome @borkdude 

> I would like to specify the download folder for Clojure deps

This is for bb usage, since I need to pack babashka deps and provide them separately as an AWS Lambda Layer. I have also disabled `add-deps` functionality in HL to force the users to pack their bb deps. Otherwise the cold starts are extremely high (which is understandable, because bb has to download deps either from github (lambda has no git command available) or maven).

```
(require '[babashka.deps])

(alter-var-root #'babashka.deps/add-deps
                (fn [f]
                  (fn [m]
                    (println "[holy-lambda] Dependencies should not be added via add-deps. Move your dependencies to a layer!")
                    (System/exit 1)
                    )))
```

**Comment by borkdude** [comment]
@FieryCod 

- Can you make a proposal how the UX should look like for downloading (and loading!) pods from a specific location?
- Similar for Clojure?

I'm not yet asking for a technical solution, just describe how the user would configure this. We can do either a System property or env variables, I'm fine with either but env variables may be more flexible as you can set them before invoking bb and they can't change in a running environment.

**Comment by FieryCod** [comment]
@borkdude 

I'm thinking whether we could do it without environment variables or system properties. Let me know what is your opinion on this:

- `bb -P` - prepare all dependencies
  
  **Arguments supported**
  - `:pods-output-dir <path>` - directory to which pods should be saved, (should create a directory if necessary)
  - `:deps-output-dir <path>` - directory to which Clojure deps should be saved. (should create a directory if necessary)

This is probably enough, and looks very similar to what Clojure CLI offers.

**Comment by borkdude** [comment]
@FieryCod I feel there are lot of gaps still. 

Pods haven't made it in `bb.edn` yet: right now their download is triggered by `load-pod` when running code. So there is no declarative way of describing what pods you need.

Also just having a `prepare` command doesn't solve the problem of where to load the pods/dependencies from.

**Comment by FieryCod** [comment]
We should probably differentiate between the usage of `bb` in a simple scripts and more complex scenarios. For simple scripts (one file) I assume the user would not like to declare pods & deps in `bb.edn`, and this is totally fine. The current way `add-deps` and `load-pods` work to dynamically add the dependency should be used in such case.

However, complex scripts with multiple files, deps and pods would probably benefit from a more declarative way of describing dependencies.

**Example bb.edn**
```
{:deps {some-library {:mvn/version "0.0.1"}
 :pods {pod-name "version"}}
```

Upon a prepare command if either `:pods-output-dir` or bb `deps-output-dir` is used `bb` can create an additional `bb.paths.edn` file with the following structure:

```
{:deps-output-dir "location-where-deps-are"
 :pods-output-dir "location-where-pods-are" }
```

Alternatively, since most of the users would probably not use `:deps-output-dir` or `:pods-output-dir` we could agree that `bb` will accept additional environment variables:

- `BABASHKA_PODS_DIR` 
- `BABASHKA_DEPS_DIR`

I have also read https://github.com/babashka/babashka/issues/863 and in my opinion `babashka` should either not allow `load-pod` without the version specified, or load the pod with the **newest version**. Otherwise `babashka` would have to create lockfiles for dependencies, which is probably an overkill?
