### ISSUE TITLE
Default bb directory on classpath - spit out .nrepl-port file in .babashka directory 

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#1032]
Then the nREPL server is started, bb should spit out an a `.babashka/.nrepl-port` file. This file should be automatically removed on exit.

We could also considering naming the dir `bb` so we can store bb-specific scripts there and `bb` would be on the classpath by default.

```
bb.edn
bb/script.clj
bb/.nrepl-port
```

Feedback from users:

> bb sounds good to me.  Especially if it’s on the default classpath! Sounds lovely.

> That's ambitious! I like it

/cc @PEZ

**Comment by bobisageek** [comment]
Should the directory name be `.bb` for consistency with lots of popular tools? (looking at a random workspace I have open shows me `.calva`, `.clj-kondo`, `.lsp`, and so on)

**Comment by borkdude** [comment]
The idea would be that `bb` would be the classpath by default (if no other paths are specified in `bb.edn` or not overriden using the `-cp` option or env var). For Clojure this is `src`. It would be a standard location to put scripts. 

The other idea would be that we could also write temporary files in there like `.nrepl-port` (to not pollute the root directory and not conflict with the JVM nREPL).

**Comment by borkdude** [comment]
I'm closing this for now.
