### ISSUE TITLE
Upgrade to GraalVM 21.3.0

### ISSUE THREAD

**Issue by jkrasnay** [babashka/babashka#1052]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

**Is your feature request related to a problem? Please describe.**
Babashka auto-downloads Clojure Tools when using deps, but when behind a corporate firewall this can fail on spoofed SSL certificates. 21.3.0 allows the user to specify the `javax.net.ssl.trustStore` system property so we can specify a keystore with the missing certs.

**Describe the solution you'd like**
Build Babashka with GraalVM 21.3.0

**Describe alternatives you've considered**
Downloading Clojure Tools separately or as part of a Clojure install and using `DEPS_CLJ_TOOLS_DIR` and `DEPS_CLJ_TOOLS_VERSION` is an alternative that works today.

**Additional context**

**Comment by borkdude** [comment]
I compared the classes that are being included in JDK 11 and JDK17 and noticed JDK17 somehow includes more java.awt classes. It would be nice if we could somehow exclude those. There is a Graal issue about it here:

https://github.com/oracle/graal/issues/3225

<img width="1497" alt="Screen Shot 2021-11-03 at 21 50 30" src="https://user-images.githubusercontent.com/284934/140198949-d3cc31e9-d330-4856-9061-24385e9d63ce.png">
<img width="1462" alt="Screen Shot 2021-11-03 at 21 50 23" src="https://user-images.githubusercontent.com/284934/140198951-26d06bdb-7ac1-41c9-82a1-24a64a498fad.png">

<img width="1587" alt="Screen Shot 2021-11-03 at 21 53 16" src="https://user-images.githubusercontent.com/284934/140198942-a83b9310-ee31-4cab-b8ac-970fbf397cdb.png">

**Comment by borkdude** [comment]
I'll upgrade to 21.3.0 JVM 11 now and hope that before upgrading to 17 https://github.com/oracle/graal/issues/3225 will be supported.

**Comment by borkdude** [comment]
@jkrasnay I upgraded to 21.3.0 on master. Could you test? Which OS do you use?

**Comment by jkrasnay** [comment]
Sure, happy to test. I'm on Windows 10.

**Comment by borkdude** [comment]
Here is a Windows binary:

https://ci.appveyor.com/api/buildjobs/bbb56nsfc6efsk2m/artifacts/babashka-0.6.5-SNAPSHOT-windows-amd64.zip

**Comment by jkrasnay** [comment]
Yes, that works! I'm able to specify `javax.net.ssl.trustStore` and it is able to download Clojure Tools through the firewall.

**Comment by borkdude** [comment]
cool :-)

**Comment by borkdude** [comment]
Adding `-H:ServiceLoaderFeatureExcludeServices=java.net.ContentHandlerFactory` gets rid of including `java.awt.Toolkit` in the image.

**Comment by jijun99** [comment]
How about Windows bb.exe?

**Comment by borkdude** [comment]
@jijun99 What about it?

**Comment by jijun99** [comment]
I realized that it is the problem in powershell, if I supplement -Djavax... options in powershell, it will say file not found.  But cmd.exe can accept such options. Thanks. @borkdude
