### ISSUE TITLE
Add --HEAD option to the brew formula

### ISSUE THREAD

**Issue by agzam** [babashka/babashka#1075]
Sometimes, for testing out experimental, unreleased features, one is required to pull babashka on the main branch. Would be nice to have an option in brew formula to make it easier for those who on Mac.

**Comment by borkdude** [comment]
@agzam What would this require? Does the --HEAD option require users to build from source or are pre-compiled binaries fine too?

**Comment by agzam** [comment]
I'm not sure of specifics of homebrew, but as far as I know, typically things installed with --HEAD tend to build from source. But maybe that's when there are no binaries available ¯\\\_(ツ)_/¯.

**Comment by borkdude** [comment]
I recommend using the install script, which now supports installing SNAPSHOT releases.

The script works on linux and macOS:

```
$ curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
$ chmod +x install
$ ./install --version 0.7.1-SNAPSHOT --dir bb-dev
$ bb-dev/bb --version
babashka v0.7.1-SNAPSHOT
```

**Comment by borkdude** [comment]
Will close this in favor of the bash script, which should be sufficient since babashka is release fairly often.
