### ISSUE TITLE
Expose next.jdbc's result-set helpers to babashka

### ISSUE THREAD

**Issue by nikvdp** [babashka/babashka#1081]
**Is your feature request related to a problem? Please describe.**
Using next.jdbc with sqlite can be inconvenient because next.jdbc returns fully qualified keywords by default, which increases the amount of hoop-jumping needed to work with the results of sql queries. Next.jdbc ships with some sugar/helpers under the `next.jdbc.result-set` namespace to make working with query results more convenient (relevant next.jdbc documentation [here](https://github.com/seancorfield/next-jdbc/blob/develop/doc/result-set-builders.md)), which work nicely when using next.jdbc on the JVM, but are not available when using next.jdbc from babashka.

**Describe the solution you'd like**
The ability to access the helpers in the `next.jdbc.result-set` namespace from babashka scripts.

**Describe alternatives you've considered**
There are other options such as:
- Using explicit column aliases in all your sql queries. According to the next.jdbc [result-set-builders documentation](https://github.com/seancorfield/next-jdbc/blob/develop/doc/result-set-builders.md)  next.jdbc will return unqualified keywords in this case.
- Using a library like https://github.com/cjsauer/disqualified, or writing your own helper functions to use with your babashka scripts.

However since Babashka's sweet spot seems to be scripting/prototyping or exploratory use cases where creating a full-blown JVM clojure project would be too heavy and these APIs are already present in next.jdbc (and I believe already included in the bb binary when `BABASHKA_FEATURE_JDBC` is enabled, just not exposed as a sci namespace) allowing babashka scripts access to them seems win/win. Additionally, users who are moving to Babashka from JVM-clojure projects may expect them to be present and using next.jdbc's own functions for this should also be more performant than having users DIY them since next.jdbc seems to go to some pains to avoid duplicating work in this area.

**Additional context**
Code to expose these functions was originally included in https://github.com/babashka/babashka/pull/1079, but removed as it is a more general next.jdbc change, and not directly related to the SQLite feature flag.

**Comment by borkdude** [comment]
Merged. Note that you can also use the babashka sqlite pod:

https://github.com/babashka/pod-registry/blob/master/examples/go_sqlite3.clj
