### ISSUE TITLE
Install script isn't using decimal numbers for version comparison

### ISSUE THREAD

**Issue by Cnly** [babashka/babashka#1085]
**version**

v0.6.8

**platform**

Not relevant.

**problem**

The `install` script uses octal numbers for version comparison:

https://github.com/babashka/babashka/blob/26336ed5006ebfbc127da9eaf3d522d07aaf6e15/install#L94

and since 0.6.8 has an 8 in it, each time the script is run it now throws a confusing message (although no functional problems):

```
line 94: [[: 000006008: value too great for base (error token is "000006008")
```

**repro**

Not applicable.

**expected behavior**

No confusing messages should be thrown.

I've already have a little patch here: https://github.com/cnly/babashka/commit/fcb0cce31ee452efde4f8fe116c4e0ee9c0b3b3a; if you want I can open a PR.

**Comment by Grazfather** [comment]
Yeah, your patch should work. Sorry about that!

**Comment by borkdude** [comment]
@Cnly OK, PR welcome then!

**Comment by Grazfather** [comment]
Confirmed the fix.

```bash
✦2 ❯ ./install
0.6.8
000006008
./install: line 97: [[: 000006008: value too great for base (error token is "000006008")

babashka on  master [!?] via 🐳 desktop-linux via ☕ v12
✦2 ❯ vim ./install # Applying fix

babashka on  master [!?] via 🐳 desktop-linux via ☕ v12 took 3s
✦2 ❯ ./install
0.6.8
000006008
```

**Comment by borkdude** [comment]
Excellent, thank you both.

**Comment by Cnly** [comment]
That was fast, thanks!

**Comment by Grazfather** [comment]
My bad on the oversight!
