### ISSUE TITLE
bb's clojure.core/read requires LineNumberingPushbackReader

### ISSUE THREAD

**Issue by Cnly** [babashka/babashka#1086]
**version**

v0.6.8

**platform**

macOS

**problem**

`clojure.core/read`'s doc [says](https://clojuredocs.org/clojure.core/read) the stream must be an instance of `java.io.PushbackReader` or some derivee. While this is true in clojure, in babashka if that reader is used, I get the error

```
Type:     java.lang.IllegalArgumentException
Message:  No implementation of method: :get-line-number of protocol: #'clojure.tools.reader.reader-types/IndexingReader found for class: java.io.PushbackReader
```

Using `clojure.lang.LineNumberingPushbackReader` instead fixes this.

**repro**

The following script runs in clojure but not in bb:

```clj
(ns hello
  (:require [clojure.java.io :as io])
  (:import [java.io PushbackReader]))

(println (let [reader (PushbackReader. (io/reader *file*))]
   (read reader)))
```

**expected behavior**

bb shouldn't require LineNumberingPushbackReader.

**Comment by borkdude** [comment]
@Cnly bb master should now support this (just pushed). Will write a test tomorrow, so I'll leave this open still.

**Comment by borkdude** [comment]
Fixed.
