### ISSUE TITLE
Add "spy" macro from taoensso.timbre

### ISSUE THREAD

**Issue by carlzhc** [babashka/babashka#1087]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

```
$ bb --version
babashka v0.6.2
```
[ Please specify which version of babashka you're using. You can find this with `babashka --version`. The documentation on the master branch may be ahead of the most released version. ]
```
$ uname -a
Linux devel.carl.home 3.10.0 #1 SMP Fri Aug 28 07:51:21 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux
```
[ Please specify which platform you are using babashka on, so you can test a
new binary when the issue is resolved. ]

From the taoensso.timbre namespace, no `spy` macro.

[ Please provide a short and to the point description of the problem ]

```
user=> (require '[taoensso.timbre :refer :all])
nil
user=> (spy 1)
Could not resolve symbol: spy [at <repl>:16:2]
user=> spyf
Could not resolve symbol: spyf [at <repl>:17:1]
```

[ Please provide a minimal working reproduction of the problem ]

http://ptaoussanis.github.io/timbre/taoensso.timbre.html#var-spy

[ What is the behavior you expected to see? Please provide a minimal working example ]

**Comment by borkdude** [comment]
@carlzhc Will do. This is fairly easy to fix, so please go ahead if you would like to do it yourself.

**Comment by carlzhc** [comment]
Thank you!
