### ISSUE TITLE
Support multi-architecture Docker builds

### ISSUE THREAD

**Issue by cap10morgan** [babashka/babashka#1096]
Docker images can be built for platforms and architectures besides linux/amd64 with the new BuildKit (which has been the default for some time) backend. It provides automatic global build args (e.g. `TARGETARCH`) to indicate which platform/arch is being targeted that you can use to determine which architecture to use in the build commands (for e.g. architecture-specific downloads like graalvm).

This allows building and running linux/arm64 containers on Apple Silicon Macs which is much faster and more reliable than emulating linux/amd64 containers.

Babashka already provides linux-aarch64 binary downloads, but the current Dockerfile assumes a linux/amd64 build. It would be great to allow building a linux/arm64 Docker image.

Note that currently graalvm does not support building static binaries on linux/arm64.

**Comment by borkdude** [comment]
> Note that currently graalvm does not support building static binaries on linux/arm64.

Actually it does. See the `linux-aarch64-static` in the circleci config. It links everything _except_ libc using the `"-H:+StaticExecutableWithDynamicLibC"` option.

**Comment by cap10morgan** [comment]
@borkdude Huh. I guess this is outdated then? Or is only referring to fully static images? https://www.graalvm.org/reference-manual/native-image/StaticImages/#prerequisites

**Comment by borkdude** [comment]
@cap10morgan it's what they call "mostly static binaries" there and they are supported for aarch64.
