### ISSUE TITLE
shasum -a 256 or sha256sum (Linux compatibility of the install script)

### ISSUE THREAD

**Issue by duzunov** [babashka/babashka#1107]
**version** 0.7.0

**platform** Amazon Linux 2

**problem**

On Amazon Linux 2 and probably other Linux systems the checksum comparison fails due the different command names as compared to MacOS (sha256sum vs shasum -a 256

**repro**

```
/tmp/install --dir /usr/local/bin/ --version 0.7.0 --static --checksum 820a1f97bdcb528c792a138715fc8e8842b7f0b053e0e42ce20f6cee3db12c12
Downloading https://github.com/babashka/babashka/releases/download/v0.7.0/babashka-0.7.0-linux-amd64-static.tar.gz to /tmp/tmp.rfTsAZG3IR
/tmp/install-bb.sh: line 121: shasum: command not found
Failed checksum on babashka-0.7.0-linux-amd64-static.tar.gz
/tmp/install-bb.sh: line 123: shasum: command not found
Got:
Expected: 820a1f97bdcb528c792a138715fc8e8842b7f0b053e0e42ce20f6cee3db12c12

```

**expected behavior**

To handle Amazon Linux 2 and other RHEL-like systems, probably Linux in general. I know the shasum -a 256 works on MacOS.

**Comment by borkdude** [comment]
sha256sum is also available on macOS. Maybe we should just use that, @thiagokokada ?

**Comment by thiagokokada** [comment]
> sha256sum is also available on macOS. Maybe we should just use that, @thiagokokada ?

I originally used `sha256sum`, and I am almost sure that I changed this because macOS.

Maybe you installed this separated using `homebrew` or something :thinking: ?

**Comment by borkdude** [comment]
You're right:

```
$ ls -lat /usr/local/bin/sha256sum

lrwxr-xr-x  1 borkdude  admin  37 Oct  6 17:09 /usr/local/bin/sha256sum -> ../Cellar/coreutils/9.0/bin/sha256sum
```

Perhaps we should try both options and pick the first one which works.

**Comment by thiagokokada** [comment]
> Perhaps we should try both options and pick the first one which works, starting with sha256sum.

Yeah, I will do this. Should be easy.

**Comment by borkdude** [comment]
@duzunov Can you try again? The script may be cached for a while by Github, so please check the contents.

**Comment by duzunov** [comment]
Works perfectly! Thank you @thiagokokada and @borkdude !
