### ISSUE TITLE
Missing error message

### ISSUE THREAD

**Issue by isaksky** [babashka/babashka#1116]
**version**

v0.7.0

**platform**

Windows 10

**problem**

Calling `partition` with the wrong arguments yields no error message.

**repro**

```powershell
PS C:\src> bb
Babashka v0.7.0 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (partition (range 5) 3)

(user=>
```

**expected behavior**

Similar to clj, note the "Don't know how to create ISeq from: java.lang.Long" error message below:

```powershell
PS C:\src> clj
Clojure 1.10.3
user=> (partition (range 5) 3)
Error printing return value (IllegalArgumentException) at clojure.lang.RT/seqFrom (RT.java:557).
Don't know how to create ISeq from: java.lang.Long
(user=>
PS C:\src>
```

**Comment by borkdude** [comment]
Should be fixed on master. You can download a new Windows binary here once the Windows build has successfully finished.

https://github.com/babashka/babashka-dev-builds/releases

**Comment by isaksky** [comment]
I get the error message now, thanks for the help!
