### ISSUE TITLE
Babashka 0.7.2 always download clojure-tools for deps.clj, even if unnecessary

### ISSUE THREAD

**Issue by thiagokokada** [babashka/babashka#1124]
**version**

babashka v0.7.2

**platform**

amd64-linux

**problem**

With the following `bb.edn` file inside a directory:

```clojure
{}
```

Deleting the directory `~/.deps.clj` and running `bb --version` (or any other flag, calling a script, etc.) this will result in the following with babashka 0.7.2:

```
$ rm -rf ~/.deps.clj && bb --version
Could not find /home/thiagoko/.deps.clj/1.10.3.1040/ClojureTools/clojure-tools-1.10.3.1040.jar
Downloading tools jar from https://download.clojure.org/install/clojure-tools-1.10.3.1040.zip to /home/thiagoko/.deps.clj/1.10.3.1040/ClojureTools
babashka v0.7.2
```

However doing the same with babashka 0.7.0 does not download `clojure-tools`:

```
$ rm -rf ~/.deps.clj && bb --version
babashka v0.7.0
```

This looks like a regression and it is causing [issues in Nixpkgs](https://github.com/NixOS/nixpkgs/pull/152637). The problem is that `clojure-lsp` uses babashka during testing, and it has a [bb.edn](https://github.com/clojure-lsp/clojure-lsp/blob/master/bb.edn) file, however it doesn't download any dependencies (the file has no `:deps` section). Since during build phase Nix doesn't allow internet connectivity, `clojure-tools` download fails.

**repro**

See above section.

**expected behavior**

The behavior from babashka 0.7.0 be restored (so not downloading `clojure-tools` unless necessary, i.e.: `bb.edn` file includes a `:deps` section).

**Comment by borkdude** [comment]
Looks like a similar problem to #1123. I'll look into it.

**Comment by borkdude** [comment]
0.7.3 is building...

**Comment by borkdude** [comment]
Released!

**Comment by thiagokokada** [comment]
Works fine: https://github.com/NixOS/nixpkgs/pull/152735

:bow: .
