### ISSUE TITLE
Add bill-of-materials to Docker images to aid vulnerability scanning

### ISSUE THREAD

**Issue by kipz** [babashka/babashka#1133]
**Is your feature request related to a problem? Please describe.**

From clojurians slack: https://clojurians.slack.com/archives/CLX41ASCS/p1641396669154300

> To take a closer look at its dependencies and their vulnerabilities, I added it [babashka] to atomist's database (https://dso.atomist.com/images/babashka/babashka/digests/sha256%3A5fd551a5602ccce77a505fefed39f1ca2f76db3acc99b860ca1b876ea22a97bc), but we can only see those dependencies brought in by the base image because first babashka is uberjared and then made into a graal native-image, which squishes things even more. Scanners such as grype (https://github.com/anchore/grype) and trivvy  obviously don't see anything. 

**Describe the solution you'd like**
>I've been playing around with a lein plugin that generates what I'm calling a meta-bom-jar, that basically just contains the group, artifact and version of all a project's dependencies (https://github.com/kipz/lein-meta-bom). If we included this in the babashka Docker images, we could give vulnerability scanners visibility into the bill of materials in use by uberjars, graal native images and so on. I tried on a fork https://github.com/kipz/babashka/tree/metabom and it seems to work (in that grype can now see all the packages in the babashka images).

**Describe alternatives you've considered**
Other solutions include adding a bill-of-materials to Docker image metadata via labels, or to the native binaries themselves, but these would require changes to all the scanners to add support. They currently support many standard ecosystem packaging formats, one of which is maven, so a jar containing babashka's dependency metadata seems most appropriate here

**Comment by lispyclouds** [comment]
Closed via https://github.com/babashka/babashka/commit/3602b89512d9a6f07f0b97c76610bcde7c29a0e6
