### ISSUE TITLE
Add opencontainers image annotations for traceability

### ISSUE THREAD

**Issue by kipz** [babashka/babashka#1134]
**Is your feature request related to a problem? Please describe.**
It's currently not possible to examine a babashka docker image and link it back to a specific commit to a specific repository automatically (of course, by manual inspection we can know the GitHub repository and assume that the image tag is the same as the git tag).

**Describe the solution you'd like**
Include opencontainers image annotations (docker labels) during the build. These are standard and support by many tools, just as snyk, atomist etc. https://github.com/opencontainers/image-spec/blob/main/annotations.md

**Describe alternatives you've considered**
n/a

**Comment by lispyclouds** [comment]
Closed via https://github.com/babashka/babashka/commit/6e2c32ff84fc826fc9c10ecee29694a53258273e
