### ISSUE TITLE
Cannot create multidimensional arrays

### ISSUE THREAD

**Issue by erdos** [babashka/babashka#1144]
**version:** `0.7.3`
**platform:** linux-amd64
**problem:**

Multidimensional (>1) arrays cannot be created with into-array.

**repro:**
```
(into-array [(into-array [1])])
```

**expected behavior:**
Same as in Clojure.

Alternatively, an `Object[][]...` return value would also be a good default for most use cases.

**Comment by borkdude** [comment]
@erdos OK, this is probably just a matter of adding `java.lang.Long[][]` to the reflection config.

**Comment by erdos** [comment]
Hi @borkdude , I think it should be more than just adding `java.lang.Long[][]`, since it is still going to fail for many other types:

```
(into-array [(into-array ['a])])
(into-array [(into-array [1.0])])
(into-array [(into-array [true])])
(into-array [(into-array [(float 1)])])
(into-array [(into-array [(short 1)])])
(into-array [(into-array [:a])])
(into-array [(into-array ["a"])])
...
```
and then for higher dimensions, too:
```
(into-array [(into-array [(into-array [(into-array [1])])))
(into-array [(into-array [(into-array [(into-array [1])])))
...
```

Perhaps a change in semantic of `into-array` may be necessary so that it can still return `Object[]` (or `Object[][]` or `Object[][][]` etc) if the correct array type can not be found at runtime. wdyt?

**Comment by borkdude** [comment]
You're probably right.

**Comment by borkdude** [comment]
@erdos I looked at your ucl implementation and it looks really neat. If you have some optimization tricks that also can apply to SCI to make it (and bb) faster, you're welcome to propose them.

**Comment by borkdude** [comment]
@erdos Naively trying this:

``` clojure
(defn into-array
  "Returns an array with components set to the values in aseq. The array's
  component type is type if provided, or the type of the first value in
  aseq if present, or Object. All values in aseq must be compatible with
  the component type. Class objects for the primitive types can be obtained
  using, e.g., Integer/TYPE."
  {:added "1.0"
   :static true}
  ([aseq]
   (clojure.lang.RT/seqToTypedArray Object (seq aseq)))
  ([_type aseq]
   (clojure.lang.RT/seqToTypedArray Object (seq aseq))))
```

will cause errors in some code paths, e.g. when doing interop on certain types of arrays:

```
bb -e '(java.nio.file.Files/copy (.toPath (io/file "/tmp/test.clj")) (.toPath (io/file "/tmp/test2.clj")) (into-array [java.nio.file.StandardCopyOption/REPLACE_EXISTING]))'
```

Possible solutions: 

1) `try/catch` around the creation of the array, catch ` java.lang.IllegalArgumentException` and then fall back on object
2) Include the most common types arrays in the reflection config.

Thoughts?

**Comment by borkdude** [comment]
Now trying this:

``` clojure
(defn into-array
  "Returns an array with components set to the values in aseq. The array's
  component type is type if provided, or the type of the first value in
  aseq if present, or Object. All values in aseq must be compatible with
  the component type. Class objects for the primitive types can be obtained
  using, e.g., Integer/TYPE."
  {:added "1.0"
   :static true}
  ([aseq]
   (try (clojure.lang.RT/seqToTypedArray (seq aseq))
        (catch IllegalArgumentException _
          (clojure.lang.RT/seqToTypedArray Object (seq aseq)))))
  ([type aseq]
   (clojure.lang.RT/seqToTypedArray type (seq aseq))))
``` 

Explicity typed arrays will run unchanged, implicit typed arrays will fall back to Object. Seems to work and might be a reasonable compromise.

**Comment by erdos** [comment]
looks good, I like the latter approach. does it also work with `(into-array (type :f) [:f])` too?

**Comment by erdos** [comment]
Looks like `make-array` is also affected:
```
user=> (make-array (type :k) 3)
java.lang.IllegalArgumentException: Class clojure.lang.Keyword[] is instantiated reflectively but was never registered. Register the class by using org.graalvm.nativeimage.hosted.RuntimeReflection [at <repl>:2:1]
```

**Comment by borkdude** [comment]
@erdos I think for `(into-array (type :f) [:f])` it would be kind of wrong to return an object array, since the user explicitly requested an array of type keyword?
