### ISSUE TITLE
Add algo.monad to libtests + add to projects.md page

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#1152]
Manually tested:

``` clojure
$ clojure -M:babashka/dev --classpath $(clojure -Sdeps '{:deps {current/deps {:local/root "."}}}' -Spath):src/test/clojure -e "(require '[clojure.algo.test-monads]) (clojure.test/run-tests 'clojure.algo.test-monads)"

Testing clojure.algo.test-monads

Ran 11 tests containing 28 assertions.
0 failures, 0 errors.
{:test 11, :pass 28, :fail 0, :error 0, :type :summary}
```

**Comment by borkdude** [comment]
Forgot how to add lib tests with the CLI:

```
script/add-libtest.clj -g https://github.com/clojure/algo.monads -T src/main/test/clojure
```

doesn't seem to work...

**Comment by cldwalker** [comment]
First arg is the maven artifact name or a deps coordinate. `script/add-libtest.clj '{org.clojure/algo.monads {:mvn/version "0.1.6"}}' -g https://github.com/clojure/algo.monads -t` works for me. Deps coordinate is for gitlibs and the few unusual libs that aren't on clojars, which is unfortunately all of the clojure libs

**Comment by borkdude** [comment]
Will try!

**Comment by borkdude** [comment]
Thanks, that worked.
