### ISSUE TITLE
Task dependency edge case

### ISSUE THREAD

**Issue by benjamin-asdf** [babashka/babashka#1190]
babashka v0.7.4
and babashka v0.7.5

bb.edn:
```
{:tasks {task-b (do
                  (Thread/sleep 500)
                  :task00-out)
         task-c {:depends [task-b]
                 :task (do
                         (println
                          "task2: "
                          (type task-b))
                         {})}
         task-a {:task (do
                         (Thread/sleep 500)
                         :task0-out)}
         task-e {:depends [task-e1] :task {}}
         task-e2 {:depends [task-a] :task {}}
         task-e3 {:depends [task-b] :task {}}
         task-e1 {:depends [task-e2 task-e3]
                  :task {}}
         task-h {:depends [task-a task-b]
                 :task {}}
         task-d {:task (do (Thread/sleep 100) {})}
         task-f {:depends [task-d task-e task-a]
                 :task {}}
         task-g {:depends [task-f
                           task-d
                           task-a
                           task-c
                           task-h]
                 :task {}}}}

```

then you run `bb run --parallel task-g`

output: 
`task2:  clojure.core.async.impl.channels.ManyToManyChannel`

expected: (and also happens in the example when changing e.g. the timings or commenting out a task) 

`task2:  clojure.lang.Keyword`

I tried to narrow it down further and did not manage.
So from a high level description of the case it't with nested task dependencies and some timing.

**Comment by borkdude** [comment]
Can repro locally, thanks:

```
borkdude@MBP2019 /tmp $ bb run --parallel task-g
task2:  clojure.lang.Keyword
borkdude@MBP2019 /tmp $ bb run --parallel task-g
task2:  clojure.core.async.impl.channels.ManyToManyChannel
```

**Comment by borkdude** [comment]
Which OS are you on? I have found a solution and will post a link here for testing. The fix is on branch `issue-1190-task-race-condition`.

**Comment by benjamin-asdf** [comment]
linux and I'm shipping a script to windows team  mates.
@borkdude sick!

**Comment by borkdude** [comment]
Linux: https://26477-201467090-gh.circle-artifacts.com/0/release/babashka-0.7.7-SNAPSHOT-linux-amd64-static.tar.gz
Windows: https://ci.appveyor.com/api/buildjobs/s7784sw58vprwa8q/artifacts/babashka-0.7.7-SNAPSHOT-windows-amd64.zip

**Comment by benjamin-asdf** [comment]
For hammock, there is a leaky abstraction: Right now when a task returns nil, it will lock. 
1 idea is that bb ads a special `:task-null-value` or something on the channel, if the task returns nil.
For the user I would say the least surprising is if the symbol ends up being bound to nil.

**Comment by borkdude** [comment]
@benjamin-asdf Is that a newly introduced behavior? Please be as precise as possible with a complete repro, because I don't understand what you mean.

**Comment by benjamin-asdf** [comment]
@borkdude yea the behaviour changed, 

bb.edn
```
{:tasks {task-a {:task (println "lulling")}
         task-b {:depends [task-a]
                 :task (println task-a)}}}
```
old: 
```
bb run --parallel task-b
lulling
#object[clojure.core.async.impl.channels.ManyToManyChannel 0x3ec048ef clojure.core.async.impl.channels.ManyToManyChannel@3ec048ef]
```

new: 
```

./bb run --parallel task-b
lulling
```
-> it will wait forever now

fix: 

```
{:tasks {task-a {:task (do (println "lulling") :done)}
         task-b {:depends [task-a]
                 :task (println task-a)}}}
```


now: 
```
./bb run --parallel task-b
lulling
:done
```

**Comment by borkdude** [comment]
@benjamin-asdf Thanks for catching this. I think I might have fixed that one on master already. Please try again with:

Linux:
https://github.com/babashka/babashka-dev-builds/releases/download/v0.7.7-SNAPSHOT/babashka-0.7.7-SNAPSHOT-linux-amd64-static.tar.gz

Windows:
https://github.com/babashka/babashka-dev-builds/releases/download/v0.7.7-SNAPSHOT/babashka-0.7.7-SNAPSHOT-windows-amd64.zip

**Comment by benjamin-asdf** [comment]
@borkdude can confirm with the version you posted it evals to nil when the task return nil. (The least surprising behaviour).

**Comment by borkdude** [comment]
Thanks!
