### ISSUE TITLE
export symbols, so that humane-test-output works.

### ISSUE THREAD

**Issue by MrGung** [babashka/babashka#1197]
For human-readable outputs in clojure.test, I'd like to use https://github.com/pjstadig/humane-test-output (alternatives welcome!).

requiring pjstadig.humane-test-output I get 
`: Could not resolve symbol: pp/get-pretty-writer ... pjstadig/print.clj:9:20`

May it be possible to provide `clojure.pprint/get-pretty-writer` in babashka? There may be additional symbol-dependencies be lurking.

I am also willing to use a working alternative to pjstadig.humane-test-output.

**Comment by borkdude** [comment]
I'll have a look

**Comment by borkdude** [comment]
I looked into this, but it's more difficult than I thought. This library relies on hacks using private pprint vars, see utils.clj. You might have better luck rewriting this library without these hacks. I'll add `get-pretty-writer`.

**Comment by cldwalker** [comment]
I looked at this not too long ago also wanting to use it. I believe the only ns that needs converting is [util.cljc](https://github.com/pjstadig/humane-test-output/blob/master/src/pjstadig/util.cljc). These are the missing vars that remain:
* clojure.pprint - pp/print-logical-block, pp/write-out, pp/*current-length*, pp/print-newline, pp/print-length-loop
* clojure.test - inc-report-counter!, get-current-env

Dunno when I'll get to this but figured I'd at least share what's left

**Comment by borkdude** [comment]
@cldwalker Issues / PRs welcome for each of them.
