### ISSUE TITLE
add property `babashka.config` to reflect `bb.edn` location

### ISSUE THREAD

**Issue by mknoszlig** [babashka/babashka#1204]
When running in a task context, both `babashka.file` and `*file*` don't contain  helpful information.
The `babashka.task` property provides a hint  that we're running in task context, but it would be nice
to have access to the location of the corresponding `bb.edn` file as well.

This could be made available on startup via a property `babaska.config`.

**Comment by borkdude** [comment]
I'm ok with adding that.
