### ISSUE TITLE
Interrupting a babashka script results in exit status zero

### ISSUE THREAD

**Issue by leahneukirchen** [babashka/babashka#1211]
**version**

babashka v0.7.6

**platform**

Linux x86_64 glibc

**problem**

Interrupting a babashka script with Control-c (SIGINT) results in exit status zero, which is different to Clojure and unusual for Unix tools.

**repro**

```
% bb -e '(Thread/sleep 10000)'
^C
% echo $?
0
```

**expected behavior**

Like clojure:

```
% clj -e '(Thread/sleep 10000)' 
^C
% echo $?
130
```

**Comment by borkdude** [comment]
Thanks!
