### ISSUE TITLE
Async alt different from jvm (bug)

### ISSUE THREAD

**Issue by benjamin-asdf** [babashka/babashka#1216]
babashka v0.7.8

```clojure
(println
 (async/<!!
  (async/go
    (async/alts!
     [(async/go
        (async/<! (async/timeout 100))
        10)]))))
```

eval this with bb in some way, I tried as script and with nrepl.
outcome `nil` but we expect somehting like 

[10 #object[clojure.core.async.impl.channels.ManyToManyChannel 0x571e71cd "clojure.core.async.impl.channels.ManyToManyChannel@571e71cd"]]

this is how it comes out on the jvm

**Comment by borkdude** [comment]
Workaround:

``` clojure
(async/<!!
 (async/thread
   (async/alts!!
    [(async/thread
       (async/<!! (async/timeout 100))
       10)])))
```

Explanation: the single exclamation mark functions and go are "faked" by the double exclamation mark functions and `<!!` but there might be a bug in how we did that.

**Comment by borkdude** [comment]
Should be fixed on master.
