### ISSUE TITLE
Cljdoc build currently fails for babashka, consider fixing?

### ISSUE THREAD

**Issue by lread** [babashka/babashka#1218]
**version**
all

**platform**
all

**problem**
Because babashka includes cljc files, cljdoc assumes babashka is also a ClojureScript project and attempts a ClojureScript analysis which fails.

**repro**
See: https://cljdoc.org/d/babashka/babashka/0.7.8

**expected behavior**
I think it might be nice if the cljdoc could build babashka docs without failure.

**proposal**
We could fix the failure by explicitly telling cljdoc to only analyze for Clojure in babashka's existing `doc/cljdoc.edn` config.

**but...**
Are cljdoc docs appropriate for babashka?
- what public API does babashka want to document?
- there is already [babaska book](https://book.babashka.org/), does cljdoc docs add anything here?

**alternative**
If cljdoc docs are not appropriate for babashka, consider some way for cljdoc to direct users to the official appropriate docs (without presenting any errors).

**exhibit a**
A local test shows what API would be presented by cljdoc:

![image](https://user-images.githubusercontent.com/967328/160006850-c3a3166b-25ba-45e9-a350-c0d845e942c1.png)

**Comment by borkdude** [comment]
@lread I'd love for cljdoc to give an overview of all the "SCI" vars and docs that are available in babashka, so that people who use babashka can easily look up what functions they have available. This needs a special analysis step, by using a combination of `(all-ns)`, `ns-publics`, `meta` and `:doc`. Perhaps clj-doc could allow a custom analysis step/script in CI, as long as it outputs the right EDN(?) format?

**Comment by lread** [comment]
Yeah, sounds like an interesting idea @borkdude. 
@martinklepsch and I were chatting about such a cljdoc feature a little while ago.

So you'd have cljdoc document all the bb built-in namespaces and vars, yeah?

**Comment by borkdude** [comment]
Yup.

**Comment by lread** [comment]
Thanks! Added issue https://github.com/cljdoc/cljdoc/issues/565

**Comment by borkdude** [comment]
I'm open to fixes, but will close this until someone picks it up.
