### ISSUE TITLE
Add a reflection config for at-at

### ISSUE THREAD

**Issue by mikeananev** [babashka/babashka#1220]
**version**

babashka v0.7.8

**platform**

Mac Intel x86

**problem**

Can't stop a task using `at-at` library.

**repro**

mike@mbp02  ~ bb                                                                                                                                               (minikube/default)
Babashka v0.7.8 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (use 'overtone.at-at)
nil
user=> (def my-pool (mk-pool))
#'user/my-pool
user=> (every 1000 #(println "I am cool!") my-pool)
I am cool!
#<RecurringJob id: 1, created-at: Fri 11:35:13s, ms-period: 1000, initial-delay: 0, desc: "", scheduled? true>
user=> I am cool!
I am cool!
I am cool!
I am cool!
(stop *1)
Method cancel on class java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask not allowed! [at <repl>]
user=> I am cool!
I am cool!
I am cool!
^C%

**expected behavior**

The task is stopped.

**Comment by borkdude** [comment]
@mikeananev Should be fixed, you can download a new version via https://github.com/babashka/babashka-dev-builds when the current build on CI finishes.
