### ISSUE TITLE
`doc` sometimes doesn't print var name

### ISSUE THREAD

**Issue by dpsutton** [babashka/babashka#1223]
**version**

`Babashka v0.7.8 REPL.`

**platform**

osx

**problem**

babashka sometimes doesn't print a var name when using `doc`

**repro**

```clojure
❯ bb
Babashka v0.7.8 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (doc inc)
-------------------------
clojure.core/inc
([x])
  Returns a number one greater than num. Does not auto-promote
  longs, will throw on overflow. See also: inc'
nil
user=> (require '[clojure.string :as str])
nil
user=> (doc str/ends-with?)
-------------------------
clojure.string/ends-with?
([s substr])
  True if s ends with substr.
nil
user=> (require '[rewrite-clj.zip :as z])
nil
user=> (doc z/next)
-------------------------
rewrite-clj.zip/
([zloc])
  Return zipper with location moved to the next depth-first non-whitespace/non-comment node in `zloc`.
   End can be detected with [[end?]], if already at end, stays there.
nil
user=>
```

**expected behavior**

`rewrite-clj.zip/` should display as `rewrite-clj.zip/next`

**Comment by bobisageek** [comment]
I believe this is partially addressed in https://github.com/babashka/sci/pull/698

The rewrite-clj namespaces are pulled into babashka using SCI's copy-ns, so adding `:name` meta in copy-ns knocks out a lot of these.

Some comparisons using the repro example and a little blurb to count public vars without `:name` metadata:

0.7.8:
```clojure
user=> (doc rewrite-clj.zip/next)
-------------------------
rewrite-clj.zip/
([zloc])
  Return zipper with location moved...

user=> (->> (all-ns)
  (map ns-publics)
  (mapcat vals)
  (map (juxt identity (comp :name meta)))
  (filter (fn [[_ n]] (nil? n)))
  count)
502
```

master (adding `:name` in `copy-ns`):
```clojure
user=> (doc rewrite-clj.zip/next)
-------------------------
rewrite-clj.zip/next
([zloc])
  Return zipper with location moved...

; an example that's still 'broken'
user=> (doc doc)
-------------------------
clojure.repl/
Macro...

user=> (->> (all-ns)
  (map ns-publics)
  (mapcat vals)
  (map (juxt identity (comp :name meta)))
  (filter (fn [[_ n]] (nil? n)))
  count)
187
```

prospective change of adding `:name` to `macrofy` and `ns-new-var` (I haven't run the full test suite on this change yet):
```clojure
user=> (doc doc)
-------------------------
clojure.repl/doc
Macro...

user=>  (->> (all-ns)
  (map ns-publics)
  (mapcat vals)
  (map (juxt identity (comp :name meta)))
  (filter (fn [[_ n]] (nil? n)))
  count)
63
```

I'll see if I can get a PR done this weekend to try and make more progress on this.

**Comment by borkdude** [comment]
It seems to be fixed on master:
```
$ clojure -M:babashka/dev
Babashka v0.7.9-SNAPSHOT REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (require '[clojure.zip :as z])
nil
user=> (doc z/next)
-------------------------
clojure.zip/next
([loc])
  Moves to the next loc in the hierarchy, depth-first. When reaching
  the end, returns a distinguished loc detectable via end?. If already
  at the end, stays there.
nil
```

Does that mean this issue can be closed @bobisageek ?

**Comment by bobisageek** [comment]
The majority of instances are addressed on master due to the change on copy-ns, however there are still some instances (some in sci, some in babashka) where the `:name` metadata doesn't get set (which is what `doc` is using):

```clojure
Babashka v0.8.1-SNAPSHOT REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (doc doc)
-------------------------
clojure.repl/
Macro
nil
user=> (doc *read-eval*)
-------------------------
clojure.core/
nil
```

I actually have a branch working on sci where everything created using `new-var` et al gets the appropriate metadata, but I'm currently sort of battling through how to handle `*input*` in babashka, and I'm sure it wouldn't be appreciated if I made a PR on sci that broke (admittedly some really small and esoteric) use cases of bb. :)

I think I'm close - in fact, as I'm typing this I just had a bit of a breakthrough, so I'd say expect a PR in the next day or two (depending on outside factors).
