### ISSUE TITLE
brew upgrade and brew install babashka sha256 mismatch

### ISSUE THREAD

**Issue by esb-dev** [babashka/babashka#1244]
brew upgrade and brew install of babashka 0.8.0 gives the following error:

==> Downloading https://github.com/borkdude/babashka/releases/download/v0.8.0/ba
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################## 100.0%
Error: babashka: SHA256 mismatch
Expected: 284a3dc22b68459ed8b5633d893125d349c8e747c37c2cb7366bc742809c2c1f
  Actual: 6dd0a68974acb0dfdab4164c7361a07a19193a2acbe1f8ebd5c27c6b8110e679

**Comment by borkdude** [comment]
Should be fixed now. Sorry for the inconvenience.

**Comment by borkdude** [comment]
Run brew update once again before installing.

**Comment by esb-dev** [comment]
Thanks
