### ISSUE TITLE
babashka.tasks/shell should optionally log shell invocations for debugging

### ISSUE THREAD

**Issue by dgtized** [babashka/babashka#1249]
When developing scripts that shell out, it's often nicer to debug problems if all of the commands that shell out are logged like a script with `bash -x`.  Ie:

```
$ cat > t
echo a
touch t
echo b
^D

$ bash t
a
b
$ bash -x t
+ echo a
a
+ touch t
+ echo b
b
```

**Describe the solution you'd like**

It would be nice if the `babashka.tasks/shell` command had a global flag to log all commands executed that could be toggled on or off. Running bb with a flag like `--explain` would add logging for each shell invocation prior to the the corresponding output. That flag should toggle a variable like `*shell-explain*` so that it could be re-bound to a different value locally. 

Additional feature that might be nice: 
 * Display timing info & exit status from each command executed.
 * Log name and timing for each named bb task executed?

**Describe alternatives you've considered**

It is possible to do this locally by providing a helper like below:
```clojure
(def *shell-explain* false)
(defn shell [& cmd]
  (when *shell-explain*
    (println (apply str "+ " (interpose " " cmd))))
  (apply babashka.tasks/shell cmd))
```

This is a pretty low priority feature, but it's nice to have for development ergonomics. It's also possible that the underlying need for this is greater in environments such as bash, but I think it's still helpful with anything that is repeatedly shelling out to other programs.

**Comment by dgtized** [comment]
After looking briefly at `babashka.tasks`, it looks like it may be doing something like this in: https://github.com/babashka/babashka/blob/master/src/babashka/impl/tasks.clj#L87, but it's not clear how to raise/lower the log level to trigger that to be visible?

**Comment by borkdude** [comment]
I think it's better to have an option for this in `babashka.process/process` which `shell` calls to, e.g. something like:
```
:cmd-print-fn (fn [cmd] (apply println cmd))
```

**Comment by borkdude** [comment]
babashka/process now has a `:pre-start-fn`.

**Comment by borkdude** [comment]
Should we do anything beyond a `:pre-start-fn`? Let's first try that out and then we can take the next step.
