### ISSUE TITLE
Installation instructions for brew with mac m1 are confusing

### ISSUE THREAD

**Issue by dgb23** [babashka/babashka#1252]
**version**

I installed babashka v0.8.1 via Homebrew 3.4.9

**platform**

macos 12.1 Monterey

**problem**

Installed bb via homebrew on an mac m1 pro and wrote and tested some one liners and the REPL. It worked just as is without issues so far.

The installation instructions here suggest otherwise:

https://github.com/babashka/babashka#brew

Which did _not_ work - it requested me to install homebrew somewhere else?

**Comment by borkdude** [comment]
The M1 workarounds probably aren't necessary anymore with newer versions of macOS. I'll remove those tomorrow.
