### ISSUE TITLE
Signal handling?

### ISSUE THREAD

**Issue by perpen** [babashka/babashka#1279]
I am writing a small script for monitoring my laptop, and I would like to allow executing a command like "less" to view some logs.
Less depends on control-c for some things, and I am unable to make it work.

I am doing something like:
```
(process/process ["less" "-S" log] {:inherit true, :shutdown p/destroy})
```
But obv SIGINT goes to bb, that just exits.

I considered doing an exec system call, but that doesn't seem possible even with standard java.
Then I have been trying to intercept SIGINT from babashka, to transmit the signal to the Less child process.
But I am unable to import classes like `sun.misc Signal` from bb. The only signal-related code seems to be for PIPE.
Am I missing something?

PS: I am just discovering babashka, and it is AWESOME! I will definitely be using it a lot at home - pity my work colleagues don't like clojure much...

**Comment by borkdude** [comment]
@perpen You are in luck because that just got added in the master version.

You can install that using:

```
bash <(curl https://raw.githubusercontent.com/babashka/babashka/master/install) --version 0.8.3-SNAPSHOT --dir .
```

if you are on linux or mac. If you're using Windows, you can download the preview binary from https://github.com/babashka/babashka-dev-builds. Let me know how that goes and you can close the issue yourself if it works correctly for you.

**Comment by borkdude** [comment]
> I considered doing an exec system call

Btw, that is also possible now with the master version.

See https://github.com/babashka/process/blob/master/API.md#exec

**Comment by borkdude** [comment]
> PS: I am just discovering babashka, and it is AWESOME! 

Thank you! If you want to chat, feel free to join Clojurians Slack and come by in the babashka channel.

**Comment by perpen** [comment]
Thanks a lot @borkdude, total serendipity!

It took me some time to get the signal stuff working, I realised how little I know about java interop.
In case others are in the same situation:
```
(require '[babashka.process :as p])
(import 'sun.misc.Signal
        'sun.misc.SignalHandler)

(defn with-signal [command-line]
  (let [proc (p/process command-line
                        {:inherit true
                         :shutdown p/destroy})
        noop-sig-handler (reify SignalHandler
                           (handle [_ _] nil))]
    (. Signal (handle (Signal. "INT") noop-sig-handler))
    @proc))

(defn with-exec [command-line]
  (let [argv (concat [(first command-line)] command-line)]
    (p/exec argv)))

(let [command-line ["less" "/etc/passwd"]]
  (with-signal command-line)
  (with-exec command-line)
  (println "not happening"))
```
