### ISSUE TITLE
Programmatically starting an nrepl-server

### ISSUE THREAD

**Issue by Oddsor** [babashka/babashka#1295]
**Is your feature request related to a problem? Please describe.**
When using Babashka for long-running tasks, i.e. a simple web server, it would be nice to also be able to start an nrepl-server.

**Describe the solution you'd like**
Being able to write something like `(nrepl/start-server {:port 1234})`. The babashka.nrepl-library equivalents expect a sci-context, which hopefully can be abstracted away (🤞), but might otherwise be sufficient?

**Describe alternatives you've considered**
Chatting with @borkdude produced a nice workaround where you can start an nrepl-server using `bb nrepl-server` but also running a script-file using `--init`, for example: `bb --init webserver.clj nrepl-server <port>`

**Comment by borkdude** [comment]
Looks good. PR welcome if anyone sees this, else I'll get to it in time.
