### ISSUE TITLE
example http_server truncating response

### ISSUE THREAD

**Issue by henryw374** [babashka/babashka#1302]
**version**

0.7.8
**platform**

Mac

**problem**

The last bytes of a file are being truncated when using example from https://github.com/babashka/babashka/blob/master/examples/http_server_from_scratch.clj

Other files seem to be ok. possibly only affects files above a certain size or something.

**repro**

run the https://github.com/babashka/babashka/blob/master/examples/http_server_from_scratch.clj script and serve a file. In my case a 953k file of compiled js. almost all of the file is served apart from this bit at the end was missing `w,b,M([cw,!1]));LL(a);return JP()});
}).call(this);` 

Not a true repro I know, sorry. 

**expected behavior**

 full file content is served

**Comment by borkdude** [comment]
@henryw374 Any reason to use this while httpkit is also built-in?

**Comment by henryw374** [comment]
I was just googling to see how I could use babashka to server files from a dir and this is what came up.

Perhaps replace this example with some httpkit one-liners then?

**Comment by borkdude** [comment]
In this case I recommend using:

https://github.com/babashka/http-server

You can use it like this:

https://github.com/babashka/scittle/blob/77b55f658e4492d5e3384e2edaf81d3d11d4a8b1/bb.edn#L20

**Comment by henryw374** [comment]
cool. I didn't know about that. I've now got  this as file server script. & not seeing any truncated output now

```#!/usr/bin/env bb

(require '[babashka.classpath :refer [add-classpath]]
         '[clojure.java.shell :refer [sh]]
         '[clojure.string :as str])

(def deps '{:deps {io.github.babashka/http-server
        {:git/sha "b38c1f16ad2c618adae2c3b102a5520c261a7dd3"}}})

(def cp (-> (sh "clojure" "-Spath" "-Sdeps" (str deps)) :out str/trim))
(add-classpath cp)
(require '[babashka.http-server :as http])

(http/serve {:port 8080 :dir "."})
(println "Serving static assets at http://localhost:8080")
@(promise)
```

thanks

**Comment by borkdude** [comment]
@henryw374 You can replace shelling out to clojure using:

```
(def deps '{...})
(babashka.deps/add-deps deps)
```

or simply add the deps in `bb.edn`

**Comment by henryw374** [comment]
ooh nice feature. 

re bb.edn, I want to run this adhoc from any dir so will not have bb.edn there mostly.
