### ISSUE TITLE
Enhancements to BB pods downloading 

### ISSUE THREAD

**Issue by FieryCod** [babashka/babashka#1316]
**Is your feature request related to a problem? Please describe.**
Currently using BB with AWS Lambda is not straightforward when using BB pods. Babashka pods has to be downloaded first in CI environment or locally (dev environment) and next packed into a AWS Layer. The current pods resolvement is sufficient when one targets the same AWS Lambda architecture as CI/dev machine architecture. 

Unfortunately things get complex when user develops application on AMD64 and then wants to target ARM64, since the CI with ARM64 support would have to be required to download BB pods (alternatively one could download pods via script from github).

As per the [Slack conversation](https://clojurians.slack.com/archives/CLX41ASCS/p1656755933015229) to allow user to download pod for different architecture and OS the following tasks have to be done: TBD

**Comment by borkdude** [comment]
I think most things mentioned in here were implemented now by @cap10morgan in https://github.com/babashka/pods/commit/5754d433aa421c68b7558da92a852df69ab66e9d and other commits.
