### ISSUE TITLE
Can't evaluate (set! *warn-on-reflection* true) in nREPL

### ISSUE THREAD

**Issue by armincerf** [babashka/babashka#1330]
**version**

babashka v0.8.157

**platform**

MacOS 12.4 - M1 MacBook Pro

**problem**

When requiring a namespace that attempts to `set!` `*warn-on-reflection*`, an error occurs due to bb running in a non-binding thread. This prevented me from requiring hasch.core.

**repro**

Run `(set! *warn-on-reflection* true)` in a bb nrepl session

**expected behavior**

shouldn't throw an error

See here for slack discussion (and temporary workaround if you are having trouble requiring deps like hasch) https://clojurians.slack.com/archives/CLX41ASCS/p1659442359306899

**Comment by borkdude** [comment]
Note that this only happens when you call the nREPL server via the programmatic API:

```
{:paths ["src"]
 :deps {io.replikativ/hasch {:mvn/version "0.3.7"}}
 :tasks
 {:requires ([babashka.fs :as fs]
             [babashka.nrepl.server :as srv])
  nrepl (binding [*warn-on-reflection* *warn-on-reflection*]
          (srv/start-server! {:host "localhost"
                              :port 1667})
          (spit ".nrepl-port" "1667")
          (-> (Runtime/getRuntime)
              (.addShutdownHook
               (Thread. (fn [] (fs/delete ".nrepl-port")))))
          (deref (promise)))}}
```

**Comment by borkdude** [comment]
This can be fixed by giving the same default options that are passed in `babashka.main`, but in `babashka.impl.nrepl_server.clj`.
