### ISSUE TITLE
README: Change Babashka logo link to point to babashka.org

### ISSUE THREAD

**Issue by rads** [babashka/babashka#1332]
Right now the big logo in the README links to the [image file](https://github.com/babashka/babashka/blob/master/logo/babashka.svg) in the GitHub repo. Would it make more sense to link to the [Babashka website](https://babashka.org) instead?

**Comment by borkdude** [comment]
I'm not sure why it should link to anything at all, but I'm fine with what you proposed too :)

**Comment by rads** [comment]
@borkdude: At first I thought the link was in the README itself, but it looks like GitHub is doing this. So if we are forced to make a choice, it's better to send people to a link that makes sense.

That said, I think making an explicit link here is still useful even if GitHub didn't have this behavior. The logo is a big piece of the screen and this will naturally point people to a place to find more info rather than leaving them at a dead end.

**Comment by rads** [comment]
Resolved in #1333.
