### ISSUE TITLE
Bump `rewrite-clj` to the latest version

### ISSUE THREAD

**Issue by zharinov** [babashka/babashka#1334]
**Is your feature request related to a problem? Please describe.**
I'm trying to establish CI pipeline for `zprint` project, and it contains Babashka adjustments you kindly provided some time ago.
From what I see, `zprint` has started to use `of-node*` function from `rewrite-clj`, which isn't defined in current version of the Babashka `rewrite-clj` dependency.

**Describe the solution you'd like**
Hopefully it would be as simple as bumping version in couple of places, and I'm ready to make the PR if you're okay with it.

**Describe alternatives you've considered**
Probably there is a way for `zprint` to explicitly use recent `rewrite-clj`, but I had no success when adding it to `bb.edn`.

**Additional context**
- https://github.com/clj-commons/rewrite-clj/issues/178
- https://github.com/kkinnear/zprint/issues/247

**Comment by borkdude** [comment]
Done.
