### ISSUE TITLE
Improper expansion of `Foo.` record constructor in syntax quote

### ISSUE THREAD

**Issue by frenchy64** [babashka/babashka#1339]
**version**

babashka v0.9.161

**platform**

Intel macOS 12.4

**problem**

If `(defrecord Foo [])` then
```
`Foo.
```
should expand to `'user.Foo.`, instead bb expands to just `'Foo.`
**repro**

```clojure
$ bb
Babashka v0.9.161 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (defrecord Foo [])
user.Foo
user=> `Foo.
Foo.
```

**expected behavior**

```
$ clj
Clojure 1.11.1
user=> (defrecord Foo [])
user.Foo
user=> `Foo.
user.Foo.
```

**Comment by borkdude** [comment]
Thanks! Yes, we should fix this. Did you run into a bug with this in a real program?

**Comment by frenchy64** [comment]
Yes, basically this:

```clojure
(defrecord Foo [])
(deftest my-test
  (is (eval `(Foo.))))
```

**Comment by borkdude** [comment]
The relevant bits in clojure.tools.reader seems to be here:

https://github.com/clojure/tools.reader/blob/master/src/main/clojure/clojure/tools/reader.clj#L653

Note that tools.reader also resolves `Foo...` while LispReader only resolves `Foo.` (one single dot).

**Comment by frenchy64** [comment]
Yes: https://github.com/plumatic/schema/pull/432/files#diff-fe7b2ea70d8a9f6dcb9ab8ffbd07a2812520ba2b988ee88b4681bd29e5dae5cdR1611

-------- Original Message --------

**Comment by borkdude** [comment]
OK, thanks for following up. Should be fixed now.
