### ISSUE TITLE
add (open?) support for clojure.reflect namespace in babashka

### ISSUE THREAD

**Issue by jlb0170** [babashka/babashka#1341]
**Describe the solution you'd like**

```
user=> (mapv :name (filter (comp :public :flags) (:members (clojure.reflect/reflect d))))
Could not resolve symbol: clojure.reflect/reflect [at <repl>]
user=> (require 'clojure.reflect)
java.lang.Exception: Could not find namespace: clojure.reflect. [at <repl>:10:1]
```

**Additional context**
from slack discussion on clojurians #babashka here:
https://clojurians.slack.com/archives/CLX41ASCS/p1660747682234929?thread_ts=1660747299.201339&cid=CLX41ASCS

**Comment by borkdude** [comment]
I added `clojure.reflect/reflect` for the next release.
