### ISSUE TITLE
core.async/to-chan! does not exist error

### ISSUE THREAD

**Issue by cap10morgan** [babashka/babashka#1370]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

0.9.162

[ Please specify which version of babashka you're using. You can find this with `babashka --version`. The documentation on the master branch may be ahead of the most released version. ]

macOS 12.6 arm64

[ Please specify which platform you are using babashka on, so you can test a
new binary when the issue is resolved. ]

It looks like babashka 0.9.162 embeds core.async v1.5.648, which deprecates `to-chan` in favor of `to-chan!` and `to-chan!!` [source code](https://github.com/clojure/core.async/blob/ff82b69a2c81e5764738d0041702d7c6b1612643/src/main/clojure/clojure/core/async.clj#L688-L738).

However, when I try to run some code using `to-chan!` with bb v0.9.162, I get this error:

```
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  to-chan! does not exist
Location: /Users/wmorgan/dev/docker-clojure-master/src/docker_clojure/core.clj:2:3

----- Context ------------------------------------------------------------------
1: (ns docker-clojure.core
2:   (:require
     ^--- to-chan! does not exist
3:     [clojure.java.shell :refer [sh with-sh-dir]]
4:     [clojure.math.combinatorics :as combo]
5:     [clojure.spec.alpha :as s]
6:     [clojure.string :as str]
7:     [clojure.core.async :refer [<!! chan to-chan! pipeline-blocking] :as async]

----- Stack trace --------------------------------------------------------------
docker-clojure.core                       - /Users/wmorgan/dev/docker-clojure-master/src/docker_clojure/core.clj:2:3
user-d5d33276-0b4d-4d51-945f-bee8f8a892ae - <expr>:4:47
```

[ Please provide a short and to the point description of the problem ]

`bb -e "(require '[clojure.core.async :refer [to-chan!]])"`

[ Please provide a minimal working reproduction of the problem ]

When I run the same code with the tools.deps `clojure` command, it works.

[ What is the behavior you expected to see? Please provide a minimal working example ]

**Comment by borkdude** [comment]
This needs to be enabled in the SCI mappings in bb .
