### ISSUE TITLE
JVM locales aren't included in babashka native image

### ISSUE THREAD

**Issue by egli** [babashka/babashka#1373]
**version**
babashka v0.9.162

**platform**

Ubuntu 22.04.1 LTS

**problem**
I'd like to print localized dates with selmer.

``` clojure
(render "{{now|date:\"cccc\":de}}" {:now (java.util.Date.)})
```
This returns "Fri" instead of correctly "Freitag". Using the JVM this works flawlessly.

**repro**
Render a localized date using Selmer on the JVM:

```
$ lein repl
nREPL server started on port 34279 on host 127.0.0.1 - nrepl://127.0.0.1:34279
REPL-y 0.4.3, nREPL 0.6.0
Clojure 1.10.0
OpenJDK 64-Bit Server VM 11.0.16+8-post-Ubuntu-0ubuntu122.04
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

foo.core=> (use '[selmer.parser])
nil
foo.core=> (render "{{now|date:\"cccc\":de}}" {:now (java.util.Date.)})
"Freitag"
```

Now try to do the same thing using Babashka:

```
~ $ bb
Babashka v0.9.162 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (use '[selmer.parser])
nil
user=> (render "{{now|date:\"cccc\":de}}" {:now (java.util.Date.)})
"Fri"
```

**expected behavior**
Return the correct localized string. 

But since a perfect solution is not without drawbacks (see References below) I would suggest that for now just documenting this problem would at least prevent some users from being surprised.

**References**
I believe this might be related to oracle/graal#2908 where they say that _native executables produced by the native-image command contain only the single locale that has been returned by `Locale.getDefault()` in the building JVM_. Apparently there are efforts under way to enable the inclusion of more locales, but I'm not sure if those are ready or if it is even desired to include more locales in the native image itself.

**Comment by borkdude** [comment]
We can include more locals but adding _all_ locales adds 5mb of image size (last time I checked, might be different now), so that is the trade-off. So far it hasn't been request that much, so I'm leaning towards not adding all locales.

The Graal arguments are this:

```
For adding only French and English: -H:IncludeLocales=fr,en. 
All locales can be included via -H:+IncludeAllLocales
```

Feel free to experiment locally with this an provide details on image size difference.
