### ISSUE TITLE
Add randomUUID to reflection config

### ISSUE THREAD

**Issue by arichiardi** [babashka/babashka#1383]
Hi babashka folks,
there is a new built-in for this but code bases against old versions of clojure usually use `(java.util.UUID/randomUUID)` pretty heavily.

This is the error I got:

```
No matching field found: randomUUID for class java.util.UUID
 at sci.impl.Reflector.getStaticField (Reflector.java:360)
    sci.impl.interop$get_static_field.invokeStatic (interop.cljc:47)
    sci.impl.resolve$lookup_STAR_$reify__4162.eval (resolve.cljc:65)
    ...
```

**Comment by arichiardi** [comment]
I'd also like to ask if possible for me to get a lil' intro around the reflection config :smile:

**Comment by borkdude** [comment]
This should already work with bb:

```
$ bb -e "(java.util.UUID/randomUUID)"
#uuid "26911c1f-d021-4185-8d1e-8e6af6827f28"
```

Do you have a repro in which it doesn't work?

**Comment by arichiardi** [comment]
Oh that's weird, I did try to repro and it worked with `import` as well.

```clojure
user=> (import 'java.util.UUID)
java.util.UUID
user=> (UUID/randomUUID)
#uuid "fbc93dc9-976c-4e8a-8ce2-7469585aee1a"
```

I might have tried on an old version. I guess I can close this. Sorry for the noise.
