### ISSUE TITLE
indexOf now working on clojure.lang.LazySeq

### ISSUE THREAD

**Issue by arichiardi** [babashka/babashka#1384]
**version**
`v0.10.163`

**platform**

JVM

**problem**
The following does not work in `bb`:

```clojure
Clojure rocks, Bash reaches.

user=> (.indexOf (map identity [1 2 3]) 2)
No matching method indexOf found taking 1 args for class clojure.lang.LazySeq
```

JVM behavior

```clojure
Clojure 1.11.1
user=> (.indexOf (map identity [1 2 3]) 2)
1
```

**Comment by borkdude** [comment]
It would be interesting to see the real life use case of this one, do you have that reference?

**Comment by arichiardi** [comment]
Well, I do exactly what's in the example above. I know I can work this around by using `mapv` instead of a `map` but I figured I should report the different.
