### ISSUE TITLE
Include `hiccup2.core/raw` and possibly other hiccup nss

### ISSUE THREAD

**Issue by mk** [babashka/babashka#1391]
Babashka includes the hiccup2.core namespace but the [raw](https://cljdoc.org/d/hiccup/hiccup/2.0.0-alpha2/api/hiccup2.core#raw) var is missing:

```clojure
(ns-publics (find-ns 'hiccup2.core)) ;;=> {html #'hiccup2.core/html}
```

(Using v0.9.162)

In case it doesn't bloat the binary, other helpers like https://cljdoc.org/d/hiccup/hiccup/2.0.0-alpha2/api/hiccup.page might also be nice to include.

**Comment by borkdude** [comment]
Thanks!
