### ISSUE TITLE
Expose `sci.lang.Namespace`

### ISSUE THREAD

**Issue by zampino** [babashka/babashka#1397]
It would be nice to be able to ask `(instance? sci.lang.Namespace x)` in a babashka runtime (e.g JVM platform).

It seems we can reach `sci.lang.Var` but not the namespace type:
```
Babashka v0.10.164-SNAPSHOT REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (instance? sci.lang.Var "ahoi")
false
user=> (import '[sci.lang Var])
sci.lang.Var
user=> (instance? Var 123)
false
user=> Var
sci.lang.Var
user=> (import '[sci.lang Namespace])
java.lang.Exception: Unable to resolve classname: sci.lang.Namespace [at <repl>:5:1]
user=> 
```

**Comment by borkdude** [comment]
I've mapped `clojure.lang.Var` to `sci.lang.Var`. We can do something similar for `clojure.lang.Namespace` -> `sci.lang.Namespace` (since clojure's namespace should not be reachable anyway in bb). 

A workaround for now is: `(instance? (type *ns*) ...)`
