### ISSUE TITLE
Uberjar command doesn't work properly when bb.edn has empty :deps map

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#1399]
Repro:

bb.edn
```
{
 :deps {}
 }
```

I think in this case the following command should succeed and produce an empty jar:

```
bb uberjar foo.jar
```

but it errors with `uberjar needs a classpath`. 

When we have a `bb.edn` we always have an implicit classpath. For the above it should probably be the empty string and not `nil` like is demonstrated here:

```
$ bb -e '(prn (babashka.classpath/get-classpath))'
nil
```

**Comment by lispyclouds** [comment]
I'm taking a crack at this and have the 2 questions if we return an `""` in this case:
- Does this mean that this [path](https://github.com/babashka/babashka/blob/master/src/babashka/main.clj#L1032) will never taken?
- This [test](https://github.com/babashka/babashka/blob/master/test/babashka/uberjar_test.clj#L82) is irrelevant?

**Comment by lispyclouds** [comment]
I'm thinking of a fix [here](https://github.com/babashka/babashka/blob/master/src/babashka/impl/classpath.clj#L105) as:
```clojure
(defn get-classpath
  "Returns the current classpath as set by --classpath, BABASHKA_CLASSPATH and add-classpath."
  []
  (or (:cp @cp-state) ""))
```

**Comment by borkdude** [comment]
It might be good to check if that doesn't cause the current directory to be on the classpath...

**Comment by lispyclouds** [comment]
Yeah that was my next thing, I'm seeing quite a lot of junk in the jar after this change 😛

**Comment by borkdude** [comment]
I think we should isolate the change just to the uberdeps. Check if there is classpath OR a config, then it's fine to continue, else keep the warning.
