### ISSUE TITLE
Referencing mutable field immediately after assignment gives old value

### ISSUE THREAD

**Issue by athos** [babashka/babashka#1401]
**version**

`babashka v1.0.164`

**platform**

Apple M2 macOS 12.6

**problem & repro**

Referencing a mutable field immediately after assignment gives the old value, as follows:

```clojure
(defprotocol ICounter (inc! [_]))

(deftype Counter [^:unsynchronized-mutable n]
  ICounter
  (inc! [_]
    (prn :before n)
    (set! n (inc n))
    (prn :after n)
    n))

(def c (->Counter 0))
(inc! c)
;; :before 0
;; :after 0
;=> 0

(inc! c)
;; :before 1
;; :after 1
;=> 1
```

I think this is caused at the sci level, but I wasn't sure how I reproduce it directly with sci, so I reported this here.

**expected behavior**

The assignment successfully updates the mutable field to the new value.

**Comment by borkdude** [comment]
Thanks

**Comment by borkdude** [comment]
Another difference is the return value of `set!`. In Clojure it returns the new value, but in SCI it returns a map with the new value (which is wrong).

**Comment by borkdude** [comment]
Repro in pure SCI:

```
user=> (sci/eval-string "(defprotocol ICounter (inc! [_])) (deftype Cnt [^:unsynchronized-mutable n] ICounter (inc! [_] (let [old-n n new-n-set (set! n (inc n)) new-n n] [old-n new-n-set new-n]))) (inc! (->Cnt 1))")
[1 {n 2} 1]
```

Expected result: `[1 2 2]`.

**Comment by athos** [comment]
Thank you for the quick fix!

**Comment by borkdude** [comment]
You can get a new binary here:

https://github.com/graalvm/graalvm-ce-dev-builds/releases

until the next release
