### ISSUE TITLE
exec needs full qualified function but errors obtusely if namespace not found

### ISSUE THREAD

**Issue by dmg46664** [babashka/babashka#1410]
**version**
v1.0.164

**platform**
Mac

**problem**

exec needs full qualified function but errors obtusely if namespace not found.

```
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  Could not find namespace: top.build.build.
Location: <expr>:4:47

----- Context ------------------------------------------------------------------
1:
2:  ;; deps
3:
4: (ns user-f39cc2e2-32f4-4dd5-b013-7c98601c1be1 (:require [top.build.build :as build]))
                                                 ^--- Could not find namespace: top.build.build.
5: (require '[babashka.tasks #_#_:refer [log]])
6: (when-not (resolve 'clojure)
7:   ;; we don't use refer so users can override this
8:   (intern *ns* 'clojure babashka.tasks/clojure))
9:

----- Stack trace --------------------------------------------------------------
user-f39cc2e2-32f4-4dd5-b013-7c98601c1be1 - <expr>:4:47
```

**repro**

https://github.com/dmg46664/problems/tree/main/05_bb_local_root
https://clojurians.slack.com/archives/CLX41ASCS/p1666789705942659

**expected behavior**

Any message stating that the fully qualified function passed to exec cannot be found.

**Comment by borkdude** [comment]
What was the `bb.edn` exec you had for this case?

**Comment by dmg46664** [comment]
@borkdude Sorry, must have lost your response somewhere in my inbox.
No clear from the reproduction link?

**Comment by borkdude** [comment]
I'm not sure what to improve here. bb already says: `Could not find namespace ..` similar to what Clojure does:

```
$ clojure -X foobar/foo
Namespace could not be loaded: foobar
```

Any suggestions?

**Comment by dmg46664** [comment]
Been a while, and I needed to correct the `defn justrun` to take `[& _args]`.
This is required in order to allow `(exec 'top.build.build/justrun)` to pass.

However `(exec 'build/justrun)` fails as per:
```
 ~/p/problems/05_bb_local_root  bb justrun 
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  Could not find namespace: build.
Location: <expr>:4:1

----- Context ------------------------------------------------------------------
1:
2:  ;; deps
3:
4: (ns user-7c952784-28ae-4401-abfa-733bb75ea876 (:require [top.build.build :as build]))
   ^--- Could not find namespace: build.
5: (require '[babashka.tasks #_#_:refer [log]])
6: (when-not (resolve 'clojure)
7:   ;; we don't use refer so users can override this
8:   (intern *ns* 'clojure babashka.tasks/clojure))
9:

----- Stack trace --------------------------------------------------------------
user-7c952784-28ae-4401-abfa-733bb75ea876 - <expr>:26:1
```

If I remember correctly what is confusing here, is it can't find the namespace build despite build being `:require`'d in the task section. I.e. it's available to be used in scripts, but because `exec` specifically requires the fully qualified namespace, this is the cause of the error. I didn't know this and it's not easily discernable in the error message. My reaction is "but I have :required build!", and there is nothing indicating in the error that it can't find the fully qualified namespace, or that the error is coming out of `exec`.

If you're happy with this quirk, feel free to close.
Otherwise I suggest something in the error stating that "babashka.tasks/exec is looking for the fully qualified namespace 'build/justrun which cannot be found".

@borkdude does that help?

**Comment by borkdude** [comment]
Yep, the confusion with the alias makes sense

**Comment by borkdude** [comment]
I don't know how to improve this specific case, but I think you can use

```
(exec `build/foo)
```

instead.

**Comment by borkdude** [comment]
Sorry, no you can't since backticks aren't allowed in EDN files.
