### ISSUE TITLE
Automatically discover next available port for `nrepl-server`

### ISSUE THREAD

**Issue by berquist** [babashka/babashka#1429]
**Is your feature request related to a problem? Please describe.**

`nrepl-server` allows not specifying a hostname+port if you're ok with `localhost:1668`, but if that port is already in use, an exception gets thrown. This means using babashka via CIDER will error if you try to start more than one server, as opposed to the default Clojure CLI behavior which automatically looks for the next available port.

**Describe the solution you'd like**

Automatically try the next available port on the given host in the event that one was not explicitly specified.

**Describe alternatives you've considered**

This is only for CIDER and won't work on Windows:
```emacs-lisp
(require 'cider)

;;;###autoload
(defun cider-jack-in-bb ()
  "Start a babashka nREPL server for the current project and connect to it."
  (interactive)
  ;; First try and find an open port, starting at the "default" bb nREPL port
  ;; of 1667.
  (let* ((port 1666)
         (lsof-cmd "lsof -P -i TCP:%d")
         (lsof-output 0))
    (while (zerop lsof-output)
      (setq port (1+ port)
            lsof-output (shell-command (format lsof-cmd port))))
    ;; An open port has been found, start 'bb nrepl-server' and pass it to
    ;; CIDER.
    (let* ((hostname "localhost")
           (project-dir default-directory)
           (params (list :host hostname
                         :port port
                         :project-dir project-dir))
           (bb-cmd (format "bb nrepl-server %s:%s" hostname port)))
      (nrepl-start-server-process
       project-dir
       bb-cmd
       (lambda (server-buffer)
         (cider-connect-sibling-clj params server-buffer))))))
```

**Comment by borkdude** [comment]
You can use port 0 and then it will choose a random port.

**Comment by berquist** [comment]
It does exactly what I want. Is it documented anywhere? I couldn't find it in the book.

**Comment by borkdude** [comment]
PR welcome to the book :)

**Comment by borkdude** [comment]
Thanks, I'll take a look at this tomorrow
