### ISSUE TITLE
Document requirements for running babashka on alpine

### ISSUE THREAD

**Issue by wagjo** [babashka/babashka#1434]
I had issues running babashka inside docker on `eclipse-temurin:17-alpine`, getting following error

`/usr/local/bin/bb: No such file or directory`

babashka was installed via curl script. The error was due to following file missing `/lib64/ld-linux-x86-64.so.2` (FYI, you can see what files are loaded by running `ldd /usr/local/bin/bb`)

To fix this issue on alpine, a gcompat package needs to be installed, e.g. with `apk add gcompat`.

If alpine is officially suported by bb, please document this requirement in the Installation section.

**Comment by borkdude** [comment]
Hey @wagjo! On alpine you can use the static binary which can be installed by providing the `--static` flag to the install script.

**Comment by borkdude** [comment]
We should indeed document that, PR welcome

**Comment by borkdude** [comment]
Alpine is fully supported: bb even provides alpine docker images:

https://hub.docker.com/layers/babashka/babashka/alpine/images/sha256-1b68e2a34e72d62e85f86eadbaebe378f642d2edc17af689c78041c0c12f5487?context=explore

This uses the static binary.

**Comment by borkdude** [comment]
@wagjo Can you follow up if this solved the problem for you?
