### ISSUE TITLE
expose query-string function in org.httpkit.client

### ISSUE THREAD

**Issue by damianr99** [babashka/babashka#1438]
Currently there's no easy way to create a properly encode query string parameter for a URL from a map.  There's a version in babashka.curl, but you can't get the URL back, only pass it to curl directly.  There's a version in org.httpkit.client/query-string, but it's not exported/available.  Could we expose the the org.httpkit.client one?

**Comment by bobisageek** [comment]
I have a PR for this, but I wanted to ask - while the "hood is open", so to speak, on that ns, would it be desirable to also expose the `url-encode` function? It's a very thin wrapper over `URLEncoder/encode`, but just from an API completeness standpoint, I thought I'd ask.

**Comment by borkdude** [comment]
Eventually I want to incorporate `babashka.http-server` which is based on JDK11 and closely follows `babashka.curl`.
I think https://github.com/schmee/java-http-clj can be a starting point or something which looks like it. Perhaps something which looks like hato which also has "middleware" which adds stuff to a request based on what's in the request map.
So I'm tempted to make a start with that namespace and expose that there without adding more stuff into the other client namespaces.

But given that there's nothing in bb like that yet, it sounds reasonable to add that to either babashka.curl or org.httpkit, although it will take up extra binary size.

**Comment by borkdude** [comment]
It's not so hard to copy the code from those namespaces and evaluate it inside bb maybe.

**Comment by borkdude** [comment]
It'll probably not make that big of a difference, let's just expose these things.

**Comment by borkdude** [comment]
It made exactly no difference in binary size :) Probably because those functions were already hit by other paths in other exposed functions. Thanks y'all :)
