### ISSUE TITLE
`clojure.pprint` is missing `code-dispatch`

### ISSUE THREAD

**Issue by aviflat** [babashka/babashka#1446]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

**version:** 1.0.168

[ Please specify which version of babashka you're using. You can find this with `babashka --version`. The documentation on the master branch may be ahead of the most released version. ]

**platform:** MacOS 12.6.1 on an M1 Mac.

[ Please specify which platform you are using babashka on, so you can test a
new binary when the issue is resolved. ]

**problem:** it’s missing

[ Please provide a short and to the point description of the problem ]

**repro:**

```shell
➜ bb
Babashka v1.0.168 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (require '[clojure.pprint :as pp])
nil
user=> pp/code-dispatch
Could not resolve symbol: pp/code-dispatch [at <repl>:5:-16]
```

[ Please provide a minimal working reproduction of the problem ]

**expected behavior:** I expected the namespace to include the var with its value being the function from the Clojure stdlib.

[ What is the behavior you expected to see? Please provide a minimal working example ]

```shell
➜  clj
Clojure 1.11.1
user=> (require '[clojure.pprint :as pp])
nil
user=>  pp/code-dispatch
#object[clojure.lang.MultiFn 0x3153ddfc "clojure.lang.MultiFn@3153ddfc"]
```

**Comment by borkdude** [comment]
Will add. Can you give some examples of how you'd use this?

**Comment by aviflat** [comment]
Thanks!

Example:

```clojure
  (pp/with-pprint-dispatch pp/code-dispatch
    (binding [pp/*print-right-margin* 80]
       (pp/pprint generated-code-or-parsed-edn-etc))))
```

**Comment by borkdude** [comment]
@aviflat You can install the latest dev-build with:

```
bash <(curl https://raw.githubusercontent.com/babashka/babashka/master/install) --dev-build --dir /tmp
```

This install the bb binary in `/tmp`
