### ISSUE TITLE
Classpath 'stuck' on different project while tasks works

### ISSUE THREAD

**Issue by naxels** [babashka/babashka#1448]
**version** : babashka v1.0.167 & also v1.0.168

[ Please specify which version of babashka you're using. You can find this with `babashka --version`. The documentation on the master branch may be ahead of the most released version. ]

**platform**: macOS intel 64

[ Please specify which platform you are using babashka on, so you can test a
new binary when the issue is resolved. ]

**problem**
For some reason the classpath seems to be stuck on a project, and when switching to a new project, causes bb 'task' to fail

In my case, project youtube-channel-data, start bb:
`(babashka.classpath/get-classpath)`
has the classpath I expect

Then switch to a different project and start bb, also run the above statement
all of a sudden, the classpath is not listed. however it does have the full classpath listed from the first project!

Is there some sort of caching going on somewhere that I'm not aware of?

ps: my ~/.clojure/deps.edn is the default, nothing changed so all comments excepts a few {}'s

[ Please provide a short and to the point description of the problem ]

**repro**

I don't know how to get the classpath to stick, however what I did was:
1. create a new folder (I have a main projects folder, then create new folder to start, add deps.edn and fill)
2. fill deps.edn with :paths, :deps + save
3. create bb.edn and add the following line:
  4. `{:deps {local/deps {:local/root "."}}}`
5. save
6. run bb
7. execute: `(babashka.classpath/get-classpath)`
8. for some reason, now you don't see the current folders/classpaths, however the sticky project's classpath.

Adding a task to bb.edn
and running: `bb tasks` actually does show the current folders bb.edn tasks
however executing a task (in my case, running a -main) results in an error, classpath not found

Here's what is interesting:
in a random folder, I executed bb, then did `(babashka.classpath/get-classpath)`, which resulted in `nil`
however.. then I add a bb.edn file and just add this:
`{:deps {local/deps {:local/root "."}}}`
Then run bb again and `(babashka.classpath/get-classpath)`
now it's stuck again on the first project's classpath!

A workaround that does work (in my case for executing the task with -main):
in bb.edn, add `:paths ["src"]`

however when looking again at `(babashka.classpath/get-classpath)`
it lists "src:(sticky project)" as classpath

[ Please provide a minimal working reproduction of the problem ]

**expected behavior**

I expected bb to use the current folder/project's classpath like it uses the current folder/project's tasks list

[ What is the behavior you expected to see? Please provide a minimal working example ]

**Comment by borkdude** [comment]
The clojure CLI indeed caches classpaths and this is done by looking at the library coordinate: `local/deps`. If you use a different name in your other project, e.g. `naxels/youtube-downloader {:local/root "."}` the problem should resolve itself. 

So we have to change the recommendation of using a different unique name instead of `local/deps`.

**Comment by borkdude** [comment]
Changed the docs here: https://book.babashka.org/#project-setup

**Comment by naxels** [comment]
Perfect, that fixed it :)
Thanks!
