### ISSUE TITLE
Publish binaries with all build options enabled

### ISSUE THREAD

**Issue by lnchan** [babashka/babashka#1453]
**Is your feature request related to a problem? Please describe.**
I appreciate babashka's built-in libraries and runtime quite a lot; however, it seems unfortunate that the released GitHub builds do not include most of them even though they would be extremely useful to have (JDBC, SQLite for JDBC, ...)

**Describe the solution you'd like**
Would it be possible to release additional complete builds for users who do not care about babashka's binary size, and wish to have those built-in?

**Describe alternatives you've considered**
Making custom builds of babashka is mostly inconvenient or even difficult on some platforms due to GraalVM, such as Windows or Alpine.

**Comment by borkdude** [comment]
@lnchan I can't commit to this since adding an unlimited amount of things in bb will inevitably lead to more RAM usage and we don't have unlimited RAM in the public cloud environments we use. You're free to set this up yourself and distribute an alternative version of babashka with as many libraries you like.

**Comment by borkdude** [comment]
@lnchan Note that you can use various pods for SQL etc:

https://github.com/babashka/pod-registry

**Comment by lnchan** [comment]
I have been using your SQLite3 Go pod as a replacement, though JDBC is quite convenient; too bad for the RAM limitations, but thank you for your reply! I will most likely use custom builds for now, but it seems a shame that things might not be as "drop-in compatible" as I'd like them to be if users or package managers are expected to have custom builds.
