### ISSUE TITLE
bb tasks stale classpath/could not find namespace

### ISSUE THREAD

**Issue by jacobobryant** [babashka/babashka#1457]
Sometimes when I run a task, I get a `Could not find namespace` exception. Running `bb --force` fixes it. For example, I was able to trigger the exception just now after creating the following files in a fresh directory:

```
$ tree
.
├── bb.edn
├── deps.edn
└── src
    └── com
        └── example.clj

2 directories, 3 files

$ cat bb.edn
{:deps {local/deps {:local/root "."}}
 :tasks {hello com.example/hello}}

$ cat deps.edn
{:paths ["src"]}

$ cat src/com/example.clj
(ns com.example)

(defn hello []
  (println "hello there"))

$ bb hello
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  Could not find namespace: com.example.
Location: <expr>:24:1

----- Context ------------------------------------------------------------------
20:   (intern *ns* 'exec @(var babashka.tasks/exec)))
21:
22: nil
23:
24: (when-not (resolve 'com.example/hello) (require (quote com.example)))
    ^--- Could not find namespace: com.example.
25: (def hello (binding [
26:   babashka.tasks/*task* '{:name hello, :task com.example/hello}]
27:   nil
28: (apply com.example/hello *command-line-args*))) hello

$ bb --force hello
hello there
```

I'm on `v1.0.165`, linux x64. A few Biff users have also ran into this. Expected behavior would be to compute the classpath when needed without the use of `--force`, correct? I wonder if the `local/deps` thing has something to do with it.

**Comment by borkdude** [comment]
This should be improved with the newest bb (which in turn uses a newer version of deps.clj which in turn has a port of an improvement in the clojure CLI for caching).

**Comment by borkdude** [comment]
Oh no, sorry, this is a different caching problem.

When using `local/deps` it's recommended to choose a unique name for your project, as the classpath is cached via a hash on the library coordinates. When you re-use this name in different project, you will get caching problems.

I improved the documentation here: https://book.babashka.org/#_paths_and_deps

**Comment by jacobobryant** [comment]
Ah, thank you for the clarification! That does indeed fix it. I should have thought of that.
