### ISSUE TITLE
Add java.util.jar.Attributes to classes

### ISSUE THREAD

**Issue by jeroenvandijk** [babashka/babashka#1463]
**Is your feature request related to a problem? Please describe.**

I'm trying to the get `Main-Class` attribute from a Jar file, specifically for this issue in `bbin` (https://github.com/babashka/bbin/pull/47) The class [java.util.jar.Attributes](https://docs.oracle.com/javase/7/docs/api/java/util/jar/Attributes.html) and specifically the method [java.util.jar.Attributes/getValue](https://docs.oracle.com/javase/7/docs/api/java/util/jar/Attributes.html#getValue(java.util.jar.Attributes.Name)) seems to [be missing 
 in the classes list](https://github.com/babashka/babashka/blob/master/src/babashka/impl/classes.clj#L413-L419)

**Describe the solution you'd like**
Adding the class to the list

**Describe alternatives you've considered**
The workaround is to iterate over the attributes and parse the key of the attributes for "Main-Class", see [the code here](https://github.com/babashka/bbin/pull/47/files#diff-2d57bc7b8c0b8798677c8c26601ff6d86f77d259acca16036d8a9e7be32064eaR302)

**Additional context**
https://github.com/babashka/bbin/pull/47

Some code to see this problem in action
```
bb version
babashka v1.0.164

bb -e '(let [clojure-jar-path (str (System/getenv "HOME") "/.m2/repository/org/clojure/clojure/1.11.0/clojure-1.11.0.jar")
      jar-file (clojure.java.io/file clojure-jar-path)]
  (with-open [jar (java.util.jar.JarFile. jar-file)]
    (-> (java.net.URL. "jar" nil (str "file:" (.getAbsolutePath jar-file) "!/META-INF/MANIFEST.MF"))
        (clojure.java.io/input-stream)
        (java.util.jar.Manifest.)
        (.getMainAttributes)
        (.getValue "Main-Class"))))'
----- Error --------------------------------------------------------------------
Type:     java.lang.IllegalArgumentException
Message:  No matching method getValue found taking 1 args for class java.util.jar.Attributes
Location: <expr>:1:1

----- Context ------------------------------------------------------------------
1: (let [clojure-jar-path (str (System/getenv "HOME") "/.m2/repository/org/clojure/clojure/1.11.0/clojure-1.11.0.jar")
   ^--- No matching method getValue found taking 1 args for class java.util.jar.Attributes
2:       jar-file (clojure.java.io/file clojure-jar-path)]
3:   (with-open [jar (java.util.jar.JarFile. jar-file)]
4:     (-> (java.net.URL. "jar" nil (str "file:" (.getAbsolutePath jar-file) "!/META-INF/MANIFEST.MF"))
5:         (clojure.java.io/input-stream)
6:         (java.util.jar.Manifest.)
```

**Comment by borkdude** [comment]
PR welcome
