### ISSUE TITLE
Printing results should be opt-in

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#1467]
So far, babashka has printed results from scripts. This was kind of a mistake that slipped in and never was corrected.
I think we should only print for `-e`. The old behavior could be restored with an explicit `--prn` flag.

**Comment by rogererens** [comment]
When a script includes a shebang, invoking the script with its filename only and the `--prn` flag, that does not restore the old behavior. Is that to be expected?

**Comment by borkdude** [comment]
Provide me a full repro and I will be able to tell you more.

**Comment by rogererens** [comment]
Do you mean this?
```
roger@T420:~/prj> bb
Babashka v1.3.176 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> ^D
roger@T420:~/prj> ll hello
-rwxr-xr-x 1 roger roger 61 mrt 18 21:30 hello
roger@T420:~/prj> cat hello
#!/usr/bin/env bb

(str "Hello, from " *ns* ", inner world")
roger@T420:~/prj> ./hello
roger@T420:~/prj> ./hello --prn
roger@T420:~/prj> 
```

**Comment by borkdude** [comment]
With a shebang like that, babashka is called like:

```
bb hello --prn
```

Not like:

```
bb --prn hello
```

so that doesn't work, since `--prn` is a global bb argument, not an argument for your script.

This works though:

``` clojure
#!/usr/bin/env -S bb --prn

(str "Hello, from " *ns* ", inner world")
```

But I think it's best to not do this and use explicit printing in your script. `--prn` is more for debugging situations.

**Comment by rogererens** [comment]
Thanks for the clarification! Hopefully this will be soon in Daniel's Babashka Babooka, too.

**Comment by borkdude** [comment]
cc @norecursive ^
