### ISSUE TITLE
Make relative paths in deps of bb.edn resolve relative to the bb.edn

### ISSUE THREAD

**Issue by lispyclouds** [babashka/babashka#1473]
**Is your feature request related to a problem? Please describe.**
Currently, due to its nature of implementation in [deps.clj](https://github.com/borkdude/deps.clj) and its use in bb, if relative paths via `:local/root` are used in the `:deps` of bb.edn, they are resolved relative to the pwd of the invocation and not the bb.edn.

**Describe the solution you'd like**
To make the expectation of all the paths in bb.edn resolve relative to it consistent the resolution of these paths should be changed as well.

**Describe alternatives you've considered**
None.

**Additional context**
Some points to consider:
- Since this is shelling out to the usual deps resolver, how does the classpath caching get affected by this change? Would it pollute the pwd now?

**Comment by borkdude** [comment]
The only change necessary to fix this is to use `(:bb-deps-root ...)` and bind the `deps.clj` `*dir*` variable to it (only if it's set, `with-bindings` allows you to do that conditionally.
