### ISSUE TITLE
Expose PersistentList/create

### ISSUE THREAD

**Issue by NoahTheDuke** [babashka/babashka#1498]
**Is your feature request related to a problem? Please describe.**
I want to use the method `create` on `clojure.lang.PersistentList` ([this one](https://github.com/clojure/clojure/blob/527b330045ef35b47a968d80ed3dc4999cfa2623/src/jvm/clojure/lang/PersistentList.java#L86)):

```
(defn ->list
  [coll]
  (PersistentList/create coll))
```

**Describe the solution you'd like**
Expose it in [this file](https://github.com/babashka/babashka/blob/711bb40480274c277b2c0364f9e86c355131f9ea/src/babashka/impl/classes.clj#L120).

**Describe alternatives you've considered**
I can use `(apply list coll)` but that's ~slower~ longer to write than calling the method directly. 

**Additional context**
Here's the output from Babashka.
```
Type:     java.lang.IllegalArgumentException
Message:  No matching method create found taking 1 args
Location: /home/noah/personal/spat/src/noahtheduke/spat.clj:39:1
```

**Comment by borkdude** [comment]
Interesting. Is the use case to turn an arbitrary sequential into a concrete list? This is pretty unusual in Clojure, given that we have `seq` right?

**Comment by borkdude** [comment]
Imo working against concrete lists, e.g. by using `list?` is almost always a code smell and you should use `seq?` etc instead.

**Comment by NoahTheDuke** [comment]
Well, it's meaningful to work against concrete lists when creating and processing code-as-data. It's annoying that syntax quote and `cons` and `list*` return seqs. It means I can't just call `list?`, I have to call `(and (not (vector? coll)) (sequential? coll))`.

It's okay if you don't want to add this, lol. After checking with criterium, it's not actually any slower to use `(apply list coll)`, so maybe I'll just stick with that in my function.

**Comment by borkdude** [comment]
`seq?` never returns true for vectors. I wasn't talking about `seqable?`. Especially when working with code you should not use `list?`, since like you said, syntax quote can return non-concrete lists: 

```
user=> (list? `(do ~@[1 2 3]))
false
user=> (seq? `(do ~@[1 2 3]))
true
```

**Comment by NoahTheDuke** [comment]
Oh! That's super interesting. Seems I was confused, yeah. Clojure has too many of these `seq*` functions lol.

**Comment by borkdude** [comment]
I'll re-open once there is a good use case to use `PersistentList/create`. Imo it should only be used in the Clojure reader to read lists in case of e.g. this: `'(1 2 3)` but there is no good use case for it outside of _reading_.

**Comment by borkdude** [comment]
Note that even:

```
user=> (list? `(+ 1 2 3))
false
```

**Comment by NoahTheDuke** [comment]
Haha yeah that bothers me a lot. Feels like Clojure should have committed to no concrete lists, just vectors or seqs.
