### ISSUE TITLE
Namespaced constructor fails after upgrading Babashka to 1.0.169 

### ISSUE THREAD

**Issue by alysbrooks** [babashka/babashka#1502]
In Lambda Island URI's test suite, recent versions of Babashka cause it to fail. Here's the error I get:

```
----- Context ------------------------------------------------------------------
12: (deftest parsing
13:   (testing "happy path"
14:     (are [x y] (= y (uri/parse x))
15:       "http://user:password@example.com:8080/path?query=value#fragment"
16:       (uri/URI. "http" "user" "password" "example.com" "8080" "/path" "query=value" "fragment")
          ^--- Unable to resolve classname: uri/URI
17: 
18:       "/happy/path"
19:       (uri/URI. nil nil nil nil nil "/happy/path" nil nil)
20: 
21:       "relative/path"
```

It appears to be due to trying to call this constructor with the `uri/` prefix.  Here are the imports for context:

```clojure
(ns lambdaisland.uri-test
  (:require ,,,
                [lambdaisland.uri :as uri]           ,,,)
  #?(:clj (:import lambdaisland.uri.URI)))

```

I also created a small issue reproduction [here](https://github.com/alysbrooks/Babashka-Constructor-Regression-Demonstration).

**Comment by borkdude** [comment]
Thanks, I'll take a look tomorrow

**Comment by borkdude** [comment]
Btw you can work around this by using the `uri/->Uri` var instead of the constructor.

**Comment by borkdude** [comment]
It's pretty weird how an `import` makes the `uri/URI.` notation work. I wouldn't be too surprised if this was undefined behavior in clojure. If you imported the class, there is no need to add the prefix to `uri/URI.`.

```
user=> (defrecord Rec [])
user.Rec
user=> (ns foo)
nil
foo=> (alias 'u 'user)
nil
foo=> (u/Rec.)
Syntax error (IllegalArgumentException) compiling new at (REPL:1:1).
Unable to resolve classname: Rec
foo=> (user/Rec.)
Syntax error (IllegalArgumentException) compiling new at (REPL:1:1).
Unable to resolve classname: Rec
foo=> (import 'user.Rec)
user.Rec
foo=> (user/Rec.)
#user.Rec{}
foo=> (Rec.) ;; without prefix
#user.Rec{}
foo=> user/Rec
Syntax error compiling at (REPL:0:0).
No such var: user/Rec
```

Can you explain what is the reasoning for adding the prefix? Usually qualified symbols with a `/` in them only refer to vars in namespaces.

**Comment by borkdude** [comment]
Got confirmation from Alex Miller that this is undefined behavior:

<img width="1346" alt="Screenshot 2023-02-25 at 14 03 46" src="https://user-images.githubusercontent.com/284934/221358424-4b80a750-3624-4d5a-ba85-5ec752179c50.png">

I think you should update your test by either removing the alias (just write `(Uri. ..)` or going through the record constructor var: `(uri/->Uri ..)`.
