### ISSUE TITLE
Support unix domain sockets

### ISSUE THREAD

**Issue by nivekuil** [babashka/babashka#1511]
**Is your feature request related to a problem? Please describe.**
Right now I need to have a custom babashka image with socat installed for https://github.com/nivekuil/zincati-consul, this would fix that

**Describe the solution you'd like**
Support unix domain sockets added in java 16

**Additional context**
https://www.baeldung.com/java-unix-domain-socket
https://app.slack.com/client/T03RZGPFR/CLX41ASCS/thread/CLX41ASCS-1668550310.958499

**Comment by borkdude** [comment]
Can you include an example expression that we can use in a test?

**Comment by nivekuil** [comment]
```clojure
  (import java.net.UnixDomainSocketAddress
          java.net.StandardProtocolFamily
          [java.nio.channels ServerSocketChannel SocketChannel])

  (def sockaddr (UnixDomainSocketAddress/of "/tmp/sock"))

  ;; server
  (doto (ServerSocketChannel/open StandardProtocolFamily/UNIX)
    (.bind sockaddr)
    (.accept))

  ;; client
  (doto (SocketChannel/open StandardProtocolFamily/UNIX)
    (.connect sockaddr))
```

**Comment by borkdude** [comment]
@nivekuil Forgive me my ignorance, but I tried to run the above program. I think the first one might be stuck waiting for a client, so I wrapped it in a future. Then the second expression resulted in `Connection refused`. Does the above program work as is on your machine?

**Comment by borkdude** [comment]
I tried something like this:

``` clojure
(import java.net.UnixDomainSocketAddress
        java.net.StandardProtocolFamily
        [java.nio.channels ServerSocketChannel SocketChannel])

(require '[clojure.java.io :as io])

(def sockaddr (UnixDomainSocketAddress/of
               (-> (doto (io/file "/tmp/sock")
                     (.deleteOnExit))
                   str)))

;; server
(def server
  (future
    (let [ch (ServerSocketChannel/open StandardProtocolFamily/UNIX)]
      (.bind ch sockaddr)
      (.accept ch)
      #_#_(prn :yolo)
      (.close ch))))

  ;; client
(let [ch (SocketChannel/open StandardProtocolFamily/UNIX)
      ch (loop [retry 0]
           (let [v (try (.connect ch sockaddr)
                        (catch Exception e e))]
             (if (instance? Exception v)
               (if (< retry 10)
                 (do (Thread/sleep 10)
                     (recur (inc retry)))
                 (throw v))
               v)))]
  (prn :ch ch)
  (.close ch)
  (prn :success))

@server

(when-not (System/getProperty "babashka.version")
  (shutdown-agents))
```

but it didn't quite work yet.

**Comment by nivekuil** [comment]
is `/tmp/sock` still around somehow? I'm testing this in a docker container, `docker.io/nivekuil/clojure-with-node:latest` and it just returns `:success` for me...

**Comment by borkdude** [comment]
It was around but even when deleting it I get the same exception.

```
(do
  (import java.net.UnixDomainSocketAddress
          java.net.StandardProtocolFamily
          [java.nio.channels ServerSocketChannel SocketChannel])

  (require '[clojure.java.io :as io])

  (def sockaddr (UnixDomainSocketAddress/of
                 (-> (doto (io/file "/tmp/sock")
                       (.deleteOnExit))
                     str)))

  (def serv (future (doto (ServerSocketChannel/open StandardProtocolFamily/UNIX)
                      (.bind sockaddr)
                      (.accept))))

  (let [ch (SocketChannel/open StandardProtocolFamily/UNIX)]
    (loop [retry 0]
      (let [v (try (.connect ch sockaddr)
                   (catch Exception e e))]
        (if (instance? Exception v)
          (if (< retry 10)
            (do (Thread/sleep 10)
                (recur (inc retry)))
            (throw v))
          v)))
    (.close ch))
  :success)
```

**Comment by nivekuil** [comment]
There seems to be something special about the name `/tmp/sock/`... I can also get that error if the socket is bound under a directory without write permissions. Could not tell you why, according to google it's a common example path for unix sockets, but it should work if you replace it with any other name.
```clojure
(do
    (import java.net.UnixDomainSocketAddress
            java.net.StandardProtocolFamily
            [java.nio.channels ServerSocketChannel SocketChannel])

    (def sockaddr (UnixDomainSocketAddress/of "/tmp/sock1"))

    (def serv (future (doto (ServerSocketChannel/open StandardProtocolFamily/UNIX)
                        (.bind sockaddr)
                        (.accept))))

    (let [ch (SocketChannel/open StandardProtocolFamily/UNIX)]
      (loop [retry 0]
        (let [v (try (.connect ch sockaddr)
                     (catch Exception e e))]
          (if (instance? Exception v)
            (if (< retry 10)
              (do (Thread/sleep 10)
                  (recur (inc retry)))
              (throw v))
            v)))
      (.close ch))
    :success)
```

**Comment by borkdude** [comment]
Doesn't work, same error:

``` clojure
(def sockaddr (UnixDomainSocketAddress/of
                 (-> (doto (fs/file (fs/temp-dir) "sock1" #_(str gensym))
                       (.deleteOnExit))
                     str)))
```

**Comment by nivekuil** [comment]
very mysterious.. I did manage to reproduce your error once with `/tmp/sock`, but trying it again the code in https://github.com/babashka/babashka/issues/1511#issuecomment-1462211437 now just works. Other paths I've tried have always worked.

Are you saying that you've never gotten these blocks of code to run without exception? There should also be unnamed sockets that can `accept` without `bind` but I'm not sure the Java API supports that.

**Comment by borkdude** [comment]
I'll just go with the top level sleep. If that doesn't turn out to be flaky over the long term, I'll make peace with it :)

**Comment by borkdude** [comment]
Windows doesn't work yet.

<img width="844" alt="Screenshot 2023-03-09 at 21 35 47" src="https://user-images.githubusercontent.com/284934/224150302-3da749c3-b0ae-43fe-9f1d-e911e72c383c.png">

https://ci.appveyor.com/project/borkdude/babashka/builds/46459254

yet I can't repro it with pure Java and native-image yet:

https://github.com/borkdude/graalvm-windows-unix-protocol-repro

**Comment by borkdude** [comment]
Turned out to be a VS2017 image vs VS2019 image problem
