### ISSUE TITLE
Support for clojure.lang.IHashEq

### ISSUE THREAD

**Issue by beho** [babashka/babashka#1520]
Hi,

I'm trying to run a tool that uses [instaparse](https://github.com/Engelberg/instaparse) using `bb` but it fails with following error:

```
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  Protocol not found: clojure.lang.IHashEq
Data:     {:type :sci/error, :line 91, :column 3, :file "instaparse/auto_flatten_seq.clj"}
Location: instaparse/auto_flatten_seq.clj:87:1
Phase:    macroexpand

----- Context ------------------------------------------------------------------
83:             (when-let [next-index (advance v index)]
84:               (flat-seq v next-index))))))
85:
86:
87: (deftype AutoFlattenSeq [^PersistentVector v ^int premix-hashcode ^int hashcode
    ^--- Protocol not found: clojure.lang.IHashEq
88:                          ^int cnt ^boolean dirty
89:                          ^:unsynchronized-mutable ^clojure.lang.ISeq cached-seq]
90:   Object
91:   (toString [self] (.toString (seq self)))
92:   (hashCode [self] hashcode)

----- Stack trace --------------------------------------------------------------
clojure.core/deftype            - <built-in>
instaparse.auto-flatten-seq     - instaparse/auto_flatten_seq.clj:87:1
instaparse.auto-flatten-seq     - instaparse/auto_flatten_seq.clj:87:1
instaparse.gll                  - instaparse/gll.clj:7:3
instaparse.core                 - instaparse/core.clj:5:3
...
user                            - <expr>:1:10
```

[This is the line at instaparse 1.4.12](https://github.com/Engelberg/instaparse/blob/v1.4.12/src/instaparse/auto_flatten_seq.cljc#L99).

I suppose that this is caused by absence of `IHashEq` in `classes.clj`.

I would try to create a PR but I might need a bit of guidance:

- Is there a reason why it is missing or simply no one hit its absence before?
- I'll start with [Adding classes](https://github.com/babashka/babashka/blob/e2f2e9ae4eb95fbca48bacd5bc48f57259ee7aeb/doc/dev.md#adding-classes).
- Any other hints? :)

**Comment by borkdude** [comment]
For other reasons, adding that class doesn't fix this particular issue.
To use instaparse with bb, try: https://github.com/babashka/instaparse-bb

**Comment by beho** [comment]
That seems to work. Thank you very much!
