### ISSUE TITLE
Drop support for non-static linux aarch64 binary

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#1524]
Currently users seem to be using the (mostly) static linux aarch64.
We can drop the non-static build and just upload the static binary twice, once to the original non-static name, so down-stream users of that link aren't affected.

cc @lispyclouds

**Comment by lispyclouds** [comment]
should we even make the linux amd64 upload the static one too? this ones a proper static one and hopefully has no downsides? could simplify the pipeline orchestration code too if we are tackling both the linuxes.

**Comment by borkdude** [comment]
Perhaps, but I don't know if musl is going to have any downsizes. Let's start with aarch64 and keep the other option in the back of our minds for the long term. By default, the installer script will choose the static one.

**Comment by lispyclouds** [comment]
right, my thoughts were coming from the kinda pipeline orchestration code we have now and to upload the aarch64 linux artifact twice, need to refactor the code a bit and was thinking should we decouple the mac and linux bits.

**Comment by borkdude** [comment]
@lispyclouds I guess we could just not publish the non-static binary in the next release and then see if people will complain. If they will complain, I can manually upload the static binary under the non-static name and then we could change a script.

**Comment by lispyclouds** [comment]
Right, so we keep the CI script as it is now then? Since the release is manual?

**Comment by borkdude** [comment]
We just remove the non-static aarch64 build then I guess.

**Comment by lispyclouds** [comment]
fixing the docker script

**Comment by borkdude** [comment]
Thanks :)

**Comment by lispyclouds** [comment]
It needs a change here: https://github.com/babashka/babashka/blob/master/.circleci/script/docker.clj#L87 should i do on master?

**Comment by borkdude** [comment]
ok
