### ISSUE TITLE
Implement user land middleware

### ISSUE THREAD

**Issue by benjamin-asdf** [babashka/babashka#1529]
# User land middleware

The reason we would like to have this is because it is a step towards cider middleware (and beyond) implementations on bb. 

- Defined in bb user sources
- Additional `--middleware` arg to bb nrepl-server  
- Use middlware wrapper semantics, it gets wrappep by middleware->transducer internally.

I basically have the hard part working, loading a middleware in the sci context then passing that to the nrepl server as middleware. 
What  is left to do is adding the middleware arg to bb main, make examples and document.

# Current Questions 

- [X]  I am trying to `(sci/resolve sci-ctx middleware)` where middleware is a symbol on the classpath (added via bb.edn, :local/root, -> deps.edn)
but it doesn't resolve. 
(sci-ctx is the one we start early in the `exec`  function)

**Comment by borkdude** [comment]
@benjamin-asdf you should probably use `requiring-resolve` instead since the namespace wasn't loaded yet, you could do this with `(sci/eval-form sci-ctx (list 'requiring-resolve middleware))`

**Comment by benjamin-asdf** [comment]
![image](https://user-images.githubusercontent.com/38900087/230592118-60805a36-2fbc-41e4-b18d-aef1ebe97c7e.png)

**Comment by benjamin-asdf** [comment]
I gave up https://faster-than-light-memes.xyz/meta-the-meta.html - just using a jvm repl for development is good.

**Comment by borkdude** [comment]
OK, let's just give up on this for now and recommend the JVM REPL for advanced REPL features. This also keeps the bb binary more lean and we don't have to port any cider middleware stuff. I might roll back the existing middleware commits in bb.nrepl as well to clean up the work that was half done in there.

**Comment by borkdude** [comment]
I think a nice (very optional, vacation-project-ish, super low priorirty) challenge might be to run the original nrepl completely in babashka, instead of having nrepl as a built-in:

```
bb -Sdeps '{:deps {nrepl/nrepl {:mvn/version "1.0.0"}}}' -m nrepl.cmdline --interactive --color
```

:-)
