### ISSUE TITLE
Unable to reload `babashka.process/exec`

### ISSUE THREAD

**Issue by lread** [babashka/babashka#1557]
**version**
```
❯ bb --version
babashka v1.3.179
```

**platform**
Repro on Linux, but should apply to all.

**problem**
Babashka comes bundled with `babashka.processs` built in.
Sometimes a newer version of `babashka.process` becomes available.

For example, at the time of this writing, a newer version of `babashka.process` is available with a `:cmd` `opt` feature.

A user can opt to use the newer version via a ns reload.
This works great in general, but not for the `exec` function.

**repro**
Given a `bb.edn` that specifies the new version:
```
{:deps {babashka/process {:mvn/version "0.5.19"}}}
```

Here's a REPL session that shows the behaviour.
We'll start off using built-in babashka.process:
```Clojure
❯ rlwrap bb
Babashka v1.3.179 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (require '[babashka.process :as p])
nil
```
And now let's call a new feature that is not yet in bb (it will fail):
```Clojure
user=> (p/shell {:cmd ["ls" "-l"]})
java.lang.NullPointerException [at <repl>:2:1]
```
And we'll reload the ns to get the updated version specified in `bb.edn` and retry our command (it will work)
```Clojure
user=> (require '[babashka.process :as p] :reload)
nil
user=> (p/shell {:cmd ["ls" "-l"]})
total 4
-rw-rw-r-- 1 lee lee 51 May 13 12:39 bb.edn
{:proc #object[java.lang.ProcessImpl 0x6d1bac37 "Process[pid=66629, exitValue=0]"], :exit 0, :in #object[java.lang.ProcessBuilder$NullOutputStream 0x73925281 "java.lang.ProcessBuilder$NullOutputStream@73925281"], :out #object[java.lang.ProcessBuilder$NullInputStream 0x1affa17d "java.lang.ProcessBuilder$NullInputStream@1affa17d"], :err #object[java.lang.ProcessBuilder$NullInputStream 0x1affa17d "java.lang.ProcessBuilder$NullInputStream@1affa17d"], :prev nil, :cmd ["ls" "-l"]}
```

Now let's try a call to `exec` to show the issue:
```
user=> (p/exec "ls -l")
clojure.lang.ExceptionInfo: exec is not supported in non-GraalVM environments [at babashka/process.cljc:612:8]
```

**expected behavior**
`exec` should also work after ns reload.

**thoughts**
I am guessing that if bb exposed `org.graalvm.nativeimage.ProcessProperties/exec` this should work.

**next steps**
I'll experiment and follow up.

**Comment by borkdude** [comment]
right, making org.graalvm.nativeimage.ProcessProperties available in bb should solve that

Let's limit it to the "exec" method in the :custom map to save space
