### ISSUE TITLE
No aarch64.tar.gz in v1.3.180

### ISSUE THREAD

**Issue by qawel** [babashka/babashka#1567]
v1.3.180
AArch64

The installer script is trying to download a file which doesn't exist:
 https://github.com/babashka/babashka/releases/download/v1.3.180/babashka-1.3.180-linux-aarch64.tar.gz

**Repro:**
$ curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
$ chmod +x install
$ ./install

**Workaround:**

add `--static` or `--version 1.3.179`

**Comment by borkdude** [comment]
I think we should adapt the script to always download the static binary on linux aarch64.

**Comment by borkdude** [comment]
Should work now
