### ISSUE TITLE
Task runner: warn when task overrides built-in (with option to disable warning)

### ISSUE THREAD

**Issue by sutyrin** [babashka/babashka#1568]
**version**

babashka v1.3.179

**platform**

Linux pavelt 6.3.1-060301-generic #202304302031 SMP PREEMPT_DYNAMIC Mon May  1 00:41:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

**problem**

Task runner stops working correctly when one of the tasks is called `run`. This name looks very common when setting up a task for run some project locally.

Though, this seem to clash with `bb run` subcommand, so, maybe documentation should be updated or error is given (because such a setup makes it impossible to run any other tasks).

**repro**

`bb.edn`:
```
{:paths ["bb"]
 :deps {}
 :tasks
 {hello (shell "echo hello")
  run (shell "echo run")
  walk (shell "echo walk")
  }}
```

**expected behavior**

```
$ bb run hello
hello
$ bb run run
run
$ bb run walk
walk
```

**actual behavior**
```
$ bb run hello
run
$ bb run run
run
$ bb run walk
run
```

Removing `run` task repairs the issue:
```
$ bb run hello
hello
$ bb run run
No such task: run
$ bb run walk
walk
```

**Comment by borkdude** [comment]
This is expected behavior. Tasks always override built-in functions. Just don't call your task `run`.

**Comment by borkdude** [comment]
You can get around this with `bb --run ...`. 
I think it would be good if bb emitted a warning that you're overriding a built-in CLI function with the option to turn that off.

**Comment by sutyrin** [comment]
Seems legit, thanks! Though, these tasks are meant to be run quickly from console (in my current workflow), so `--run` is not best solution. 

Will work around with other names)
