### ISSUE TITLE
Add clojure.tools.reader/resolve-sym

### ISSUE THREAD

**Issue by jeroenvandijk** [babashka/babashka#1579]
**Is your feature request related to a problem? Please describe.**

I was trying to see how far I would get in porting [`polylith`](https://github.com/polyfy/polylith) to babashka. One missing part is `clojure.tools.reader/resolve-sym` used here which is not part of  the [Babashka namespace](https://github.com/babashka/babashka/blob/056254dc9da23e9088f171c53a6e0363b1215323/src/babashka/impl/clojure/tools/reader.clj#L56)

**Describe the solution you'd like**

Adding `clojure.tools.reader/resolve-sym` might get me closer to this experiment.

**Describe alternatives you've considered**

Adding resolve-symbol myself via: 

```clojure
(require 'clojure.tools.reader)
(in-ns 'clojure.tools.reader)

(defn resolve-symbol [sym]
  (intern (symbol (namespace sym)) (symbol (name sym))))
```

Which still gave me an error that it could not find the particular ns, but I assume this is a different issue

**Additional context**

[Slack discussion](https://clojurians.slack.com/archives/CLX41ASCS/p1687355757823539)

**Comment by borkdude** [comment]
This isn't what I meant with the `intern` suggestion. This is more like it:

```
(intern 'clojure.tools.reader 'resolve-symbol your-version-of-resolve-symbol)
```

**Comment by borkdude** [comment]
You can probably try to copy `resolve-symbol` from tools reader and use it in the above patch.

**Comment by jeroenvandijk** [comment]
After some guidance of @borkdude [this is the patch](https://github.com/jeroenvandijk/polylith/blob/master/projects/poly-bb/src/polylith_bb/core.clj#L8-L44)

**Comment by jeroenvandijk** [comment]
Thank you!
