### ISSUE TITLE
improving config file loading

### ISSUE THREAD

**Issue by pekeler** [babashka/babashka#1586]
I wish the --debug option printed some information about the loading of the config file.

And that there'd be an error or warning message if bb is invoked with a --config path that can't be loaded. Currently, `bb --config bad-path.edn` doesn't result in any error or warning.

Context: I'm trying to debug why my bb.edn is loaded on my dev machine but not in production.

**Comment by borkdude** [comment]
I'll consider this. Meanwhile you can for example make an intentional bug in your EDN file, e.g. `{:a 1 :a 2}` which will make the EDN reader crash.
