### ISSUE TITLE
`Thread/setDefaultUncaughtExceptionHandler` compiles but is ignored

### ISSUE THREAD

**Issue by rynkowsg** [babashka/babashka#1589]
**Is your feature request related to a problem? Please describe.**
An option to provide a custom DefaultUncaughtExceptionHandler for unhandled exceptions. Babashka compiles but ignores the provided DefaultUncaughtExceptionHandler. Most likely because Babashka handles the Exception so it never becomes Uncaught.

**Describe the solution you'd like**
When we call `Thread/setDefaultUncaughtExceptionHandler` multiple times, only the last one is valid.
One solution we could consider is to provide Babashka's implementation of `DefaultUncaughtExceptionHandler` on process start (before evaluating provided script) and if the user provides another one, the new one would replace the default one.

**Describe alternatives you've considered**
Until now, what I'm using to make possible catching the exception is placing try/catch in the main function so I can handle exceptions before they are handled by Babashka. Ideally, I would prefer to use `Thread/setDefaultUncaughtExceptionHandler` as it brings parity between Babashka and JVM.

**Additional context**

Initially reported on Clojurians [HERE](https://clojurians.slack.com/archives/CLX41ASCS/p1689002325262219).

Tested on Babashka 1.3.181.

Sample code:
```clojure
#!/usr/bin/env bb

(ns simulate-crash
  (:require
    [taoensso.timbre :as log]))

(defn handle-unhandled []
  (Thread/setDefaultUncaughtExceptionHandler
    (reify Thread$UncaughtExceptionHandler
      (uncaughtException [_ thread ex]
        ;; place where I can send info about unhandled somewhere, eg. to Slack, Sentry, etc
        (log/error ex "Uncaught exception on" (.getName thread))))))

(defn -main [& _args]
  (log/info :started)
  (throw (ex-info "Very nasty bug" {:data "value 1"}))
  (log/info :finished))

(when (= *file* (System/getProperty "babashka.file"))
  (handle-unhandled)
  (apply -main *command-line-args*))
```
In the above example the line:
```clojure
(log/error ex "Uncaught exception on" (.getName thread))
```
is never called.

**Comment by borkdude** [comment]
When you would execute this script with JVM Clojure, the uncaught exception handler would also not be triggered, since clojure's error handler logic does this. I guess maybe a global try/catch is the best you can do, like you would do it with normal Clojure?

**Comment by borkdude** [comment]
I'll close this until I get a reply from OP.
