### ISSUE TITLE
Babashka does not propagate error code when running a task that doesn't exist within another task

### ISSUE THREAD

**Issue by axvr** [babashka/babashka#1599]
**version**

babashka v1.3.182

**platform**

macOS

**problem**

When running a task that doesn't exist from another task, the error code is not propagated once Babashka exits.

**repro**

```clojure
;; bb.edn
{:tasks
 {foo {:task (run 'bar)}}}
```

```shell
$ bb run foo
No such task: bar
$ echo $?
0
```

**expected behavior**

Error code should be `1`, as it is when running `bb run bar` directly.

**Comment by borkdude** [comment]
Thanks
