### ISSUE TITLE
`Thread/sleep` only works with timeouts of type `long`

### ISSUE THREAD

**Issue by Cortys** [babashka/babashka#1619]
v1.3.184
Reproduced on Linux (Ubuntu 22.04 on WSL2) and Windows 11.

**problem**

Babashka seems to resolve static methods slightly differently than Clojure JVM.
In particular, when calling `(Thread/sleep ms)` the type of `ms` has to be `java.lang.Long`; when passing `ms` of type `java.lang.Integer`, the sleep method is not resolved properly:
```
java.lang.IllegalArgumentException: No matching method sleep found taking 1 args
```
In Clojure JVM (and also Java) the [`Thread.sleep`](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#sleep-long-) method can however be called with `int` arguments, which are then autocasted.

If I remember correctly, I think that this has worked in Babashka at some point in the past and then it broke in one of the following releases - I have not yet spent the time to track this down though.

**repro**

Using Babashka:
```clojure
(do (Thread/sleep 1000) (println "test"))
;; => (waits 1000ms) "test"

(do (Thread/sleep (int 1000)) (println "test"))
;; Throws: java.lang.IllegalArgumentException: No matching method sleep found taking 1 args
```

Using Clojure JVM, the second example behaves just like the first one.

**expected behavior**

No exception when arguments with castable types are given.
Maybe this issue is not specific to `Thread/sleep` but to how methods are resolved in general?

**Comment by borkdude** [comment]
methods are resolved through reflection. See `sci.impl.reflector` which is largely based on `clojure/lang/Reflector.java`. A similar thing happens in clj when using reflection:

```
 $ clj
Clojure 1.10.3
user=> (type (int 1))
java.lang.Integer
user=> (def x (int 1))
#'user/x
user=> (type x)
java.lang.Integer
user=> (Thread/sleep x)
Execution error (IllegalArgumentException) at user/eval5 (REPL:1).
No matching method sleep found taking 1 args
```

**Comment by borkdude** [comment]
Btw, note that `(long x)` does work.

**Comment by Cortys** [comment]
Interesting. Your example with the indirection through the `x` variable works for me when using JVM 17 but indeed throws when using JVM 20 (tested using Clojure 1.10.3 and Clojure 1.11.1). Not sure what's going on here.

As far as I can tell the method is correctly resolved in any case if a type hint is used:
```clj
(def x (int 1))
(Thread/sleep ^int x) ;; works on JVM 17 and 20
```

In Java, both `long` and `int` arguments are supported as well:
```java
int x = 1000;
Thread.sleep(x); // works on JVM 17 and 20
```

I also just checked that the example from my first post (`(Thread/sleep (int 1000))`) worked in Babashka [v1.1.173](https://github.com/babashka/babashka/releases/tag/v1.1.173) but no longer works since [v1.2.174](https://github.com/babashka/babashka/releases/tag/v1.2.174).

Of course, I agree that this issue is easy to circumvent in ones own code. The reason I initially noticed this bug was due to [this](https://github.com/brunoV/throttler/blob/master/src/throttler/core.clj#L37) line of code in the throttler library (which in turn calls `Thread/sleep` [here](https://github.com/babashka/babashka/blob/master/src/babashka/impl/clojure/core/async.clj#L75)), which I use in one of my BB scripts and which stopped working after an update of BB.

While the specific issue I encountered is easy to fix/circumvent (e.g., by forking throttler or, as a quick-and-dirty solution, by altering the var roots of the affected functions at runtime in userland), the change of behaviour introduced in v1.2.174 could maybe cause other unforeseen incompatibilities with other Clojure libraries that worked previously with Babashka.

If this issue turns out to be not easily fixable, maybe an alternative more specific but trivial fix could be to explicitly add a cast `(long ms)` in`babashka.impl.clojure.core.async/timeout` implementation.

**Comment by borkdude** [comment]
> maybe an alternative more specific but trivial fix could be to explicitly add a cast (long ms) inbabashka.impl.clojure.core.async/timeout

For sure, we can do this.

The other issue may not be as easily fixable. The Clojure compiler will emit a byte code operation to cast a java.lang.* boxed object to a primitive and will then invoke the method on the primitive, but since babashka is basically using clojure.lang.Reflector it works similarly when using reflection in Clojure.

**Comment by Cortys** [comment]
Ah ok, I see, that makes sense.

Just out of curiosity, do you have an idea, what might have caused the difference in behaviour from BB v1.1.173 to v.1.2.174? Maybe the [upgrade](https://github.com/babashka/babashka/commit/3ad043769c16162abf33c58ad7068fb8ebc6679f) from Java 11 to 19?

**Comment by borkdude** [comment]
Yes, that is definitely it.

**Comment by Cortys** [comment]
Thanks! 😄

**Comment by borkdude** [comment]
A better fix underway as part of issue https://github.com/babashka/babashka/issues/1513. Will be fixed in next release, everything will just work for Thread/sleep
