### ISSUE TITLE
Source releases miss submodule dependencies

### ISSUE THREAD

**Issue by DerGuteMoritz** [babashka/babashka#1627]
**version**

1.3.184

**platform**

x86_64 GNU/Linux

**problem**

The release source archives (both .zip and .tar.gz) are incomplete in that they don't contain the sources of dependencies which are pulled in via git submodules (e.g. `deps.clj` or `sci`). They simply end up as empty directories. Thus, these archives are insufficient for building babashka from source.

**repro**

```
$ curl -sL https://github.com/babashka/babashka/archive/refs/tags/v1.3.184.tar.gz | tar zx
$ cd babashka-1.3.184
$ script/uberjar     
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-nixos)
OpenJDK 64-Bit Server VM (build 19.0.2+7-nixos, mixed mode, sharing)
Execution error (FileNotFoundException) at babashka.impl.common/eval187$loading (common.clj:1).
Could not locate sci/ctx_store__init.class, sci/ctx_store.clj or sci/ctx_store.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.

Full report at:
/tmp/clojure-8295359212037518323.edn
Error encountered performing task 'do' with profile(s): 'base,system,user,provided,dev,xml,yaml,csv,transit,httpkit-client,httpkit-server,core-match,hiccup,test-check,selmer,logging,priority-map,reflection'
Suppressed exit

```

**expected behavior**

It should be possible to build babashka from a source archive.

**Comment by borkdude** [comment]
I don't determine how these archives are made, they are added automatically by github. Just use a recursive git clone I'd say.

**Comment by DerGuteMoritz** [comment]
Ah okay, I thought this was accomplished by some custom GitHub action or so. Anyway, for posterity: I was able to work around it by fetching and unzipping the `*-standalone.jar` instead (I needed the `DEPS_CLJ_RELEASED_VERSION` file from `deps.clj` which is included in that jar, too). That means I gotta download 20+ MB instead of ~2 MB to get this info but oh well :shrug: :smile:
