### ISSUE TITLE
Var `*file*` should work like `__FILE__` in C

### ISSUE THREAD

**Issue by KDr2** [babashka/babashka#1631]
**version**
Babashka v1.3.184

**platform**
Linux 5.15.0-70-generic Ubuntu SMP

**problem**
The variable `*file*` has an improper value in some situations.

**repro**
bb.edn
```
{:paths ["."] ;; classpath
 :deps {}
 :tasks {:requires ([klib])
         k0 (prn *file*)
         k1 (klib/show)
        }
 }
```
klib.clj:
```
(ns klib
  (:require [babashka.fs :as fs]))

(def x)
(require '[clojure.java.io :as io])
(def script-dir (.getParentFile (io/file (:file (meta #'x)))))

(defn show []
  (println script-dir)
  (println *file*))
```

Run with `bb -f`:
```
$ bb -f bb.edn k0
"/path/to/bb.edn" #### it is right

$ bb -f bb.edn k1
#object[java.io.File 0x12a73132 /path/to] #### it is right
/path/to/bb.edn #### Wrong, it should be /path/to/klib.clj
```
Run with `bb --config`:
```
$ bb --config bb.edn k0
"<expr>" #### wrong
$ bb --config bb.edn k1
#object[java.io.File 0x4b452a63 /path/to] # right
<expr> #### wrong
```

**expected behavior**
Var `*file*` should always have the value of the file where it is written, like `__FILE__` in C or `__file__` in Python.

**see also**
- #179
- https://github.com/babashka/babashka/commit/2eecdea571256037f4590cd981d4051de25f8d7c

**Comment by borkdude** [comment]
`*file*` works the same as in Clojure JVM.

If you want to know the current file in a function, do this:

```
(def current-file *file*)
(defn foo []
  current-file))
```

The var `*file*` is bound the the file that is being analyzed. When the function executes, the binding has already gone. 

Hope it helps.
