### ISSUE TITLE
`str/join` doesn't work in `bb.edn`

### ISSUE THREAD

**Issue by dancek** [babashka/babashka#1644]
**version** 1.3.186
**platform** linux x86-64 (AUR: [babashka-bin](https://aur.archlinux.org/packages/babashka-bin))
**problem**

The alias `str` for `clojure.string` doesn't work in a `bb.edn` task. The error is:
> Could not resolve symbol: str/join

**repro**

Create this `bb.edn`, then run `bb fail`:
```
{:tasks {fail (println (str/join " " ["this" "fails"]))}}
```

**expected behavior**

The task should print `this fails`.

**Comment by dancek** [comment]
https://book.babashka.org/#built-in-namespaces this is the relevant documentation. Also, `bb '(str/join " " [1 2 3])'` does work.

**Comment by borkdude** [comment]
Alias are not intended to work in `bb.edn`, all should be explicit there
In the `user` namespace the aliases are pre-defined, but the tasks do not execute in the user namespace.
