### ISSUE TITLE
Support for clojure.lang.LongRange

### ISSUE THREAD

**Issue by paintparty** [babashka/babashka#1645]
Hi!

I’m working on a cljc dev tooling project, and was curious to see if it would work as-is with babaskha.
Everything seems to be fine, except that I’m getting an error related to `clojure.lang.LongRange`.

Executing the (contrived) bb script below will throw an error with the message
`Could not resolve symbol: clojure.lang.LongRange`:
```Clojure
(def clj-coll-types
  {clojure.lang.PersistentVector   :vector
   clojure.lang.PersistentArrayMap :map
   clojure.lang.PersistentHashMap  :map
   clojure.lang.PersistentHashSet  :set
   clojure.lang.LazySeq            :seq
   clojure.lang.Range              :seq
   clojure.lang.LongRange          :seq
   clojure.lang.PersistentList     :list})

(println (-> (range 10) type clj-coll-types))
```
Wondering if the fix is just a matter of adding `clojure.lang.LongRange` to the `:instance-checks` vector in  `babashka.impl.classes/classes` ?

**Comment by borkdude** [comment]
Yep, that would be it, PR welcome

**Comment by paintparty** [comment]
Would this addition to the `:instance-checks` require adding a unit test, as mentioned in the [Adding classes](https://github.com/babashka/babashka/blob/master/doc/dev.md#adding-classes) section of the dev.md doc? If so, where should it go? Asking because I can't seem to find unit tests for some of the other things in `:instance-checks`.

**Comment by borkdude** [comment]
PR still welcome, or no longer needed?

**Comment by paintparty** [comment]
Thank you for the reminder, just created a PR.
