### ISSUE TITLE
cmdline args are ignored under certain conditions

### ISSUE THREAD

**Issue by kwj** [babashka/babashka#1646]
Hello,

I might have found a bug about command-line parsing when using the `-f/--file` global option. If the first argument of `cmdline args` exists as a file, Babashka looks like to ignore the entire `cmdline args`.

Tested with v1.3.186

```console
$ ls
test.clj
$ cat test.clj
(println *command-line-args*)
$ bb test.clj A
(A)
$ bb -f test.clj A
(A)
$ touch A
$ ls
A  test.clj
$ bb test.clj A
(A)
$ bb -f test.clj A
nil
$ bb -f test.clj A B C
nil
$ bb -f test.clj C B A
(C B A)
$ bb --version
babashka v1.3.186
```

I hope this report is helpful.

**Comment by kwj** [comment]
Thanks for the workaround.

**Comment by borkdude** [comment]
Unfortunately the workaround didn't work either.
You can install the master version with:

```
bash <(curl https://raw.githubusercontent.com/babashka/babashka/master/install) --dev-build --dir /tmp
```

once CI finishes.
