### ISSUE TITLE
Unable to resolve classname: java.time.temporal.WeekFields

### ISSUE THREAD

**Issue by luontola** [babashka/babashka#1653]
**version**

babashka v1.3.186

**platform**

macOS

**problem**

I'm unable to import the `java.time.temporal.WeekFields` class. I need that class for calculating week numbers.

**repro**

```
user=> (import java.time.temporal.WeekFields)
java.lang.Exception: Unable to resolve classname: java.time.temporal.WeekFields [at <repl>:1:1]
```

**expected behavior**

Being able to use all the classes in the `java.time.temporal` package.

Example usage:

```clj
(ns example
  (:import (java.time ZonedDateTime)
           (java.time.temporal WeekFields)))

(prn (-> (ZonedDateTime/now)
         (.get (.weekOfYear WeekFields/ISO))))
```

**Comment by borkdude** [comment]
I think you can do it without this class, as a workaround: https://stackoverflow.com/a/40495319/6264

**Comment by luontola** [comment]
Thanks. I was able to use the workaround. Extra thanks for the fastest service on planet. 😊
