### ISSUE TITLE
#{a b} set initialization doesn't throw if there are duplicates (in clj it does)

### ISSUE THREAD

**Issue by brdloush** [babashka/babashka#1655]
**version**
 1.3.186

**platform**
 ubuntu linux 22.04, intel cpu

**problem**
Watching a part of a recent youtube video [50 clojure.core functions in 50 minutes](https://www.youtube.com/watch?v=4mDX4pqAVm0&t=1m10s) (approx. the part at 1m10s), it shows that if you declare duplicates such as `#{1 2 3 1}`, the literal expression fails. This is true for both clojure and babashka:

```bash
➜  ~ clj -e '#{1 1}'
WARNING: Implicit use of clojure.main with options is deprecated, use -M
Execution error (IllegalArgumentException) at clojure.main/main (main.java:40).
Duplicate key: 1

Full report at:
/tmp/clojure-13380372891003630970.edn

➜  ~ bb -e '#{1 1}'
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  Set literal contains duplicate key: 1
Data:     {:type :edamame/error, :line 1, :column 2}
Location: <expr>:1:2
Phase:    parse

----- Context ------------------------------------------------------------------
1: #{1 1}
    ^--- Set literal contains duplicate key: 1

----- Stack trace --------------------------------------------------------------
edamame.impl.parser/throw-reader   - <built-in>
edamame.impl.parser/throw-dup-keys - <built-in>
edamame.impl.parser/parse-set      - <built-in>
edamame.impl.parser/parse-sharp    - <built-in>
edamame.impl.parser/dispatch       - <built-in>
edamame.impl.parser/parse-next     - <built-in>
edamame.core/parse-next            - <built-in>
```

However, when you change the code to a bit more dynamic way using `let`-defined symbols, suddenly babashka silenlty accepts duplicities, while clojure still throws:
```bash
➜  ~ clj -e '(let [a 1, b 1] #{a b})'
WARNING: Implicit use of clojure.main with options is deprecated, use -M
Execution error (IllegalArgumentException) at user/eval136 (REPL:1).
Duplicate key: 1

Full report at:
/tmp/clojure-765538857763729018.edn

➜  ~ bb -e '(let [a 1, b 1] #{a b})'
#{1}
```

**expected behavior**
I'm not sure, what's the correct behavior in this specific case, really. But it would probably make sense to align the behavior with what regular clojure is doing. Also if jvm clojure behaves the same (throws) no matter if you use actual values or symbols, it feels safer to have this aligned in babashka as well.

**Comment by borkdude** [comment]
ClojureScript also accepts `(let [a 1, b 1] #{a b})`. I would consider this undefined behavior or an incidental implementation detail.

**Comment by borkdude** [comment]
Ah wait:

```
user=> (defn foo [a b] #{a b})
#'user/foo
user=> (foo 1 1)
Execution error (IllegalArgumentException) at user/foo (REPL:1).
Duplicate key: 1
```

**Comment by borkdude** [comment]
Since CLJS accepts it and I haven't heard anyone complain about that, I think it's better to just leave it since then the SCI code can remain the same for both implementations.
