### ISSUE TITLE
No dispatch macro for: ?

### ISSUE THREAD

**Issue by arichiardi** [babashka/babashka#1664]
`1.3.186`  on linux

We get an exception when running `bb uberjar`

`java.lang.RuntimeException, :message "No dispatch macro for: ?"`

```
.m2/repository/org/babashka/json/0.1.1/json-0.1.1.jar
.m2/repository/org/clojure/data.xml/0.2.0-alpha8/data.xml-0.2.0-alpha8.jar
{:warning "clashing jar item", :path "data_readers.cljc", :strategy :merge-edn}
{:error "unable to copy file", :name "data_readers.cljc", :exception java.lang.RuntimeException, :message "No dispatch macro for: ?"}
.m2/repository/org/clojure/data.zip/1.0.0/data.zip-1.0.0.jar
```

Apologies, don't really have a repro one yet.

I suspect it is related to [this `tool.build` solved issue](https://ask.clojure.org/index.php/12733/tools-build-datareaders-should-support-reader-conditionals) so my solution would be to move to the clj tooling. 

I am open to any step you want me to run for debugging!

**Comment by borkdude** [comment]
Yeah, eh, a repro would be great :)

**Comment by borkdude** [comment]
I think I can see what goes wrong. Babashka uses a (very old) uberjar implementation which was known as depstar. I can swap that out for the tools build implementation I guess. Indeed it tries to merge data_readers.clj(c) by reading it as EDN, but doesn't support reader conditionals. I'm going to fix that.

**Comment by borkdude** [comment]
Actually, I pushed a commit to master now which I believe should fix it.
You can test it with:

```
bash <(curl https://raw.githubusercontent.com/babashka/babashka/master/install) --dev-build --dir /tmp
```

**Comment by arichiardi** [comment]
Oh cool will try for sure!

**Comment by borkdude** [comment]
Ready for testing

**Comment by borkdude** [comment]
Guess we can close then, I'll update the changelogs later

**Comment by arichiardi** [comment]
Sounds good, will monitor when this gets released
