### ISSUE TITLE
metadata added by read-string (as compared to clj implementation).

### ISSUE THREAD

**Issue by skat-kurt** [babashka/babashka#1665]
**version**
Babashka 1.3.186

**platform**
Arch Linux (6.7.3-arch1-2)

**problem**
`read-string` on edn and then printing it back with \*print-meta\* bound to true gives different results between babashka and clojure.

**repro**

The following file is on disk at PATH.

``` clojure
{:name
 test

 :description
 "Testing read-string from bb"

 :details
 {:submap {:first  [some values]
           :second [(comp odd?)]}}}
```

Now execute the following sequence of expressions.

``` clojure
(def read-edn (read-string (slurp PATH)))

(binding [*print-meta* true]
    (prn read-edn))
```

**expected behavior**

I would execpt the output to be identical with the output that standard clojure prints. The babashka version is almost the same, but 1 expression (the list with symbols `comp`and `odd?` got tagged with metadata (`^{:line 9, :column 21}`).

The actual edn file I want to read has some metadata tagging in it that I want to keep when writing a new file, but I don't want extra metadata from the read process. For now I have fixed this by postwalking the datastructure from `read-line`.

eg.

``` clojure
(require '[clojure.walk :as walk])

(def read-edn (walk/postwalk
                 (fn [x]
                   (if (meta x)
                     (vary-meta x dissoc :line :column)
                     x))
                 (read-string (slurp PATH))))
```

**Comment by borkdude** [comment]
@skat-kurt It's not recommended to use `read-string` for reading EDN files. This is what we have `clojure.edn/read-string` for. `read-string` is for reading code.

**Comment by borkdude** [comment]
Nonetheless, I'll try to align bb's behavior to clj's.

**Comment by skat-kurt** [comment]
I'll have to stick with my original work-around for now. The original file I want to read contains a regex, which `edn/readstring` doesn't like

`(edn/read-string "#\"test\"")` 

Results in the 

java.lang.RuntimeException: No dispatch macro for: "

exception, mentioned in another issue as well. That behavior is identical with standard clojure though.

**Comment by skat-kurt** [comment]
You are right. A pity that the clojure.edn namespace isn't symetric. I mean, there is no `clojure.edn/write-string` function that could throw when serializing data to edn that cannot be expressed in it. I use `pr-str` instead, which happily writes regex etc.

Some background. The "edn" files form the basis to auto-generate leiningen compatible project.clj files and some of them need :userjar-merge-with in combination with regex, as seen in the example project.clj file https://gitlab.com/technomancy/leiningen/blob/master/sample.project.clj#L436. I'll find another way to express this in the source edn files, so that they become valid edn files and take it from there.

**Comment by borkdude** [comment]
Well, `project.clj` isn't technically EDN.

**Comment by skat-kurt** [comment]
I think I'll go with introducing a reader tag for regex, so that the edn files at least become valid, while `edn/read-string` returns regex data. Something like the following.

```
(edn/read-string
            {:readers {'regex re-pattern}}
            "#regex \"the-pattern\"")
```

**Comment by borkdude** [comment]
@skat-kurt I recommend using something like edamame for this, which is built into babashka as well. You can tweak whatever you want to allow in your `.ednish` or `.cljish` file. E.g. if you want to have EDN + regexes but never a location, you can do this:

```
(require '[edamame.core :as e])
(e/parse-string "..." {:regex true :location? (constantly false)})
```
