### ISSUE TITLE
Wrapping built-in timbre/log! throws an error

### ISSUE THREAD

**Issue by publicimageltd** [babashka/babashka#1679]
**version**
babashka v1.3.188

**platform**

linux

**problem**

When I bind the macro `timbre/log!` in a function, babashka throws an error while doing the same thing with regular clojure works.

Doing it with clojure (using `deps-try com.taoensso/timbre`):
``` clojure
user=> (require '[taoensso.timbre :as timbre])
nil
user=> (defn log-wrapper [& args] (timbre/log! :warn :p args))
#'user/log-wrapper
user=> (log-wrapper "hallo")
2024-03-11T13:17:21.548Z lenovoT14 WARN [user:1] - hallo
nil
```

With babashka:
```clojure
user> (require '[taoensso.timbre :as timbre])
nil
user> (defn log-wrapper [& args] (timbre/log! :warn :p args))
java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Symbol [...]
user> 
```
**expected behavior**
I was expecting both to work the same way. 

The backgound is that I want to bind the logging function to a dynamic variable, but timbre/log! is a macro, so I need to wrap it.

I have no idea what causes the exception.

**Comment by borkdude** [comment]
You can probably get around this by making `log-wrapper` a macro too. I'll look at the bug.

**Comment by publicimageltd** [comment]
I can't bind macros with `binding`, can I? That's what forced me initially to write a wrapper, i.e.

```clojure
(binding [*some-dyn-var* timbre/info] ....
```

Won't compile ("Can't take the value of a macro").

But I can use println for the time being, that's ok.

**Comment by publicimageltd** [comment]
Thanks, I really appreciate the work you put in this!
