### ISSUE TITLE
The sample code on the readme page fails

### ISSUE THREAD

**Issue by dabrazhe** [babashka/babashka#1715]
**Documentation improvement** 

MacOS
babashka v1.3.191 version 

The sample code in the main readme page fails. This is the first command suggested to run after installation, which gives a not desired impression because it fails

```
$ ls | bb -i '(filter fs/directory? *input*)'
("doc" "resources" "sci" "script" "src" "target" "test")
bb took 4ms.
```

**Suggestions**
- Remove the $, because it's copied along the command
- move bb took 4ms. in the new code block 
- update the code to work right out of the box

****repro****

Copy/paste the code from the readme to your terminal and start debugging. 

**expected behavior**

Run without issues right of the bat.

**Comment by borkdude** [comment]
Thanks. I'll just make clear that the dollar sign is a convention to indicate that you're running this in a shell, which is a pretty normal convention imo.

**Comment by dabrazhe** [comment]
And please move these to a new box, otherwise it's copied along 

```
("doc" "resources" "sci" "script" "src" "target" "test")
bb took 4ms.
```

**Comment by borkdude** [comment]
Done as you suggested.
