### ISSUE TITLE
add java.util.TreeMap

### ISSUE THREAD

**Issue by srenatus** [babashka/babashka#1728]
**Is your feature request related to a problem? Please describe.**

I've been meaning to try https://github.com/aroemers/crustimoney in my favorite clojure environment for shell scripting. It failed trying to find java.util.TreeMap, and @borkdude confirmed that it's not built into bb.

I've also tried to narrow it down:
```
user=> (def t (new java.util.TreeMap {:a 1 :b 2}))
clojure.lang.ExceptionInfo: Unable to resolve classname: java.util.TreeMap [at <repl>:1:8]
```

**Describe the solution you'd like**

It would just work.

**Describe alternatives you've considered**

N/A

**Additional context**

This is what it looks like trying to use crustimoney:

bb.edn
```
{:deps {nl.functionalbytes/crustimoney {:mvn/version "2.0.0-rc-3-0x8bb5"}}}
```

```console
$ bb
Babashka v1.4.192 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (require '[crustimoney.core :refer [parse]]                        
         '[crustimoney.string-grammar :refer [create-parser]])
java.lang.Exception: Unable to resolve classname: java.util.TreeMap [at crustimoney/caches.clj:9:3]
```

**Comment by srenatus** [comment]
OK so I've got a build that seems to work with java.util.TreeMap, but it's still insufficient for crustimoney:

```
user=> (new java.util.TreeMap {:a 1 :b 2})
{:a 1, :b 2}
user=> (require '[crustimoney.core :refer [parse]]                        
         '[crustimoney.string-grammar :refer [create-parser]])
clojure.lang.ExceptionInfo: defrecord/deftypecurrently only support protocol implementations, found: CharSequence [at crustimoney/experimental/reader.clj:61:1]
```

Would you think it's worth adding java.util.TreeMap, just because?

**Comment by borkdude** [comment]
@srenatus I usually only add java class if there's a good reason for it and so far this is the only occurrence where this came up. I'm fine with keeping this issue open until someone else has a need as well though.
It's a pity it didn't work out with crustimoney though, although I'm sure that with a bit of effort it could be rewritten in a bb-compatible way. The issue seems to be the `ReaderBuffer` type that implements a Java interface.

**Comment by srenatus** [comment]
GitHub was overeager here. Let's keep this open.

**Comment by borkdude** [comment]
I'm working on crustimoney compat now.

**Comment by borkdude** [comment]
https://github.com/aroemers/crustimoney/pull/26
