### ISSUE TITLE
`./script/compile` fails to set `BABASHKA_SHA` fallback

### ISSUE THREAD

**Issue by frenchy64** [babashka/babashka#1750]
**version**

master

**platform**

macOS

**problem**

I've cloned `babashka` and run `./script/uberjar`. Now I've run `./script/compile` but this happens and the script fails:

**repro**

```
$ ./script/compile
./script/compile: line 110: BABASHKA_SHA: unbound variable
```

**expected behavior**

The script should set the var and continue.

It's failing because `set -u` interferes with the `-z` call.

This can be fixed by using the [following syntax](https://unix.stackexchange.com/a/583068) in `./script/compile`:

```
if [ -z "${BABASHKA_SHA:-}" ]
```

**Comment by borkdude** [comment]
@lispyclouds

**Comment by borkdude** [comment]
Done, thanks.

**Comment by lispyclouds** [comment]
More reasons to use Clojure and not bash 🥲
