### ISSUE TITLE
arrow key not work in REPL

### ISSUE THREAD

**Issue by rmGFW** [babashka/babashka#1766]
<img width="349" alt="image" src="https://github.com/user-attachments/assets/1693104a-c21b-46d1-8523-468cfeaa9d09">
<img width="362" alt="image" src="https://github.com/user-attachments/assets/656ec021-0319-4c44-8789-4449ee2ede3d">
i want use arrow key to control cursor and switch execution history , but it not work

**Comment by borkdude** [comment]
Try `rlwrap bb`

**Comment by borkdude** [comment]
Also see docs here: https://book.babashka.org/#_repl
