### ISSUE TITLE
adding java.nio.file.attribute.UserDefinedFileAttributeView ?

### ISSUE THREAD

**Issue by ryantate** [babashka/babashka#1777]
This class is used to read and write extended attributes from files. I've got a CLI script that depends on it, which I'd love to port to babashka. 

Would you be open to adding it? If so, would a PR be helpful?

(I have not actually obtained an error on this class yet, since there is another class also missing per my other Issue, but I see it is [missing from your supported class ns](https://github.com/babashka/babashka/blob/master/src/babashka/impl/classes.clj) so I anticipate this will be my next failure.)

**Comment by borkdude** [comment]
I'll wait for a PR for this one since the other PR is now merged

**Comment by ryantate** [comment]
OK cool. I just wanted to make sure the other one looked OK to you before I made a second one. Stand by....
