### ISSUE TITLE
Calling `bb` ignores custom `repl` task but requests `:override-builtin`

### ISSUE THREAD

**Issue by frenchy64** [babashka/babashka#1779]
**version**

```
$ bb --version
babashka v1.12.195
```
**platform**

```
uname -a
Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:14 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8103 arm64
```

**problem**

I added a `repl` task to `bb.edn` to override `bb repl`. Calling `bb` ignores this task, but prints a warning implying otherwise.

**repro**

```bash
$ cat bb.edn
{:tasks {repl {:task (println "Hello")}}}
$ bb
[babashka] WARNING: task(s) 'repl' override built-in command(s). Use :override-builtin true to disable warning.
Babashka v1.12.195 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> %                                                                                                                                                                                                    
$ bb repl
[babashka] WARNING: task(s) 'repl' override built-in command(s). Use :override-builtin true to disable warning.
Hello
$
```

**expected behavior**

Either `bb` uses my custom `repl` task or I am not prompted to add `:override-builtin true`.

**Comment by borkdude** [comment]
looks like a bug indeed, will check tomorrow

**Comment by borkdude** [comment]
btw, what happens if you add :override-builtin true to your task?

**Comment by frenchy64** [comment]
The warning is silenced but same behavior.

-------- Original Message --------

**Comment by borkdude** [comment]
I can't reproduce this. Am I missing something?

```
borkdude@m1-4 /tmp/dude $ /opt/homebrew/bin/bb repl
Hello
borkdude@m1-4 /tmp/dude $ cat bb.edn
{:tasks {repl {:task (println "Hello")
               :override-builtin true}}}
borkdude@m1-4 /tmp/dude $ /opt/homebrew/bin/bb repl
Hello
borkdude@m1-4 /tmp/dude $ cat bb.edn
{:tasks {repl {:task (println "Hello")}}}
borkdude@m1-4 /tmp/dude $ /opt/homebrew/bin/bb repl
[babashka] WARNING: task(s) 'repl' override built-in command(s). Use :override-builtin true to disable warning.
Hello
borkdude@m1-4 /tmp/dude $ /opt/homebrew/bin/bb --version
[babashka] WARNING: task(s) 'repl' override built-in command(s). Use :override-builtin true to disable warning.
babashka v1.12.195
```

**Comment by borkdude** [comment]
Oh I understand what you mean now. 
Invoking `bb` does not implicitly invoke a task overrides with the name `repl`, it just always invokes a console REPL. You can't override this with tasks, that's not how it's intended. The override warning just warns you when you override an explicit bb subcommand like `bb repl`.

**Comment by frenchy64** [comment]
Ah, my mistake. I didn't realize the warning was triggered regardless of the subcommand.

This line from `bb --help` also made me unsure of the intended behavior. It might help to add a note that tasks are ignored.

```
When no eval opts or subcommand is provided, the implicit subcommand is repl.
```
