### ISSUE TITLE
Port tests to Windows

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#235]
Windows builds are done using Appveyor:

https://ci.appveyor.com/project/borkdude/babashka

Some tests are marked with `^:windows` metadata which are tested on Appveyor.

Many tests are failing for trivial reasons:

```
actual: (not (= "process 2\n" "process 2\r\n")
```

We already have a predicate `babashka.main/windows?` that determines if babashka is running in Windows, which can be used.

There is now also a `test-utils/normalize` function which is used to replace `\r\n` to `\n` when tests are running in Windows.

Some tests might not be suited for running on Windows, which can be handled by wrapping them in a conditional: `(when-not main/windows? ...)`.

Multiple smaller PRs to the windows-tests branch, one for each test are welcome.

**Comment by borkdude** [comment]
@kolharsam If you want, you can help fix the Windows tests.

I'll update the issue with some instructions.

**Comment by bobisageek** [comment]
Is this still 'available'? I started messing around with some of the tests, so I could put in a PR that addresses about 10 tests (on the JVM env), but the windows-tests branch is also well behind master, so do you think it would make more sense to merge in from master first?

**Comment by borkdude** [comment]
Hi @bobisageek, thanks for your interest in adding/improving Windows tests. I now brought the `windows-tests` branch up to date, but lots of tests are failing. A PR and fixes to this branch are more than welcome. I was thinking: perhaps we can add metadata to tests so only a selection of tests run on Windows, so we can merge the branch into master and work more gradually on it.

**Comment by borkdude** [comment]
I now added a test selector called `:windows` and flagged one test with `:windows` metadata. 

This is running here: https://ci.appveyor.com/project/borkdude/babashka/builds/39621659

If all tests still pass on the other platforms, I will just merge this branch so we can continue on master.

**Comment by borkdude** [comment]
Merged. Let's continue on the master branch by adding `^:windows` gradually to more tests.

**Comment by bobisageek** [comment]
@borkdude style question regarding the test selectors: I'm working on separating the handful of tests that have different enough implementations on Windows and *nix to make them separate tests. We've done the :skip-windows tag, and I'm also adding a :windows-only tag, but some of these tests already have checks along the lines of `(when b.main/windows?...`. If we ensure that those checks are comprehensive, then the selectors become redundant from the standpoint of being able to run 'lein test' and get only the tests that are aimed at the target platform. However, the tags/selectors add some value in terms of consistently communicating intent (e.g. it's communicated at the `deftest` level if the test has platform dependence), but the trade-off would be that there's a chance for them to get out of sync with the `windows?` checks.

Do you have a preference regarding using the tags/selectors or using `when main/windows?` checks or both?

**Comment by borkdude** [comment]
I would be fine with migrating over to the test metadata.

**Comment by borkdude** [comment]
@bobisageek Do I understand correctly that we can close this issue now that you've pretty much finished it?

**Comment by bobisageek** [comment]
I was actually just reviewing the gaps between Windows and *nix testing, and I think the gaps that remain are small enough that this issue could be closed.

Possibly even more importantly, new tests will run on Windows unless they're explicitly skipped, so that feels like a pretty big win.

**Comment by borkdude** [comment]
@bobisageek You've done a terrific job, thanks a lot. Feel free to follow up with more PRs if necessary, even with the issue closed.
