### ISSUE TITLE
What companies or projects are using babashka and/or sci?

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#254]
This issue has several purposes:

- Your company might be mentioned in a sheet of a presentation about babashka or sci. A link to a logo would be helpful.
- This issue would be a good way to notify you of any breaking changes in babashka or sci (which we will try to prevent).
- Your company is listed on [this](https://github.com/babashka/babashka/blob/companies/doc/companies.md) page.

If you would like to sponsor babashka and/or SCI, I would be happy to take your money! :)

https://opencollective.com/babashka
https://github.com/sponsors/borkdude

**Comment by ikitommi** [comment]
Metosin

**Comment by retrogradeorbit** [comment]
Using sci
Epic Castle 
https://epiccastle.io/images/logo.png

**Comment by cldwalker** [comment]
Reify Health
Logo at https://www.reifyhealth.com/

**Comment by jeroenvandijk** [comment]
Adgoji 

We use Babashka in scripts. Sci is used in tooling around Cloudformation and AWS Lambda (in development).

Logo [here](https://drive.google.com/file/d/1VlUhnrodGmZZd8bQl-PFgJPBdJTf_H4M/view)

**Comment by bmillare** [comment]
AWS

I'm trying it out, not using it in production. Can't get it to build on my work VM though, graal 19.3.1 is complaining about unsupported features. I need to build it myself because we are using a different version of glibc. I'm just using the standalone jar for now.

**Comment by borkdude** [comment]
@bmillare babashka is currently built with graalvm-jdk8. There is an issue about jdk11 here:

https://github.com/borkdude/babashka/issues/120
and the branch:
https://github.com/borkdude/babashka/tree/jdk11

**Comment by borkdude** [comment]
@bmillare babashka is currently built with graalvm-jdk8. There is an issue about jdk11 here:

https://github.com/borkdude/babashka/issues/120
and the branch:
https://github.com/borkdude/babashka/tree/jdk11

Do you have a link to the AWS company?

**Comment by bmillare** [comment]
@borkdude I see. I'll try building on jdk8. I work for AWS, specifically ECS. https://aws.amazon.com/ecs/

**Comment by borkdude** [comment]
@bmillare Cool! 

Babashka now also has a Dockerfile: 

https://github.com/borkdude/babashka/blob/master/Dockerfile

That should give you an idea.

It's deployed to Docker hub too:

https://hub.docker.com/r/borkdude/babashka/

**Comment by borkdude** [comment]
NextJournal is using babashka in their notebook images:

> it’s in our base bash environment and I want to use it for all our more complex scripting needs as well as for custom language runtimes

https://nextjournal.com

**Comment by brunchboy** [comment]
Deep Symmetry just adopted it to build a plugin for generating byte field diagrams in Asciidoctor and Antora documents. I have to hand it to you! I got quite far building my own interpreter based on an EDN parser, and was as far as having special forms like `def` and `let` and `doseq` work, building diagrams like the one linked to in the [project README](https://github.com/Deep-Symmetry/bytefield-svg) when someone pointed me at sci. I am going to miss out on the fun of finishing off some of the other special forms I had sketched out in my head, but I would never have caught up to you, and now I can get back to porting my documents from LaTeX and focusing on my own core features. 🎉

**Comment by borkdude** [comment]
@brunchboy Thank you! I added this project to the list here: https://github.com/borkdude/sci/#why

**Comment by rodolfo42** [comment]
I'm using `babashka` at Nubank quite a lot lately, it's been really helpful. I've heard of a couple of colleagues that use it as well.

I use it for various things, mostly around transforming outputs of some internal cli commands or semi-structured application log lines (we use clojure so most of our log lines are basically edn) and sometimes performing some actions like downloading/printing referenced files, showing some summaries or reducing map structures to a more human-friendly way. Reduces a great deal of toil for me.

Thanks for the project @borkdude!

I guess our logo would be in this page: https://nubank.com.br/en/press/
But my message here is mostly for the shout-out.

**Comment by DarinDouglass** [comment]
We at Barracuda use babashka for most new scripting tools. Our kube manifest pre-processor started off as a babashka utility and morphed into a JVM clojure environment that uses SCI to process fn and macro calls

Our logo can be found here: https://www.barracuda.com/media

**Comment by liquidz** [comment]
We are using both of babashka and clj-kondo😃 
Thanks for your awesome job!

TOYOKUMO,Inc.
Logo: https://github.com/borkdude/clj-kondo/issues/438#issuecomment-533347900

**Comment by JduPreez** [comment]
[Lifecheq](http://www.lifecheq.co.za) is making use of sci for many of our tools, allowing development to build the tools and platform, and business to extend it and implement their own solutions. 

Thank you so much for sci. It's absolutely fantastic!

**Comment by borkdude** [comment]
Thanks for sharing you all!

To quote the tweet of @JduPreez:

> @borkdude's Small Clojure Interpreter enabled Lifecheq to add scripting to our tools. Now the whole business is learning #Clojure & everyone's scripting their own solutions. This frees up a lot of time from the dev team. Pretty cool if you ask me

<img width="601" alt="Screenshot 2020-07-01 12 44 03" src="https://user-images.githubusercontent.com/284934/86235370-9e17bb80-bb98-11ea-94a2-0e3008291c56.png">

Business people writing Clojure, that IS pretty cool.

**Comment by stevebuik** [comment]
[Nextdoc.io](https://www.nextdoc.io) is using Babashka every day in devops/monitoring. Planning to add sci to our ETL system soon. 

Love your work!

**Comment by lukaszkorecki** [comment]
[EnjoyHQ](https://enjoyhq.con)

We use bb for a couple of things

- ECS stats scraper daemon, runs as a sidecar with each service we deploy
- operations/infrastructure scripts
- YAML/JSON configuration generator

**Comment by eraad** [comment]
https://datil.com

Build scripts!

**Comment by anthony-khong** [comment]
[Zero One Group](https://zero-one-group.com/)

We use Babashka for:
- General scripting such as this [auto version-bump script in Geni](https://github.com/zero-one-group/geni/blob/develop/scripts/version-bumps.clj)
- Ad-hoc data transformations such as transforming a CSV to pretty-printed EDN.
- Automating GitLab using babashka.curl and [GitLab API](https://docs.gitlab.com/ee/api/), such as batch deleting/labelling/moving issues.

**Comment by borkdude** [comment]
I appreciate all the postings here. I added this to the original post and will post it here only once. *Do not feel obligated to do anything with this*, I just want to know that this is an area I'm exploring and there are possibilities to help this project grow.

If your company is using babashka or sci and profiting from it, consider donating via OpenCollective or Github actions:

https://opencollective.com/babashka
https://github.com/sponsors/borkdude

I might be able to sustain myself from open source work in the future. Around 4000-5000 dollars/euros a month should be enough to get started and around 8000 dollars/euros a month should be sufficient to live comfortably in the long term (not that I also have to pay taxes which are quite high in my country, save for retirement, etc.). 

If you have different ideas on how to provide income from babashka while also keeping it free, open source and accessible, feel free to reach out to me in private.

**Comment by huahaiy** [comment]
Datalevin native command line shell use sci for executing query/transaction.

**Comment by takaczapka** [comment]
https://www.hi55.uk

scripted tools!

**Comment by borkdude** [comment]
@huahaiy Thanks! @takaczapka Can you tell more about what you are doing? Using babashka or sci? In what way?

**Comment by takaczapka** [comment]
We use babashka to run operation/admin tasks against live system. Usually it involves calling a REST or GraphQL endpoints with payload loaded from a file or typed as arguments. Our thinking is to develop scripts first, and later (but only if they are prove to be useful) convert them to screens in the web portal. So babashka helps us to iterate quickly and decide what is needed in the longer run and what's not.

**Comment by latacora-gabriel** [comment]
At https://www.latacora.com/, we're using sci for a sandboxed environment (and hopefully bb for some util and devops tasks soon). [Logo is here](https://www.latacora.com/images/logo150x150.png). Thanks for all that you do!

**Comment by borkdude** [comment]
Thanks a lot for sharing!

**Comment by joelittlejohn** [comment]
We use babashka at JUXT as a general-purpose bash replacement for all kinds of scripting tasks. We've used it to create build and deploy scripts for small projects, and we've used to it create small utilities and more fully featured CLI tools. 

Logo at https://www.juxt.land/logo-normal.svg.

**Comment by borkdude** [comment]
@joelittlejohn Great to hear, thanks for sharing.

**Comment by interstar** [comment]
Using SCI for scripting in Cardigan Bay : 

https://www.youtube.com/watch?v=H7_THeK9EBw

https://github.com/interstar/cardigan-bay/releases/tag/0.6.0

**Comment by borkdude** [comment]
@interstar Thanks for sharing. I added your project here: https://github.com/borkdude/sci#projects-using-sci

**Comment by pmonks** [comment]
I'm using `sci` in this little Discord bot: https://github.com/pmonks/for-science

**Comment by jgrodziski** [comment]
Use SCI for scripting of the [administration tasks of keycloak-clojure](https://cljdoc.org/d/keycloak-clojure/keycloak-clojure/1.18.0/doc/administrative-tasks#realm-setup-with-keycloak-clojure-starter-cli)

**Comment by rdgd** [comment]
[Splash Financial](https://www.splashfinancial.com/) uses Babashka for scripting things which Bash just isn't suited for (and because we love Clojure)

[Company logo](https://www.splashfinancial.com/wp-content/uploads/2021/05/logo.svg)

**Comment by borkdude** [comment]
I've created a companies.md page in the babashka repo now:

https://github.com/babashka/babashka/blob/master/doc/companies.md

Sponsoring companies are listed first, in order of payment. They will be able to provide a direct hiring link as well. Remaining companies are listed in alphabetical order. I will create a similar page for clj-kondo and SCI.

In other news, I have quit my long time job to work more on my open source projects. Any additional sponsoring will help me continue doing so! :-)

**Comment by askonomm** [comment]
[Fluent](http://fluent.to), where I work, uses Babashka for tasks. 

[Logo](https://uploads-ssl.webflow.com/600fdbbcf0cbfe02f1a48030/600fdf0fffe881c3e8e298f4_Fluent%20logotype-p-500.png)

**Comment by stask** [comment]
PractiTest, build scripts and utilities
practitest.com
