### ISSUE TITLE
Provide args via file like JDK9

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#266]
https://stackoverflow.com/questions/201816/how-to-set-a-long-java-classpath-in-windows/54270831#54270831

**Comment by bobisageek** [comment]
@borkdude do you feel like `bb.edn` and tasks make this sort of obsolete? While I guess it might not cover every possible use case, I think at least the big ones are covered:

- "classpath too big" - bb.edn makes it possible to create those big classpaths (arguably in a much more elegant way)
- common argument sets - I imagine the intent of this would be to make often-used invocations easy to execute, which feels like basically just what tasks are made for (but of course, tasks make even more possible)
