### ISSUE TITLE
Document checking if data is available on stdin

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#324]
```
$ bb '(pos? (.available System/in))'
false
$ echo true | bb '(pos? (.available System/in))'
true
```

**Comment by cldwalker** [comment]
I noticed this detection doesn't work when chaining one bb command to another:

```sh
$ bb '(println [1 2 3])' | bb '(.available System/in)'
0
$ echo '[1 2 3]' | bb '(.available System/in)'
8
```
Any idea why this would happen?

**Comment by kolharsam** [comment]
@cldwalker I tried the code snippet that you posted.
```clojure
$ bb '(println [1 2 3])' | bb '(.available System/in)'
=> 8
```
This seems to be giving the correct result on `v0.0.94`.

**Comment by borkdude** [comment]
Maybe it depends on the operating system. What operating system are you using @kolharsam? I still see:

```
$ bb '(println [1 2 3])' | bb '(.available System/in)'
0
```

**Comment by kolharsam** [comment]
I'm on macOS 10.15.4.


> Maybe it depends on the operating system.

I thought so too.

**Comment by cldwalker** [comment]
I'm on osx 10.13.1. For now I worked around this by adding an explicit flag to signal to not read from stdin. Of course it would be nice if we could detect this between bb commands

**Comment by borkdude** [comment]
@cldwalker Another thing I noticed:

```

$ bb '(println "foo")' | bb '(.available System/in)'
4
```
so when printing a string, it does seem to work.

**Comment by borkdude** [comment]
This also seems to work:

```
$ bb '(println ["foo"])' | bb '(Thread/sleep 100) (.available System/in)'
6
```
so it must be a matter of timing.
