### ISSUE TITLE
include test.check (as preparation work for clojure.spec)

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#487]
@lread made a start with this here: https://github.com/lread/sci-test/blob/master/src/sci_test/impl/test_check.clj

**Comment by green-coder** [comment]
Supporting `test.check` in bb/sci will also enable the generators in a lot more libraries, including:
- Minimallist,
- Malli,
- Regal

I am looking forward to it. 😻

**Comment by borkdude** [comment]
Included in 0.2.8, just released
