### ISSUE TITLE
`doc` doesn't print docstrings for macros

### ISSUE THREAD

**Issue by j-cr** [babashka/babashka#531]
**version** babashka v0.1.3
**platform** linux/irrelevant

**problem**

`(doc <macro>)` prints nothing but `nil`, even though `(doc <fn>)` works just fine.

**repro**

```
user=> (doc defn)
nil
user=> (doc for)
nil
user=> (doc ->)
nil
```

**Comment by borkdude** [comment]
Thanks for the issue. The reason for this is that most function vars are copied (including docstrings) but macros are often re-implemented. This can be fixed though.
