### ISSUE TITLE
Add Debian Packaging.

### ISSUE THREAD

**Issue by aadrian** [babashka/babashka#533]
Please add Debian Packaging too.

There are GitHub Actions that can do that, e.g. https://github.com/dawidd6/action-debian-package

Thanks in advance.

**Comment by borkdude** [comment]
This would be awesome. I have tried this in the past, but gave up because the process was too much work. Are you sure it's just "use this Github action and it kind of works" ? Are there any example packages using this Github action?

**Comment by aadrian** [comment]
>  Are you sure it's just "use this Github action and it kind of works" ?

Sorry, no. I haven't tried that particular GitHub Action myself :( . 

I tried myself this https://github.com/marketplace/actions/build-rpm-action for some RPMs and it works great.

Personally I'm using most of the time Gradle/Maven (even for Clojure projects with https://github.com/clojurephant/clojurephant ), and it can build:
 - RPM and DEB only with: https://github.com/nebula-plugins/gradle-ospackage-plugin
 - for all major platforms (requires more fiddling) with https://github.com/i-net-software/SetupBuilder

Example project with Gradle using the Nebula Plugins https://github.com/mucommander/mucommander , see https://github.com/mucommander/mucommander/blob/master/build.gradle#L161 (mostly I just copy and modify those sections :) )

**Comment by borkdude** [comment]
I wouldn't mind if anyone volunteered to maintain the .deb package. I'll leave this issue open for people to respond.

**Comment by lukaszkorecki** [comment]
Since babashka is a static binary (right?) there's a couple of projects that can help with that, I've used both in the past with great success, before Docker that is:

- fpm https://fpm.readthedocs.io/en/latest/intro.html
- packager.io https://packager.io - although this one is more suited for packaging applications

**Comment by borkdude** [comment]
Babashka is dynamically linked against libraries that are very common on linux systems. In rare cases (like Alpine) people need to use the static binary. @lispyclouds knows more about the ins and outs of the preference for dynamically linked babashka.

**Comment by borkdude** [comment]
```
borkdude@vps1918:~$ ldd bb
	linux-vdso.so.1 (0x00007fff84de0000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa93b844000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa93b823000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa93b81e000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa93b600000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa93b5f6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa93b435000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa93b2b0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa93ee75000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa93b296000)
```

**Comment by lukaszkorecki** [comment]
Gotcha, in that case `fpm` is the way to go - you can bake in dependencies for Debian, similarly to how it's done here: https://github.com/jordansissel/fpm/issues/1071  - bearing in mind that `dpkg` doesn't install dependencies for you, but there's a way of hacking around with `apt-get`.

I'd love to help out with this issue - as I used to be knee-deep in this stuff, but I barely have any time 😿

**Comment by lispyclouds** [comment]
I would say we stick to having a dynamic linked binary for bb for a debian package and add the deps via dpkg. Adding onto what @borkdude said, static binaries cause unforseen issues and in general debian recommends dynamic linked binaries more from the perspective of security and other updates being possible without updating the software itself.

About the debian packaging, I think it would be really worth it to get it into Debain mainline via the proper packaging process. It's a bit tedious compared to other Linux distros but once it happens it would be available to all Debians and its derivatives, namely Ubuntu and friends via a direct `apt install babashka`. This would be really awesome as this impacts a wider audience and eases the install greatly. More [info](https://wiki.debian.org/Packaging)

I have some experience doing debain mainline packaging and have maintainer access on some, I can try to initiate the process with the Debain Clojure [team](https://wiki.debian.org/Clojure). I have had some very minimal contact with [Elena Hashman](https://twitter.com/ehashdn) who is the lead maintainer for clojure things on Debian and I would try to contact her for some guidance. I can take this up to get my rusty debian muscles working again and bb to more places! 😄 😄

**Comment by ieugen** [comment]
I'm also interested in providing a hand. 

Providing packages upstream for the native binary will require GraalVM + substratevm to be in Debian (and maybe some other things).

**Comment by borkdude** [comment]
Anyone that wants to work on this, feel free, this can happen outside of the babashka org
