### ISSUE TITLE
Consider hot-swapping parts of sci / edamame for speed

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#544]
Sci and edamame are highly configurable. Checking for certain settings during evaluation might take some time while babashka doesn't use those settings per se. We could try swapping out `interpret` and `eval-call` for lighter versions that could maybe speed up things.

Note that we're compiling with direct linking, so alter-var-root probably isn't going to work.

**Comment by jeroenvandijk** [comment]
Are you considering a protocol approach? Contexts could be protocol implementations (e.g. records) and be configurable at the start of an invocation.

```clojure
(defn eval-string [s] 
   (-eval-string s (create-babashka-context)))
```

E.g. 
```clojure
(defprotocol IInterpret
  (-interpret [_ expr]
   ...)

(defrecord BabashkaContext [bindings namespaces
   IInterpret
   (-interpret [_ expr]))

(defrecord SciContext [bindings namespaces termination-safe]
   IInterpret
   (-interpret [_ expr] 
      ...))
```

Some previous (unsuccessful) efforts: [Sci with protocols](https://github.com/borkdude/sci/compare/master...jeroenvandijk:features/protocol-interpreter), [First steps of a simple interpreter with protocols ](https://gist.github.com/jeroenvandijk/aac0d4373ede06aea927840f3fd41faf)

**Comment by borkdude** [comment]
Probably not, just a hack in babashka that swaps out some functions with others that skips that aren't relevant to babashka (possibly just using a volatile). It remains to be seen how much performance is gained. If it's not significant, then I'll just not merge it.
