### ISSUE TITLE
consider adding core.logic

### ISSUE THREAD

**Issue by linpengcheng** [babashka/babashka#546]
try to add all standard libs in https://github.com/clojure

**Comment by borkdude** [comment]
Can you be more specific?

**Comment by linpengcheng** [comment]
core.logic

**Comment by borkdude** [comment]
@linpengcheng Could you elaborate how useful core.logic would be for scripting purposes?

See the inclusion criteria here: https://github.com/borkdude/babashka#including-new-libraries-or-classes

**Comment by linpengcheng** [comment]
I think babashka can become an IDE for database (analysis) applications, 
such as Foxpro (the former king of desktop database developers), 
Racket(all in one), Janet(clojure-like, stdlib: db, webapp, ui), python Jupyter,etc.

- If built-in H2 database (and its Web console), http-kit, then babashka has all Foxpro components (database engine, database management, GUI(Web), programming language), and clojure is good at manipulating data, becoming departmental or small Enterprise's WebApp database development solution.

- If you add data visualization libraries such as oz, darkstar, or call an external command line visualization engine, It will be a good data display platform.

- Babashka is not suitable for big data analysis, but if fastmath & core.logic is integrated, it can become a lightweight `expert system` type data analysis platform.

I think babashka comes with libraries and JVM class libraries should be as complete as possible, larger size is not a problem, storage is very cheap.

**Comment by borkdude** [comment]
@linpengcheng One limitation is memory on CI. If we add more and more stuff to it without thinking about it first, then we will hit the CI memory limit and we will have to remove stuff again, which will be a breaking change. A solution for this is babashka pods: https://github.com/babashka/babashka.pods. There is already a pod for PostgreSQL and HSQLDB: https://github.com/babashka/babashka-sql-pods.

**Comment by borkdude** [comment]
Another approach is to add more feature flags for features not everybody needs: https://github.com/borkdude/babashka/blob/master/doc/build.md#feature-flags
Companies that want to use non-standard features can build babashka with these flags.
