### ISSUE TITLE
Document io.aviso/pretty ansi usage in libraries.md

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#547]
``` 
$ export BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {io.aviso/pretty {:mvn/version "RELEASE"}}}')
$ bb -e "(require '[io.aviso.ansi :as ansi]) (println (str \"The following text will be \" ansi/bold-red-font \"bold and red\" ansi/reset-font \".\"))"
``` 

![Screenshot 2020-08-20 at 19 48 54](https://user-images.githubusercontent.com/284934/90807471-d036d580-e31e-11ea-96dc-8e2c9479fada.png)

**Comment by justone** [comment]
There is also the https://github.com/trhura/clojure-term-colors lib, which works with Babashka.

**Comment by borkdude** [comment]
Both added to projects.md.
