### ISSUE TITLE
Make a list of missing classes from java.time (e.g. which are used in tick)

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#554]
And see how much size it would cost to add those.

**Comment by bobisageek** [comment]
Tick's master branch currently has a `deftype`. Tick also has a 'babashka' branch where that deftype is removed, so we start running into the missing classes. My list (so far) is:
- `java.text.ParsePosition`
- `java.time.temporal.TemporalQuery`

... assuming the java.time feature is enabled, adding these two classes allows for a little progress, and then when testing the `tick.interval` namespace, we run into the `GeneralRelation` record implementing the `IFn` interface, which of course leads to the 'Records currently only support protocol implementations' exception.

As far as growth from adding the classes, on my Windows build environment, those 2 classes add ~5KB to the executable size.

**Comment by borkdude** [comment]
It seems fine to add those classes, but perhaps as a PR which explicitly adds support for a library (like tick) and not just for the purpose of "maybe there's a library out there which we will enable by this". The other restrictions tick currently has seem like blockers for now. I think I've seen several libs around java.time in the Clojure space, one of them is cljc.java-time which runs fine. I usually recommend bb users to just embrace java.time interop and create a few helpers functions here and there.

**Comment by borkdude** [comment]
We will revisit this as needed.
