### ISSUE TITLE
Consider adding clojure.spec

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#558]
Do we need spec at all in babashka? We already have https://github.com/borkdude/spartan.spec. Building clojure spec into babashka will make it run faster though.

Use cases:

- Verifying CLI args (see https://github.com/l3nz/cli-matic/issues/113)

One issue with clojure.spec is that currently spec2 is in the making. Should we wait for this, or add clojure.spec1 and migrate to spec2 once it comes out? This will be a breaking change. Another possibility is to offer a feature flag so people can optionally compile babashka with spec support.

Work in progress in the `spec` branch.
TODO:
- [x] clojure.test.check.random issue https://gist.github.com/borkdude/768eb5d01085944190e5eb485fd4737a
- [ ] hook `clojure.spec.test.alpha`'s `resolve` references to sci's resolve

**Comment by aadrian** [comment]
+1 for waiting for `clojure.spec2`

**Comment by wagjo** [comment]
How about adding spec2 right now?

**Comment by borkdude** [comment]
@wagjo I don't know how stable spec2 is right now. It's still in development.

**Comment by puredanger** [comment]
@wagjo spec 2 is still likely to undergo significant changes, so I would not recommend this

**Comment by borkdude** [comment]
60% of people are in favor of waiting for spec 2 according to this poll: https://twitter.com/borkdude/status/1299975678885072898

**Comment by serioga** [comment]
@borkdude Cannot we have both included when spec2 is released?

**Comment by borkdude** [comment]
@serioga I guess we could.

**Comment by serioga** [comment]
Well, so I vote for adding spec1 now and spec2 later allowing to use spec1 after adding spec2 :-)

**Comment by seancorfield** [comment]
I was a bit surprised the poll seemed to present Spec 1 vs Spec 2 as an "either/or" since Spec 1 is still going to be around for a long time even after Spec 2 is finalized (and incorporated into Clojure as `clojure.spec`). I'd say go ahead and add Spec 1 if folks think it is valuable enough and then add `clojure.spec` once it is finalized -- no need to _remove_ Spec 1 at that point.

I don't have a dog in this fight since I don't use babashka (yet) but, for me, adding Spec feels like overkill for a command-line scripting tool, which is how I think of babashka.

**Comment by borkdude** [comment]
@seancorfield 

> adding Spec feels like overkill for a command-line scripting tool

Spec is part of Clojure core and some libraries leverage this, e.g. for checking command line args:

https://github.com/l3nz/cli-matic/issues/113

A list of currently compatible libraries:

https://github.com/borkdude/babashka/blob/master/doc/libraries.md

Adding spec 1 and/or 2 could unlock a new category of existing libraries.

Figuring out how to add spec to sci (babashka's Clojure interpreter) could also have an interesting effect on clj-kondo, which is also a command line tool. This would allow you do provide user-defined code to do checking on function and macro calls. One could write a spec and run it over the sexpr, like the Clojure compiler itself does at macro-expansion time.

One other command line utility I could see happening is generating test data to test web APIs from scripts.

I'm running an extended poll here: https://twitter.com/borkdude/status/1300428421252747266

**Comment by seancorfield** [comment]
Hah, fair enough! The possibility of extending `clj-kondo` like that is appealing 👍

**Comment by borkdude** [comment]
https://twitter.com/borkdude/status/1300428421252747266:

- Malli now, no spec 33%
- Nothing now, spec2 later 30%

I might still go forward with including spec1, but only under a feature flag. This way we can figure out the details, without including it in bb yet. Once spec2 becomes stable we have figured out most of the stuff we need to include it shortly after.

**Comment by digash** [comment]
Here is a tool [crucible](https://github.com/brabster/crucible) that uses spec and would be nice to run with bb.
```
Babashka v0.2.2 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=>
(ns crucible.examples-test
  (:require [crucible.core :refer [template parameter resource output xref encode join]]
            [crucible.aws.ec2 :as ec2]))
Could not resolve symbol: clojure.lang.Compiler/demunge [at clojure/spec/alpha.clj:128:16]
crucible.examples-test=>
```

**Comment by borkdude** [comment]
@digash Warning: hacks ahead! 

I experimented a bit, fooling this library by creating a `clojure.spec.alpha` namespace and mapping some things from spartan.spec to it. I think it even runs expound. Note that I stubbed some macros with empty implementations. 

To run it, first set `BABASHKA_CLASSPATH`:

```
export BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {borkdude/spartan.spec {:git/url "https://github.com/borkdude/spartan.spec" :sha "ff7317d67ec15f188afb856d37090e5c9509374e"}  crucible/crucible {:mvn/version "0.46.0"}}}')
``` 

The final result:

``` 
(println (encode simple))
;; prints:
;; {"AWSTemplateFormatVersion":"2010-09-09","Description":"A simple sample template","Outputs":{"Vpc":{"Value":{"Fn::Join":["/",["foo",{"Ref":"MyVpc"}]]}}},"Parameters":{"MyVpcCidr":{"Type":"String"}},"Resources":{"MyVpc":{"Type":"AWS::EC2::VPC","Properties":{"CidrBlock":{"Ref":"MyVpcCidr"}}}}}
``` 

The script:

``` clojure
(ns clojure.spec.alpha
  (:refer-clojure :exclude [keys + * or cat assert and])
  (:require [clojure.core :as c]
            [spartan.spec :as s]))

(defmacro def [& args]
  `(s/def ~@args))

(defmacro keys [& args]
  `(s/keys ~@args))

(defmacro * [& args]
  `(s/* ~@args))

(defmacro + [& args]
  `(s/+ ~@args))

(defmacro or [& args]
  `(s/or ~@args))

(defmacro and [& args]
  `(s/and ~@args))

(defmacro nilable [& args]
  `(s/nilable ~@args))

(defmacro coll-of [& args]
  `(s/coll-of ~@args))

(c/def conform s/conform)

(c/def get-spec s/get-spec)

(defmacro unform [& _args]
  ;; Not implememented in spartan.spec
  )

(defmacro fdef [& _args]
  ;; Not implememented in spartan.spec
  )

(defmacro form [& _args]
  ;; Not implememented in spartan.spec
  )

(defmacro with-gen [& _args]
  ;; Not implememented in spartan.spec
  )

(alter-meta! #'s/dt dissoc :private)

(defn multi-spec-impl [mm retag]
  (let [id (gensym)
        predx #(let [mm mm]
                 (mm %))]
    {:type :spartan.spec/spec
     :cform  (fn [_ x]
               (if-let [pred (predx x)]
                 (s/dt pred x nil #_form)
                 ::invalid))}))

(defmacro multi-spec [mm retag]
  `(multi-spec-impl ~mm ~retag))

(defmacro cat [& args]
  `(s/cat ~@args))

(defmacro spec [& args]
  `(s/spec ~@args))

(defmacro assert [& args]
  `(s/assert ~@args))

(defmacro map-of [& args]
  `(s/map-of ~@args))

(c/def valid? s/valid?)

(c/def *explain-out* #'s/*explain-out*)

(c/def explain-data s/explain-data)

(c/def explain-printer s/explain-printer)

;; not in bb yet, will fix for next version
(intern 'clojure.core ^:dynamic '*print-namespace-maps* false)

(require '[clojure.pprint])

(ns clojure.pprint)

(def write) ;; write isn't in bb's clojure.pprint yet, will fix for next version

(ns crucible.examples-test
  (:require [crucible.aws.ec2 :as ec2]
            [crucible.core :refer [template parameter output xref encode join]]))

(def simple (template "A simple sample template"
                      :my-vpc-cidr (parameter)
                      :my-vpc (ec2/vpc {::ec2/cidr-block (xref :my-vpc-cidr)})
                      :vpc (output (join "/" ["foo" (xref :my-vpc)]))))

(println (encode simple))
;; prints:
;; {"AWSTemplateFormatVersion":"2010-09-09","Description":"A simple sample template","Outputs":{"Vpc":{"Value":{"Fn::Join":["/",["foo",{"Ref":"MyVpc"}]]}}},"Parameters":{"MyVpcCidr":{"Type":"String"}},"Resources":{"MyVpc":{"Type":"AWS::EC2::VPC","Properties":{"CidrBlock":{"Ref":"MyVpcCidr"}}}}}
```

**Comment by borkdude** [comment]
Meanwhile I published another native CLI tool that exposes `clojure.spec.alpha` for grepping Clojure code:

https://github.com/borkdude/grasp

**Comment by borkdude** [comment]
I made a few small changes to spartan.spec. It now defines a namespace `clojure.spec.alpha` when loaded, for compatibility.
This change allows you to e.g. use expound:

https://github.com/borkdude/spartan.spec#example

**Comment by borkdude** [comment]
FYI, the following libs now work (from source):

- Expound. Example: https://github.com/borkdude/spartan.spec#example
- Cli-matic. Example: https://github.com/borkdude/spartan.spec/blob/master/examples/cli_matic.clj
- Crucible. Example: https://github.com/borkdude/spartan.spec/blob/master/examples/crucible.clj

Spartan.spec itself takes 40ms to load (on my machine). Expound takes another 50ms. Cli-matic takes another 50ms. So in total the combination of these will take about 150ms of startup time, currently.

**Comment by onetom** [comment]
I was just about about try the following, but it seems it requires clojure.spec too:
```clojure
  (require '[babashka.deps :as deps])

  (deps/add-deps
   '{:mvn/repos {"datomic-cloud" {:url  "s3://datomic-releases-1fc2183a/maven/releases"}}
     :deps {com.datomic/tools.ops {:mvn/version "0.10.82" :exclusions  [org.slf4j/slf4j-nop]}}})

  (require '[datomic.tools.ops.cloud :as datomic-cloud])
```
It errored out with:
```
clojure.lang.ExceptionInfo: Could not resolve symbol: clojure.lang.Compiler/demunge [at clojure/spec/alpha.clj:128:16]
```

The reason I'm trying this is because the current command-line tooling for Datomic Cloud is written in shell scripts, which run a full-blown JVM Clojure via Clojure CLI tools and it's brutally slow, especially when I need to combine multiple operations.

Here is an almost complete example of what I'm trying to achieve (and it works in JVM Clojure):
```clojure
(ns xxx
  (:require
    [datomic.tools.ops.cloud :as datomic-cloud]
    [datomic.tools.ops.system :as datomic-system]))

  (let [aws-ctx {:profile "default"}]
    (->> (datomic-cloud/list-systems aws-ctx)
         (mapv (fn [datomic-system]
                 (rassoc datomic-system :instances
                         #(datomic-system/list-instances
                            (into aws-ctx {:system (:name %)})))))
         (into {}
               (map (fn [{:as   datomic-system
                          :keys [instances]}]
                      {(->> datomic-system
                            ((juxt (comp symbol :topology)
                                   :name
                                   ;:storage-cft-version
                                   )))
                       (->> instances
                            (mapv (fn [compute-group]
                                    (->> compute-group
                                         ((juxt (comp keyword :status)
                                                :group-name
                                                (comp symbol :instance-id)
                                                ;:group-cft-version
                                                ;:group-cloud-version
                                                )))))
                            (sort))})))
         time))
```

The output looks something like this:
```clojure
{[solo "datomic-storage"] ([:running "access-gateway" i-0772da0de2ec0xxxx]
                           [:running "datomic-compute" i-066336431a515xxxx]),
 [production "xxx-prod-datomic"] ([:running "access-gateway" i-08e7a946d60c9xxxx]
                                          [:running "xxxx-prod-datomic-primary-compute" i-042fd969ecb74xxxx]
                                          [:running "xxxx-prod-datomic-primary-compute" i-0537d37fb88efxxxx]
                                          [:running "prod-xxxx-saas" i-00c3425415069xxxx])}

"Elapsed time: 1289.453993 msecs"
```

**Comment by borkdude** [comment]
I don't know what this library entails, there might be some other stuff that doesn't work with babashka, but for spec you can now include `spartan.spec` and it will define a `clojure.spec.alpha` namespace for you that is compatible with babashka (without having it built in).

https://github.com/borkdude/spartan.spec

**Comment by borkdude** [comment]
See https://github.com/babashka/babashka/issues/737 for a discussion around adding malli.

**Comment by wilkerlucio** [comment]
I think would be great to have spec for compatibility reason. Given spec comes with Clojure, and some libraries use that. Even if it was a noop spec, would be better than now, because currently, if a library uses spec, it can't be used in Babashka.

I personally have used a lot of spec for the regex feature, to parse use commands on macros. But sadly I can't use these libraries with Babashka.

**Comment by borkdude** [comment]
@wilkerlucio How do you feel about adding spec.alpha now and removing it for spec2 later?

**Comment by wilkerlucio** [comment]
I feel if something gets add, better to keep it to avoid the "I bumped and now things don't work anymore" problem. If the idea is to remove later, I would rather not add.

**Comment by borkdude** [comment]
I revisited this issue and found out that clojure.spec's source needs only a few light changes to make it compatible with babashka. So the answer to this issue will be: use https://github.com/babashka/spec.alpha as a dependency. We will wait for spec2 non-alpha to come out and this will be built-in (for optimal performance).
If you are interested, please try the clojure.spec fork out with babashka from master (you can download binaries from the builds or ask me for a link for your OS).  Everything is supposed to work. All tests are passing. Also tested with several libraries like coax, orchestra, expound.

**Comment by borkdude** [comment]
Recommended solution for clojure.spec.alpha: https://github.com/babashka/spec.alpha
Will revisit this once spec2 non-alpha comes out!
