### ISSUE TITLE
Add tests for raynes/fs lib and add to libraries.md

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#602]
This works:

``` 
export BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {clj-commons/fs {:mvn/version "RELEASE"}}}')
$ clojure -M:bb-local -e "(require '[me.raynes.fs :as fs]) (fs/glob \"*.md\")"
(#object[java.io.File 0x78f2bb1b "/Users/borkdude/Dropbox/dev/clojure/babashka/CHANGELOG.md"] #object[java.io.File 0x651c826c "/Users/borkdude/Dropbox/dev/clojure/babashka/README.md"] #object[java.io.File 0x10323056 "/Users/borkdude/Dropbox/dev/clojure/babashka/CONTRIBUTING.md"])
``` 

but it would be nice if we added some tests to lib-tests.

Also we need to add it to the libraries.md page.

- [x] Fix #601 
- [ ] A good test would be to check if the Java 7 conditional is executed:

``` 
$ clojure -A:bb-local -cp $(lein classpath):src:test -e "(require '[me.raynes.fs :as fs]) (contains? (ns-publics 'me.raynes.fs) 'directory?)"
``` 

- [ ] Test if the Coercions impl is working

**Comment by cldwalker** [comment]
Is this still worth doing when bb can require fs.clj but not https://github.com/Raynes/fs/blob/master/src/me/raynes/fs/compression.clj because of the java classes it doesn't have?

**Comment by borkdude** [comment]
I think so yes, since `fs.clj` is still being used in several libs so having compatibility with it is good.
