### ISSUE TITLE
babashka.fs namespace

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#634]
This namespace contains some utility functions for dealing with files:

- [glob](https://github.com/borkdude/babashka/blob/ed263b1089c909cd7eb4110dc23d0452e1a2c895/test-resources/babashka/glob.clj#L3), the linked implementation could be faster using file visitor or alike

Probably inspired by or a babashka vendored fork of https://github.com/clj-commons/fs.

Also see: 
- https://github.com/russmatney/ralphie/blob/master/src/ralphie/fs.clj
- https://github.com/nate/fs/blob/master/src/nate/fs.clj
- https://github.com/zcaudate/hara/blob/master/src/hara/io/file.clj

Some useful feedback here: https://github.com/borkdude/babashka/issues/457

**Comment by michaelwhitford** [comment]
I would be very happy if everything from clj-commons/fs was included in bb by default. I find myself wanting these types of functions all the time in my scripting. Especially filesystem path functions, I use format strings entirely too often to resolve paths.

**Comment by borkdude** [comment]
@michaelwhitford Can you explain which function(s)s (regarding paths) you are using mostly? To create paths I usually use `(.getPath (io/file "foo" "bar")` which returns "foo/bar" or "foo\\bar" depending on the OS.

**Comment by borkdude** [comment]
Work in progress at https://github.com/babashka/nio

**Comment by borkdude** [comment]
Babashka.fs is included in bb 0.2.9.
