### ISSUE TITLE
Babaska not working with malli

### ISSUE THREAD

**Issue by lucywang000** [babashka/babashka#647]
See the details on the malli issue tracker https://github.com/metosin/malli/issues/302

**Comment by borkdude** [comment]
@lucywang000 Thanks for trying! 

Maybe you could make issues for individual smaller issues that could be addressed one by one. For each change you did do the malli source code and one for the protocol nullpointer. I'd be happy to look into those.

Alternatively you could look at https://github.com/green-coder/minimallist which runs with babashka.

Lastly, could I invite you to fill in the babashka survey if you haven't done so already, to learn more about your usage of babashka? 

https://nl.surveymonkey.com/r/H2HK3RC

**Comment by borkdude** [comment]
The protocol error might be related to this part, not sure: https://github.com/lucywang000/malli/blob/1f4684060b3cde90ae724178a14b33af2f5a04ab/src/malli/core.cljc#L227-L241

**Comment by ikitommi** [comment]
The protocol cache was added few days ago. Happy to take in changes to make malli work with bb.

**Comment by borkdude** [comment]
@ikitommi Likewise happy to fix issues in bb that should normally work in Clojure. Isolated small repros welcome.

**Comment by borkdude** [comment]
@lucywang000 There is an issue here with a proposal to add malli to babashka:

https://github.com/babashka/babashka/issues/737

**Comment by borkdude** [comment]
A PR to add compatibility to bb for malli: https://github.com/metosin/malli/pull/718
