### ISSUE TITLE
Merge reitit-feature branch to master

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#681]
I need to look deeper into this before merging to master but glossing over it, it seems @kloimhardt did a great job:

Branch: https://github.com/borkdude/babashka/tree/reitit-feature
Diff: https://github.com/borkdude/babashka/compare/reitit-feature

TODO/questions:

- [ ] why is feature-reitit/reitit/trie.cljc a separate file, does it contain a patch - if so which one?

**Comment by kloimhardt** [comment]
Ring and Reitit needed to be patched for Graal. I'd like to mention on thought: it would be ideal to have official Graal compilable versions of those two important libraries.

**Comment by borkdude** [comment]
@kloimhardt If possible, I think it would be nice to merge back certain things. The metosin people are likely to accept patches that will benefit GraalVM native-image compilation (cc @ikitommi).

One question so far: why is feature-reitit/reitit/trie.cljc a separate file, does it contain a patch - if so which one?

**Comment by borkdude** [comment]
Another question: can you identify the other patches? I know there is one for resource in ring - maybe it's possible to do this with alter-var-root instead as well, without copying the entire file?

**Comment by kloimhardt** [comment]
I will write down exactly what the patches are (after re-understanding what I did). I can only work on this in two weeks time as it stands now. I would in any case be very happy if this PR is more seen to start a process and finally gets merged without my reitit/ring patches even if this takes some time.

**Comment by borkdude** [comment]
@kloimhardt Agreed and no problem.

**Comment by ikitommi** [comment]
PRs welcome to reitit to make it work with GraalVM.

**Comment by borkdude** [comment]
Will close this for lack of activity, feel free to request re-opening the ticket.
