### ISSUE TITLE
Support downloading pod if it doesn't exist on the system

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#690]
Playing around with a pod resolver (downloads a pod if it's not downloaded yet). Example:

```
(require '[babashka.pods :as pods])

;; this will download the hsqldb pod, takes a while the first time, fast the second time
(pods/load-pod 'org.babashka/pod-babashka-hsqldb)

(require '[pod.babashka.hsqldb :as db])

(def db "jdbc:hsqldb:mem:testdb;sql.syntax_mys=true")

(db/execute! db ["create table foo ( foo int );"])

(db/execute! db ["insert into foo values (1, 2, 3);"])

(db/execute! db ["select * from foo;"])
```

The above example should work with:
- linux version: https://13945-201467090-gh.circle-artifacts.com/0/release/babashka-0.2.6-SNAPSHOT-linux-amd64.zip
- macos version: https://13944-201467090-gh.circle-artifacts.com/0/release/babashka-0.2.6-SNAPSHOT-macos-amd64.zip
(windows TODO, should work, but the pod doesn't have a Windows version)

Ideas: 

- The metadata for downloading a pod could be hosted in the pod repository itself (instead of having a central repo where I have to take PRs)? E.g. `(load-pods "https://github.com/babashka/sql-pods/meta/postgresql")` will download `https://raw.githubusercontent.com/babashka/sql-pods/master/meta/postgresql.0.0.1.edn` if it isn't available yet in the local cache and then follows instructions from that edn file to download the binary.
 Counter-argument: we could keep the pod repo format private for a while or in a central place (in a git repo in the babashka org) so we can change things still.
 *Decision*: we will have one central repo: https://github.com/babashka/pod-manifests
 
- Maybe one should also be able to run from a local manifest, so you can test it before committing it... `(load-pod 'justone/brisk {:manifest "foo.edn"})` or something.

**Comment by lispyclouds** [comment]
@borkdude this is addressed now right?

**Comment by borkdude** [comment]
Yep! https://github.com/babashka/pod-registry
