### ISSUE TITLE
git pod 

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#693]
Based on https://github.com/go-git/go-git we could implement a git pod for idiomatic clojure usage. This wouldn't even require you to install git.

**Comment by lispyclouds** [comment]
The common git operations can be carried out with the use of (babashka.process)[https://github.com/babashka/process] like this example which takes in a path containing `n` git repos and performs a rebasing pull on all of them in parallel:

```clojure
(require '[babashka.process :as p]
         '[clojure.java.io :as io])

(def default-root ".")

(defn list-dirs
  [root]
  (filter #(.isDirectory %) (.listFiles (io/file root))))

(defn git-pull
  [dir]
  (println (str "Pulling: " dir))
  (p/process ["git" "-C" dir "pull" "--rebase"]))

(when (= *file* (System/getProperty "babashka.file"))
  (let [root  (get *command-line-args* 0 default-root)
        pulls (->> root
                   list-dirs
                   (map git-pull)
                   doall)]
    (doseq [pull pulls]
      (-> pull
          p/check
          :out
          slurp
          print))))
```

This pod can be made if the need really arises for more intimate git operations. What say @borkdude ?

**Comment by lispyclouds** [comment]
Also in real world tests, forking git processes via bb seems to be faster than forking via go
