### ISSUE TITLE
Reader parsing of `#()` combined with `#_` behaves differently than in Clojure and ClojureScript

### ISSUE THREAD

**Issue by didibus** [babashka/babashka#702]
**version**

Babashka v0.2.6 REPL.

**platform**

OpenSuse Linux running inside Windows WSL2

**problem**

On Clojure and ClojureScript, the following code:

```
(mapv #(rand-int 10 #_%) (range 100))
```

Returns:

```
[2 5 2 4 2 2 2 6 7 8 5 9 5 8 2 0 7 8 6 1 0 8 7 6 0 0 8 6 4 9 1 0 6 9 7 2 9 3 3 0 8 3 2 1 5 6 9 9 9 6 2 7 6 1 7 3 2 5 1 5 5 2 8 2 5 4 9 1 7 5 0 8 0 6 0 4 8 0 9 7 4 8 7 2 9 9 9 8 0 3 3 1 3 6 9 7 1 6 4 9]
```

But in Babashka it errors with:

```
clojure.lang.ArityException: Wrong number of args (1) passed to: mapv [at <repl>:1:1]
```

**repro**

At the command line:

```
> babashka
user=> (mapv #(rand-int 10 #_%) (range 100))
```

**expected behavior**

I expect it to work just like in Clojure and ClojureScript. Also to remark:

```
(mapv #(rand-int 10 #_%1 #_%2) (range 100) (range 100))
```

Also works in Clojure and ClojureScript.

**Comment by borkdude** [comment]
According to @puredanger this is undefined behavior:

https://twitter.com/puredanger/status/1280854707980972036

![Screenshot 2021-01-05 at 09 10 18](https://user-images.githubusercontent.com/284934/103621460-88af8f80-4f35-11eb-8cea-5631650528d7.png)

**Comment by borkdude** [comment]
From slack:

```
7m
alexmiller  I do not believe this is behavior you should rely on. We’ve even looked at changes to the discard reader recently re tagged literals or reader conditionals and it’s not clear to me that things would still work this way after those changes. So, please don’t do this.

6m
alexmiller  It’s so much clearer to just use fn
```

So I won't explicitly support this, but I did find an issue in the parser that allows nested anonymous function literals:

```
$ bb -e '(#(+ % (#(+ % 1) 2)) 10)'
13
```

This probably violates what people expect, namely to throw with a warning that nested fn-literals aren't supported.

**Comment by didibus** [comment]
Like we discussed on Slack, I think this is actually more intuitive behavior, and its too bad Clojure/Script actually allow this, but it does seem to be accidental, and the official stance is not to rely on this behavior, as it is considered undefined. So feel free to close this issue whenever you want.
