### ISSUE TITLE
Revisit core.async/go macro with tools.analyzer on graalvm

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#703]
We might be able to get the go macro working now that tools.analyzer seems compatible with graalvm. Liz apparently uses this in GraalVM: https://github.com/dundalek/liz.

Things to watch: 

- Increase in binary size. It may not be worth it. We can put core async (or only the go macro) behind a feature flag.
- Maybe use tools.analyzer as a pod?

**Comment by borkdude** [comment]
This is now solved via virtual threads

**Comment by jianghoy** [comment]
Sorry what does the comment mean? Does it mean that now bb uses virtual thread to support go macro? Or does it mean it can be solved via virtual thread but no plans yet?

**Comment by borkdude** [comment]
@jianghoy The `go` macro in bb uses virtual threads now. You shouldn't notice any difference though.
