### ISSUE TITLE
shell command result piped into a babashka repl

### ISSUE THREAD

**Issue by csandeep** [babashka/babashka#706]
Piping a shell command output to babashka and dropping into a repl would greatly help in developing scripts. Eg:

``` 
$ ls | bb -i --repl
```

currently evaluates the result of `ls` in repl. However if we had access to `*input*` and a repl then we can develop a script interactively.

**Comment by borkdude** [comment]
@csandeep I don't think this is possible because it requires you to switch the source of the stdin stream of the babashka process after having read the pipe.

What you can do is write the output of the pipe to a file and then read that input in a REPL from the file.

**Comment by csandeep** [comment]
Thank you @borkdude , going to close this ticket.

PS: thank you for creating this tool, its super helpful.
