### ISSUE TITLE
Upgrade to GraalVM 21.0.0

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#712]
Extra used classes which can potentially be avoided:

< java.awt.AWTError
9113,9114d9008
< java.awt.Toolkit$2
< java.awt.Toolkit$DesktopPropertyChangeSupport

< java.io.ObjectInputFilter$Config$Global
< java.io.ObjectInputFilter$Config$Global$$Lambda$4dd9853c377fdaf2983784fe9ca6a7d91aa08aba
< java.io.ObjectInputFilter$Config$Global$$Lambda$6ed619c85962e033376c3c62b14925013f517d3c
< java.io.ObjectInputFilter$Config$Global$$Lambda$a2157b605cabcfb5dc530ff4568b242ff4bf47da
< java.io.ObjectInputFilter$Config$Global$$Lambda$bd410e2d4be0a162fbf8797dcb2f091f7ab442f2
< java.io.ObjectInputFilter$Config$Global$$Lambda$cc04eb241424577dfc6f01dea54fc6f49ba6a6bd
9197,9198d9078
< java.io.ObjectInputStream$FieldValues
< java.io.ObjectInputStream$FilterValues
9200d9079
< java.io.ObjectInputStream$HandleTable$HandleList
9203,9218d9081
< java.io.ObjectInputStream$ValidationList$1
< java.io.ObjectStreamClass
< java.io.ObjectStreamClass$$Lambda$961d1c2f735b794177da1c3eadaac7a9db3a36dc
< java.io.ObjectStreamClass$1
< java.io.ObjectStreamClass$2
< java.io.ObjectStreamClass$3
< java.io.ObjectStreamClass$4
< java.io.ObjectStreamClass$5
< java.io.ObjectStreamClass$ClassDataSlot
< java.io.ObjectStreamClass$EntryFuture
< java.io.ObjectStreamClass$EntryFuture$1
< java.io.ObjectStreamClass$ExceptionInfo
< java.io.ObjectStreamClass$FieldReflector
< java.io.ObjectStreamClass$FieldReflectorKey
< java.io.ObjectStreamClass$MemberSignature
< java.io.ObjectStreamClass$WeakClassKey

**Comment by borkdude** [comment]
@sh0hei Before merging your PR, I want to look if we can avoid including the above classes, since they take up 5MB of extra binary space.

**Comment by borkdude** [comment]
@sh0hei Take a look at the Java classes in the resources folder, these are used to cut off classes. And then check the output using `"-H:+PrintAnalysisCallTree"`. The classes should not show up anymore after compilation in the used_classes file.

**Comment by borkdude** [comment]
@sh0hei Alternatively you could also use the new dashboard feature:

https://www.graalvm.org/docs/tools/dashboard/?ojr=help%3Btopic%3Dgetting-started.md

I haven't used it myself yet, but this would be a nice tool to get an idea of what is included.

**Comment by sh0hei** [comment]
Many thanks to @borkdude for their help.
I'll try it 👍

**Comment by borkdude** [comment]
Dump from GraalVM slack:

@Ziyi So every native-image gets ObjectStreamClass no matter what?

Ziyi  12 hours ago
I don't think every native image requires it. If the native image has nothing to do with serialization, it's not necessary to loop ObjectStreamClass in.

Michiel Borkent Today at 12:47 PM
If the analysis graph was available in JSON, it would also be easier to build a tool around this
9 replies

David Kozak  2 hours ago
DashboardJson option will change the output format to json.

David Kozak  2 hours ago
All dashboard relevant options are defined here - https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/dashboard/DashboardOptions.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/dashboard/DashboardOptions.java
/*
 * Copyright (c) 2020, 2020, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
Show more
<https://github.com/oracle/graal|oracle/graal>oracle/graal | Added by GitHub

Kirill Prazdnikov  2 hours ago
Can I make svm_heap as heapdump to analyze in VisualVM?

Oleg Šelajev  2 hours ago
that would be interesting I don't think it works currently, maybe create an issue for this?

Kirill Prazdnikov  2 hours ago
https://github.com/oracle/graal/issues/3158
kirillpkirillp
#3158 Make svm_heap as heapdump to analyze in VisualVM
It would be useful to make svm_heap as heap dump, so we can open it in VisualVM and analyze.  
Same way we can create a dashboard file.
Labels
feature
<https://github.com/oracle/graal|oracle/graal>oracle/graal | Today at 1:28 PM | Added by GitHub

Oleg Šelajev  1 hour ago
thanks!

Michiel Borkent  2 minutes ago
I was referring to
"-H:+PrintAnalysisCallTree"
is the same output available in the dashboard file?

Michiel Borkent  < 1 minute ago
Sorry I missed this message:
https://graalvm.slack.com/archives/CN9KSFB40/p1611662486028000?thread_ts=1611661605.027000&cid=CN9KSFB40

David Kozak
You can actually visualise the points-to graph in the dashboard. You just have to “click your way through” either the code or heap layout until you arrive at the method you are interested in. Once you click on it again, a points-to exploration window opens. Now you can traverse the points-to graph and see what gets pulled in and why. Quick warning - the user experience might not be the best. Please let me know what you think about it, because I am actually considering to do some improvements in this area. If you have specific use cases in mind that are not handled well by the current tooling, please let me know.
From a thread in #native-image | Today at 1:01 PM | View reply

Michiel Borkent  < 1 minute ago
I'll try that
