### ISSUE TITLE
Incorrect function call reported as source of error

### ISSUE THREAD

**Issue by judepayne** [babashka/babashka#719]
**version**
0.2.7

**platform**
MacOS

**problem**
babashka reports the incorrect function call as the source of the error. 

**repro**
file `msg.clj`:

    #!/usr/local/bin/bb

    (defn echo-msg [msg]
      (println msg))

    (defn main []
      (echo-msg))  ;; called with the wrong arity

    (main)
now execute the file:
`./msg.clj`
This error message is reported:

    ----- Error --------------------------------------------------------------------
    Type:     clojure.lang.ArityException
    Message:  Wrong number of args (0) passed to: main ;; wrong function cited
    Location: /Users/jude/Dropbox/Projects/clojure/control-maths/lambdas/./msg.clj:9:3

    ----- Context ------------------------------------------------------------------
     5:   (println msg))
     6: 
     7: 
     8: (defn main []
     9:   (echo-msg))  ;; called with the wrong arity
          ^--- Wrong number of args (0) passed to: main  ;; the position of the error is right but the wrong function is cited
    10: 
    11: 
    12: (main)

**expected behavior**
If I put the same code into a clojure file, I get this error message:

    Execution error (ArityException) at my-ns.core/main (core.clj:331).
    Wrong number of args (0) passed to: my-ns.core/echo-msg

The function call that is the source of the error is correctly cited.
I have seen this with other errors, not just arity errors. Made debugging a bit tricky!

**Comment by borkdude** [comment]
Thanks for reporting.

**Comment by borkdude** [comment]
Fixed with https://github.com/babashka/babashka/commit/34777e3d7ab22ad6946c2c91fee3077de4f0748f

**Comment by judepayne** [comment]
@borkdude Great. How can I get a build to test? I tried cloning and running the scripts but had a few problems with Java versions. Wait for 0.2.9?

**Comment by borkdude** [comment]
@judepayne Each commit has a green tick-mark on the left (of red if it failed):

![Screenshot 2021-01-27 at 22 42 26](https://user-images.githubusercontent.com/284934/106058064-07d95300-60f1-11eb-8291-a4e455a08149.png)

When you click on that, you will see a list of builds:

![Screenshot 2021-01-27 at 22 43 42](https://user-images.githubusercontent.com/284934/106058143-23445e00-60f1-11eb-8ec7-96120f4c6a06.png)

Select the build for your OS and then go to the artifacts tab. There you can download a binary for that commit.

For macOS that is: https://14802-201467090-gh.circle-artifacts.com/0/release/babashka-0.2.9-SNAPSHOT-macos-amd64.zip

**Comment by judepayne** [comment]
Thanks. perfect now
