### ISSUE TITLE
--eject / describe deps

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#720]
Experimental idea:

bb --eject will create a deps.edn (or project.clj?) with all libraries available in babashka, so you can run it with the JVM.

Optionally also a native image configuration, so you can compile your script natively using GraalVM.

**Comment by borkdude** [comment]
See #733. `bb eject` could print a deps.edn to stdout which could also be used by LSP to calculate the classpath. It would then merge in the paths and deps from bb.edn as well.

**Comment by ericdallo** [comment]
Looks valid to make #733 work on clojure-lsp

**Comment by thiagokokada** [comment]
This seems to be useful, in an internal project that I am working I provide a `project.clj` that interop with `bb.edn` using `lein-tools-deps`. Since we mostly use `leiningen` internally, this makes setting up a development environment easy (just do a `lein repl` like in any other project).

This is an example:

```clojure
(defproject some-project "0.1.0-SNAPSHOT"
  :plugins [[lein-tools-deps "0.4.5"]]
  :middleware [lein-tools-deps.plugin/resolve-dependencies-with-deps-edn]
  ;; Dependencies that are builtin in Babashka, only added here to interop
  ;; with leiningen
  ;; To add a new dependency to the project, add it to the bb.edn instead
  :dependencies [[org.clojure/clojure "1.11.0-alpha1"]
                 [babashka/fs "0.0.5"]]
  :lein-tools-deps/config {:config-files [:install :user :project "bb.edn"]})
```

The disadvantage of the above approach is that I need to manually track which versions of the dependencies are being used in Babashka, so we don't have strange errors.

So yeah, having something like `bb --eject` would be useful.

**Comment by borkdude** [comment]
Now that we have subcommands, perhaps we can just do:

```
bb describe --deps
```
which will spit out the built-in deps followed by the deps of the `bb.edn`. We can add more subcommands to `describe` for other things like this. The general idea is that it can output EDN with some bespoke info about bb itself and/or the project.

**Comment by ericdallo** [comment]
@borkdude for clojure-lsp it would be nice to have a option to output the classpath separated by `:` like every tool has that (clj cli, lein, shadow-cljs), I think it's a standard on how to print the classpath.

It could be something like `bb describe deps --classpath`?

**Comment by borkdude** [comment]
@ericdallo In that case `describe` might not really be the best fit. 

The built-in deps aren't resolved via maven or git deps, they are just built-into babashka. So bb doesn't even know how to make a classpath for those libraries. It _could_ do that by invoking clojure -Spath on those libraries, but I don't think that is the job of bb. So I think the best bb could do is to output a list of libraries and their mvn versions or git shas and then let some other tool do something with that.

**Comment by borkdude** [comment]
Perhaps just making a bespoke script that pulls down the latest deps.edn (or even by version tag) from the bb repo, calculates the classpath and hooking that up in the `:classpath-cmd` of LSP is the best solution.

**Comment by ericdallo** [comment]
Hum, I don't get it why bb can't say what built-in does it has, I don't know why other tool would need to scan bb code just to know the built-in libs if bb itself could read from the deps.edn somewhere and show that later in a command

**Comment by borkdude** [comment]
> Hum, I don't get it why bb can't say what built-in does it has

It can, but this is not the same as producing a classpath. A classpath is a list of relative source paths and a list of absolute paths into a maven repo. Babashka cannot tell you where e.g. "cheshire" is in your maven repo, since it doesn't really need it to be there.
