### ISSUE TITLE
Support for Github Action: Install Babashka

### ISSUE THREAD

**Issue by ericdallo** [babashka/babashka#723]
I need to setup babashka in `clojure-lsp` Github Actions to run the integration tests, I need to setup for Linux, Windows and Mac, and I realized that I would need to manually specify which binary I want to download from GIthub release, it'd be really helpful to have a Github Action "Install Babashka" where checks the OS and installs it to the PATH automatically, similar to [Setup Clojure](https://github.com/marketplace/actions/setup-clojure)

It'd be even better to have babashka in [Setup Clojure](https://github.com/marketplace/actions/setup-clojure) by an optional flag :)

**Comment by ericdallo** [comment]
Also, it seems the [installer script](https://github.com/babashka/babashka#installer-script) is only supported for unix OSs, for Windows I'd need to manually download from the release, right?

**Comment by borkdude** [comment]
There is one here: https://github.com/turtlequeue/setup-babashka

You usually can find these things here:

https://github.com/babashka/babashka/blob/master/doc/projects.md

**Comment by ericdallo** [comment]
Thank you!
