### ISSUE TITLE
Don't print REPL output in non-interactive run

### ISSUE THREAD

**Issue by bard** [babashka/babashka#726]
**Is your feature request related to a problem? Please describe.**

I expected bb to behave as other interpreters I know, and execute a script passed via stdin quietly. The script does get executed, but with REPL messages interspersed:

```sh
/tmp$ cat test.bb
(println "hello")
/tmp$ bb <test.bb
Babashka v0.2.8 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> hello
nil
```

**Describe the solution you'd like**

No REPL output would be printed by default in a non-interactive run.

**Describe alternatives you've considered**

I tried `--repl=false` and `--repl=off`, hoping that might silence the output.

**Additional context**

```sh
/tmp$ cat test.rb
puts "hello"
/tmp$ ruby <test.rb
hello
/tmp$ cat test.py
print("hello")
/tmp$ python <test.py
hello
```

**Comment by borkdude** [comment]
@bard If you want to execute the script without REPL output, just invoke it like: `bb test.bb`. 
Even `clojure` shows REPL output when invoking a script on stdin:
```
$ clojure < /tmp/foo.clj
Clojure 1.10.2
user=> :hello
nil
user=> :bye
nil
```

**Comment by bard** [comment]
@borkdude thanks, I know about `bb FILE` and `bb -f FILE`, but in this case I don't have a file, only an output stream. (Context: I'm writing an Emacs extension pipes directly to an interpreter.) 

I just tried a workaround and it appears to do the trick.

```sh
/tmp$ bb /dev/stdin <test.bb  
hello
```

The above is enough for me so I'll close this.

**Comment by borkdude** [comment]
@bard What you can also do, and which is more cross-platform maybe:

```
$ bb -e '(load-string (slurp *in*))' <<< '(+ 1 2 3)'
6
```
