### ISSUE TITLE
(if false 10 20) returns nil

### ISSUE THREAD

**Issue by thedeemon** [babashka/babashka#727]
**version**

babashka v0.2.9

**platform**

Windows 10 64-bit, bb binary taken from github releases

**problem**

`(if false 10 20)` returns `nil` instead of 20. Meanwhile `(if (even? 1) 10 20)` returns 20 as expected.

**repro**

`(if false 10 20)`

**expected behavior**

I expected it to return 20.

**Comment by borkdude** [comment]
@thedeemon Thanks for the report. This might be because of an unfortunate optimization. Will fix.

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/sci/issues/529. Will release a new bb as this is pretty critical.

**Comment by thedeemon** [comment]
Amazing speed! Thank you.

**Comment by borkdude** [comment]
Released.
