### ISSUE TITLE
[BUG]: `split-paths` not available on babashka.fs using bb 2.0.9 and 2.0.10

### ISSUE THREAD

**Issue by eccentric-j** [babashka/babashka#728]
## Description

I'm interested in using the `split-paths` function described in the docs, but bb says the function does not exist.

https://babashka.org/fs/babashka.fs.html#var-split-paths

## Reproduction

1. Start babashka repl `bb`
2. Run the following`(require '[babashka.fs :refer [split-paths]])`

## Expected

Babashka imports the split-paths method and I can use it like the following:

```clojure
(requuire '[babashka.fs :as fs])
(fs/split-paths "a/b/c")
;; =>
["a" "b" "c"]
```

## Actual

I get an error like the following:

```
user=> (require '[babashka.fs :refer [split-paths]])
java.lang.Exception: split-paths does not exist
```

## Workarounds

```clojure
(defn split-paths
  [path-str]
  (clojure.string/split path-str (re-pattern fs/file-separator)))
```

## Environment

| Key            | value               |
| -------------- | ------------------- |
| OS             | OS X 11.2 (Big Sur) |
| bb versions    | babashka v0.2.10    |
|                | babashka v0.2.09    |
| Installed From | Install script      |

**Comment by borkdude** [comment]
@eccentric-j The `split-paths` function doesn't do what you think it does. It will split something like a classpath "foo:bar" into multiple files. To get all the components of a path, you can use `fs/components`:

``` 
$ bb -e '(map str (fs/components (fs/real-path ".")))'
("Users" "borkdude" "Dropbox" "dev" "clojure" "babashka")
```

**Comment by borkdude** [comment]
Nonetheless I now added `fs/split-paths` to bb master as well.

**Comment by eccentric-j** [comment]
😳My mistake. Thanks for clarifying and adding it back anyway.

**Comment by borkdude** [comment]
@eccentric-j A fun thing I learned while developing this library, you can call `seq` on `java.nio.file.Path`: `(seq (fs/real-path "."))`:

```
$ bb -e '(map str (seq (fs/real-path ".")))'
("private" "tmp" "condp-hook")
``` 

The `components` function basically uses `seq`.
