### ISSUE TITLE
LSP support for babashka scripts

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#733]
Current solution:

1) Install below script in `/Users/you/script/bbcp.clj`:

``` clojure
(require '[babashka.curl :as curl]
         '[babashka.deps :as deps]
         '[clojure.edn :as edn])

(def deps-edn (:body (curl/get "https://raw.githubusercontent.com/babashka/babashka/master/deps.edn")))

(let [deps (edn/read-string deps-edn)
      deps (update deps :deps assoc
                   'babashka/fs {:mvn/version "0.0.5"}
                   'babashka/babashka.curl {:mvn/version "0.0.3"})
      deps (update deps :deps dissoc 'borkdude/sci)
      deps {:deps (:deps deps)}
      ;; _ (clojure.pprint/pprint deps)
      cp (with-out-str (deps/clojure ["-Spath" "-Sdeps" deps]))]
  (println cp))
```

2) Configure .lsp by inserting this in `.lsp/config.edn`:

```
{:project-specs [{:project-path "bb.edn"
                  :classpath-cmd ["bb" "/Users/you/script/bbcp.clj"]}]}
```

3) In your bb project / script dir, create a `bb.edn` file (with a minimum an empty map)

4) Now you should be able to get Clojure-LSP features in bb scripts

-----

Original issue:

@ericdallo: what would be needed for clojure-lsp to get auto-complete working for libs built into babashka?

These are basically the deps that are included:

``` 
{:deps {org.clojure/clojure {:mvn/version "1.10.2"},
        babashka/babasha.curl {:local/root "babashka.curl"}
        babashka/fs {:local/root "fs"}
        org.clojure/core.async {:mvn/version "1.3.610"},
        org.clojure/tools.cli {:mvn/version "1.0.194"},
        org.clojure/data.csv {:mvn/version "1.0.0"},
        cheshire/cheshire {:mvn/version "5.10.0"}
        org.clojure/data.xml {:mvn/version "0.2.0-alpha6"}
        clj-commons/clj-yaml {:mvn/version "0.7.106"}
        com.cognitect/transit-clj {:mvn/version "1.0.324"}
        org.clojure/test.check {:mvn/version "1.1.0"}
        nrepl/bencode {:mvn/version "1.1.0"}
        http-kit/http-kit {:mvn/version "2.5.1"}
        org.clojure/core.match {:mvn/version "1.0.0"}
        hiccup/hiccup {:mvn/version "2.0.0-alpha2"}}}
 ```

**Comment by ericdallo** [comment]
ATM, clojure-lsp get a classpath string from common dependency managers [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/crawler.clj#L54-L61) like `clj -Spath`, `lein deps`, if babashka provide some kind of command that return the deps/classpath in the same way/following the same output standard of a classpath (string with `:`), that would fit perfect :)

**Comment by ericdallo** [comment]
Also, ATM, we just run those commands if a specific file exists, like `deps.edn` or `project.clj`, but for babashka we wouldn't have that, so probably we could do some workaround to load the classpath scan if we open a file with a babashka header or something like that

**Comment by ericdallo** [comment]
Still would not be easy, as we only persist the analysis if it's a project with root/not a single file, it'd be necessary to think in some workaround for that too

**Comment by borkdude** [comment]
@ericdallo I think it would be better if babashka had a command to spit out a deps.edn file (to stdout), which then was used by clojure-lsp to calc the classpath. 

This would also serve another purpose: people could work on the normal JVM to develop their scripts and then run it with babashka. 

Something like:

```
bb --deps-edn <optional-file, else stdout>
```

so in lsp you could then use this output as if there was a deps.edn in the root of the project. I think we would also need to add the current dir to the classpath since else the script itself would not be part of it?

Let me know what you think.

**Comment by ericdallo** [comment]
I think we could do some woraround to do that, the issue is that clojure-lsp just delegate the classpath find to the tools following the classpath standard, like `clj -Spath` => `/home/user/a.clj:/home/user/b.clj`, so we don't manipulate a deps.edn or parse anything like that, that's why I suggested some kind of `bb --classpath <optional-file, else stdout>`. I think the classpath command would help other JVM libs that may need to know the whole babashka classpath, WDYT?

**Comment by borkdude** [comment]
Maybe clojure-lsp can have a pre-configured classpath / deps.edn that you can choose from a menu? So you can have a preset: babashka which you can activate manually?

**Comment by borkdude** [comment]
@ericdallo @snoe I have a project here: https://github.com/borkdude/deps-infer which can infer dependencies from random code by looking at your .m2 directory. 

E.g. a random script in my /tmp dir:

``` clojure
(ns app.core
  {:clj-kondo/config '{:linters {:unresolved-symbol {:exclude [(slingshot.slingshot/try+)]}}}}
  (:require [slingshot.slingshot]))

(slingshot.slingshot/try+
 x
 (:foo x))
```

Infer deps:

```
$ clojure -M:deps-infer --analyze /tmp/dude.clj
slingshot/slingshot {:mvn/version "0.12.2"}
```

This approach could be used to automatically infer deps. Maybe using a setting in `.lsp/config.edn`.

**Comment by ericdallo** [comment]
Just linking our discussion that may fix this issue: https://github.com/babashka/babashka/discussions/757#discussioncomment-513395

**Comment by borkdude** [comment]
We could possible add this information to the output of `bb describe`.

**Comment by ericdallo** [comment]
`bb describe` seems to print information about the `bb` itself, right?
I think a `bb deps` or `bb classpath` would fit better?

**Comment by borkdude** [comment]
bb describe spits out an EDN map. we could add a `:deps` entry to this, so it describes the versions / coordinates of the deps bb has bundled. This would also be about itself, but could also be used by LSP.

**Comment by ericdallo** [comment]
yes, we could use that indeed, but won't be cases of user adds custom deps to babashka via the bb.edn or something?
I mean, the `:deps` inside `bb describe` would always be the same or `bb` would compute it and just give it ready to LSP including the user extra deps?

**Comment by borkdude** [comment]
That's a good point.

**Comment by borkdude** [comment]
@ericdallo To continue our conversation in #720,

I made this script:

bbcp.clj
```
(require '[babashka.curl :as curl]
         '[babashka.deps :as deps]
         '[clojure.edn :as edn])

(def deps-edn (:body (curl/get "https://raw.githubusercontent.com/babashka/babashka/master/deps.edn")))

(let [deps (edn/read-string deps-edn)
      deps (update deps :deps assoc
                   'babashka/fs {:mvn/version "0.0.5"}
                   'babashka/babashka.curl {:mvn/version "0.0.3"})
      deps (update deps :deps dissoc 'borkdude/sci)
      deps {:deps (:deps deps)}
      ;; _ (clojure.pprint/pprint deps)
      cp (with-out-str (deps/clojure ["-Spath" "-Sdeps" deps]))]
  (println cp))
```

When invoking that, it prints a large classpath.

But when I add it to a `.lsp/config.edn` like this:

```
{:project-specs [{:classpath-cmd ["bb" "/tmp/bbcp.clj"]}]}
``` 

it doesn't seem to be picked up when I restart the lsp workspace...

**Comment by ericdallo** [comment]
@borkdude you need to specify a `:project-path` to clojure-lsp use the classpath-cmd if finds a specific file, check the [default ones](https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/crawler.clj#L55-L62)

**Comment by ericdallo** [comment]
for example:
```clojure
{:project-specs [{:project-path "bb.edn"
                  :classpath-cmd ["bb" "/tmp/bbcp.clj"]}]}
```

**Comment by borkdude** [comment]
@ericdallo Can't get it to work. It seems it doesn't even make a `.lsp/sqlite.db`.

**Comment by ericdallo** [comment]
What is the output of clojure-lsp.out? You can get it with `lsp-clojure-server-info` via `:log-path`

**Comment by borkdude** [comment]
It seems it is scanning files in `Analyzing source paths for project root /Users/borkdude/Dropbox/temp` while my sources are in `Dropbox/temp/lsptest` 🤔

**Comment by ericdallo** [comment]
It's because you configured the project root as `Dropbox/temp/`, you can fix it with `lsp-workspace-folders-remove` and then `lsp`

**Comment by borkdude** [comment]
Ah, this worked!

<img width="703" alt="Screenshot 2021-05-16 at 23 52 22" src="https://user-images.githubusercontent.com/284934/118413881-cc639400-b6a1-11eb-9d97-754d8a889c9f.png">

**Comment by ericdallo** [comment]
Nice!
Any changes to bb has that script built-in some way?

**Comment by borkdude** [comment]
Can you re-phrase those sentences? I'm not sure I understand. With connection, do you mean, doing a curl to Github? This is very fast. The script runs in 100ms on my machine.

**Comment by borkdude** [comment]
Eventually there can be something in bb like this, but I think it's more flexible to use a script to being with, to figure out what exactly we need and so people can tweak the script to their needs.

**Comment by borkdude** [comment]
One improvement to the script would be to merge in the paths and deps from bb.edn so that they also appear on the classpath.

**Comment by ericdallo** [comment]
if user doesn't have an internet connection, the classpath will fail, but it doesn't seem to be a block to me as lein does the same I think.

If bb doesn't provide that built-in how do you think it would be the final ux? would users need to have that custom script and project-specs configured manually?

**Comment by borkdude** [comment]
> if user doesn't have an internet connection, the classpath will fail

Isn't this always the case with downloading deps? You can't magically generate some classpath, if you don't have those deps.

The final UX: let's take it one step at a time, we first have to find out what works and this can be done through some scrips initially.

> would users need to have that custom script 

We can put it in a gist or gitlib, so people can put it in their bb.edn or so, to get going

> project-specs configured manually

If you don't configure those project-specs, how else is lsp going to know what to do?

**Comment by ericdallo** [comment]
> Isn't this always the case with downloading deps? You can't magically generate some classpath, if you don't have those deps.

Yeah, I think it makes sense

> If you don't configure those project-specs, how else is lsp going to know what to do?

My idea was to add support by default adding something to [default project-specs](https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/crawler.clj#L55-L62), something like:
```clojure
{:project-path "bb.edn"
 :classpath-cmd ["bb" "print-deps"]} ;; or the script 
```

**Comment by borkdude** [comment]
Cool, yeah, that makes sense. So for now we can tell people to download the script and configure it like above, gather some feedback and then improve the UX.

**Comment by ericdallo** [comment]
Ok, thanks for the help!

**Comment by ericdallo** [comment]
Sorry to bother you again with this @borkdude, but I'd really like to make the bb <-> clojure-lsp integration just as good as any other tool (clj, lein, boot, shadow-cljs) for the final user, your script seems to work really well, would you accept a PR adding this logic to bb as something like `bb print-deps`? It could even check for bb.edn extra libs and add to the classpath in the future?

Then we could add a default project-spec for bb [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/crawler.clj#L63-L70) so bb would just work without any other configuration, WDYT?

**Comment by borkdude** [comment]
Let's also coordinate with @cfleming if this is something he wants to be using from Cursive as well. He has been working on bb integration with Cursive as well and may have some insights. Happy to hear them.

**Comment by borkdude** [comment]
Oops, tagged the wrong person. I meant @cursive-ide.

**Comment by cursive-ide** [comment]
So is the proposal to add an option to bb to output a deps.edn containing the runtime dependencies? Something like that would be useful for Cursive, definitely. Currently I retrieve the bb version once the user has configured the executable path, download the deps.edn script from Github and then modify it in more or less the same manner as the script above. The main problem is there's no good way to calculate the two explicit dependency versions, currently they're hard-coded in Cursive pending a better solution. Something like a `bb print-deps` would definitely be a nicer solution for this.

**Comment by borkdude** [comment]
@cursive-ide Got it, thanks. Will report back once there is something useful to test.

**Comment by borkdude** [comment]
@ericdallo @cursive-ide I had another idea regarding the following two problems: 

1) Some functions in babashka, like `babashka.wait/wait-for-path` are not (yet) in a library. These could be moved to a library of course, but...
2) Some public vars of some libraries are not available in babashka. E.g. in cheshire there is stuff around JSON SLIME which is not commonly used so it's not available in babashka to save on binary size.

Considering the above, it may make sense to (programmatically) create a mock project purely for static analysis which has all namespaces and "dummy" vars (only a def or defn with a docstring and metadata like `:dynamic`) that are available in babashka. This project can then be re-generated for each version of babashka and tagged as such. Perhaps this is more useful for static analysis than using the "real" dependencies. Thoughts?

**Comment by ericdallo** [comment]
I see the problem, but that wouldn't be easier to make clojure-lsp understand this mock project and it seems a specific issue with babashka, my idea of a `bb print-deps` would make it much similar to other tools regarding the ability to print the classpath that is what is important for clojure-lsp (and probably cursive).
IMO that would be a better start

**Comment by borkdude** [comment]
@ericdallo The mock project would be "understood" by clojure-lsp and Cursive by just analyzing that dependency, no special logic needed. That dependency would contain all the code that the static analyzer should analyze.

**Comment by ericdallo** [comment]
Hum, not sure what that dependency would be, a jar? a tmp folder?

**Comment by borkdude** [comment]
@ericdallo It could just be a dependency on github that you can include as a git dependency.

**Comment by ericdallo** [comment]
I see, so clojure-lsp would need to download the dependency and consider it as part of the classpath as clj-kondo would scan it later and consider the vars of that project in its analysis, right?
It could work but seems too specific, I don't see a big issue a command that would print the classpath of those libs even if there are public vars not exposed

**Comment by borkdude** [comment]
@ericdallo Right. Well, the problem is that clojure-lsp (and Cursive) would offer completions for vars that aren't really available. 

Btw, to get something clear, again, `bb print-deps` would not print a classpath, but a `deps.edn`. That `deps.edn` can in turn be used to convert it into a classpath, but I think it's better to output data which can then be used to calculate a classpath instead of outputting a classpath directly (we've been over this before in this thread).

**Comment by ericdallo** [comment]
I see what bb would print, but I can't understand how that would be useful for clojure-lsp, how clj-kondo would analyze that output and return the analysis for clojure-lsp. ATM clojure-lsp call clj-kondo to analyze each path returned from the classpath output

**Comment by borkdude** [comment]
Yes, I understand. It's not so hard to convert a `deps.edn` into a classpath though. You're already doing this within clojure-lsp when you detect a `deps.edn` right?

**Comment by ericdallo** [comment]
yes, actually `clojure -Spath` already return an existent classpath, jars and folders that exist on the machine, would clojure-lsp need to put that new bb mock dependency somewhere for clj-kondo be able to find those files?

**Comment by borkdude** [comment]
I think we can figure that one out relatively easily. e.g. `bb -cp $(bb print-deps) -e '(babashka.classpath/get-classpath)'` would do the same, but perhaps we could just support it as `bb print-deps --classpath` to print a classpath, I can see how that would be more convenient. Anyway, that would print "real" deps and not the "mock" dependency. I'll give it some more hammock time...

**Comment by ericdallo** [comment]
Yeah, printing the classpath would make it much easier for clojure-lsp indeed, one thing I still don't understand clearly is:
when you `lein classpath`, `clojure -Spath`, it will print for example cheshire jar path from my `.m2` folder that `clojure` or `lein` downloaded previously, but when I `bb print-deps --claspath`, it will print cheshire or some other built-lib from what place? how clj-kondo would analyze the built-in lib folder/jar if not present somewhere.
Sorry if that sounds confusing, I'm just trying to understand how that flow would work completely

**Comment by borkdude** [comment]
I think what bb would do if you add the `--classpath` flag, that it will do what the above expression does (which contains a mistake I see now). So using the printed deps map, it will call deps.clj which will then calculate the classpath from that (which will force cheshire etc, to be downloaded if it wasn't already). In that way, clojure-lsp can just read cheshire, etc. from the .m2 dir.

**Comment by ericdallo** [comment]
Hum.. I see now, so the return of the bb print-deps would be passed to deps.clj which would do the magic of downloading the deps to the path which later would be analyzed by clj-kondo.
It'd still need a refactor in clojure-lsp for handling this bb case but I think would work

**Comment by cursive-ide** [comment]
Right, the problem with just printing a classpath for the deps is that bb doesn't actually include those deps in its distribution, so it really has to provide something that can then be passed to a tool that does download deps (e.g. to .m2) such as tools.deps. 

I considered the function stubs idea, and it's something that Cursive already does so implementing it would have been easy. If that's an option, then bb doesn't really have to do anything over and above what it already does, those stubs can just be generated from the runtime using introspection. Cursive already does that for tricky namespaces which generate a lot of vars at runtime. The advantage is that the stubs reflect exactly what the runtime environment actually provides, the disadvantage is that if the user wants to look at the source of a dependency namespace they can't. In the end I decided that the dependency option was better even though it was quite tricky to implement. What I might end up doing on top of the deps approach is introspecting the available vars and have an inspection which flags if someone accesses a var which isn't actually available in the runtime.

One thing we haven't discussed here is Java classes. Currently as far as I can tell there's no way to introspect from bb which Java classes are available. I've seen classes.clj in the bb repo, but that's not easy to extract the list from and it depends on the features selected in features.clj. It would be really useful if the class list generation created a json or edn file listing the available classes which could be obtained from the runtime somehow.

**Comment by borkdude** [comment]
> What I might end up doing on top of the deps approach is introspecting the available vars and have an inspection which flags if someone accesses a var which isn't actually available in the runtime.

So it seems we still need the deps approach. I'll go ahead and implement that first. That feature also comes in handy for #720 and ideally if bb has a new feature it addresses multiple use cases.

Currently I'm thinking of `bb print-deps` which accepts:

```
--format deps (default): prints deps.edn file with paths + built-in + external deps 
--format classpath: prints classpath (derived from deps.edn file, resolved using tools.deps)
```

> One thing we haven't discussed here is Java classes.

This one is easy. Each babashka release publishes the list of classes as a json file called `reflection.json`:
https://github.com/babashka/babashka/releases/tag/v0.5.0

**Comment by borkdude** [comment]
@cursive-ide @ericdallo I added `bb print-deps` as described in my previous message. It also merges deps from `bb.edn` into the output.

```
borkdude@MBP2019 /tmp/project $ cat bb.edn
{:deps {medley/medley {:mvn/version "1.0.0"}}}
borkdude@MBP2019 /tmp/project $ bb print-deps --format deps
{:deps
 {selmer/selmer {:mvn/version "1.12.44"},
  org.clojure/clojure {:mvn/version "1.11.0-alpha1"},
  org.clojure/tools.logging {:mvn/version "1.1.0"},
  org.clojure/tools.cli {:mvn/version "1.0.206"},
  rewrite-clj/rewrite-clj {:mvn/version "1.0.644-alpha"},
  hiccup/hiccup {:mvn/version "2.0.0-alpha2"},
  org.clojure/data.xml {:mvn/version "0.2.0-alpha6"},
  org.clojure/data.csv {:mvn/version "1.0.0"},
  com.taoensso/timbre {:mvn/version "5.1.2"},
  com.cognitect/transit-clj {:mvn/version "1.0.324"},
  babashka/babashka.curl {:mvn/version "0.0.3"},
  clj-commons/clj-yaml {:mvn/version "0.7.107"},
  cheshire/cheshire {:mvn/version "5.10.1"},
  org.clojure/core.match {:mvn/version "1.0.0"},
  org.hsqldb/hsqldb {:mvn/version "2.5.1"},
  org.clojure/test.check {:mvn/version "1.1.0"},
  babashka/fs {:mvn/version "0.0.5"},
  nrepl/bencode {:mvn/version "1.1.0"},
  org.clojure/core.async {:mvn/version "1.3.618"},
  http-kit/http-kit {:mvn/version "2.5.3"}}}
borkdude@MBP2019 /tmp/project $ bb print-deps --format classpath
src:/Users/borkdude/.m2/repository/babashka/babashka.curl/0.0.3/babashka.curl-0.0.3.jar:/Users/borkdude/.m2/repository/babashka/fs/0.0.5/fs-0.0.5.jar:/Users/borkdude/.m2/repository/cheshire/cheshire/5.10.1/cheshire-5.10.1.jar:/Users/borkdude/.m2/repository/clj-commons/clj-yaml/0.7.107/clj-yaml-0.7.107.jar:/Users/borkdude/.m2/repository/com/cognitect/transit-clj/1.0.324/transit-clj-1.0.324.jar:/Users/borkdude/.m2/repository/com/taoensso/timbre/5.1.2/timbre-5.1.2.jar:/Users/borkdude/.m2/repository/hiccup/hiccup/2.0.0-alpha2/hiccup-2.0.0-alpha2.jar:/Users/borkdude/.m2/repository/http-kit/http-kit/2.5.3/http-kit-2.5.3.jar:/Users/borkdude/.m2/repository/nrepl/bencode/1.1.0/bencode-1.1.0.jar:/Users/borkdude/.m2/repository/org/clojure/clojure/1.11.0-alpha1/clojure-1.11.0-alpha1.jar:/Users/borkdude/.m2/repository/org/clojure/core.async/1.3.618/core.async-1.3.618.jar:/Users/borkdude/.m2/repository/org/clojure/core.match/1.0.0/core.match-1.0.0.jar:/Users/borkdude/.m2/repository/org/clojure/data.csv/1.0.0/data.csv-1.0.0.jar:/Users/borkdude/.m2/repository/org/clojure/data.xml/0.2.0-alpha6/data.xml-0.2.0-alpha6.jar:/Users/borkdude/.m2/repository/org/clojure/test.check/1.1.0/test.check-1.1.0.jar:/Users/borkdude/.m2/repository/org/clojure/tools.cli/1.0.206/tools.cli-1.0.206.jar:/Users/borkdude/.m2/repository/org/clojure/tools.logging/1.1.0/tools.logging-1.1.0.jar:/Users/borkdude/.m2/repository/org/hsqldb/hsqldb/2.5.1/hsqldb-2.5.1.jar:/Users/borkdude/.m2/repository/rewrite-clj/rewrite-clj/1.0.644-alpha/rewrite-clj-1.0.644-alpha.jar:/Users/borkdude/.m2/repository/selmer/selmer/1.12.44/selmer-1.12.44.jar:/Users/borkdude/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.4/jackson-core-2.12.4.jar:/Users/borkdude/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.12.4/jackson-dataformat-cbor-2.12.4.jar:/Users/borkdude/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.12.4/jackson-dataformat-smile-2.12.4.jar:/Users/borkdude/.m2/repository/tigris/tigris/0.1.2/tigris-0.1.2.jar:/Users/borkdude/.m2/repository/org/flatland/ordered/1.5.9/ordered-1.5.9.jar:/Users/borkdude/.m2/repository/org/yaml/snakeyaml/1.26/snakeyaml-1.26.jar:/Users/borkdude/.m2/repository/com/cognitect/transit-java/1.0.343/transit-java-1.0.343.jar:/Users/borkdude/.m2/repository/com/taoensso/encore/3.12.1/encore-3.12.1.jar:/Users/borkdude/.m2/repository/io/aviso/pretty/0.1.37/pretty-0.1.37.jar:/Users/borkdude/.m2/repository/org/clojure/core.specs.alpha/0.2.56/core.specs.alpha-0.2.56.jar:/Users/borkdude/.m2/repository/org/clojure/spec.alpha/0.2.194/spec.alpha-0.2.194.jar:/Users/borkdude/.m2/repository/org/clojure/tools.analyzer.jvm/1.1.0/tools.analyzer.jvm-1.1.0.jar:/Users/borkdude/.m2/repository/org/clojure/data.codec/0.1.0/data.codec-0.1.0.jar:/Users/borkdude/.m2/repository/org/clojure/tools.reader/1.3.5/tools.reader-1.3.5.jar:/Users/borkdude/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.4/jackson-databind-2.12.4.jar:/Users/borkdude/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/Users/borkdude/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar:/Users/borkdude/.m2/repository/org/msgpack/msgpack/0.6.12/msgpack-0.6.12.jar:/Users/borkdude/.m2/repository/com/taoensso/truss/1.6.0/truss-1.6.0.jar:/Users/borkdude/.m2/repository/org/clojure/core.memoize/1.0.236/core.memoize-1.0.236.jar:/Users/borkdude/.m2/repository/org/clojure/tools.analyzer/1.0.0/tools.analyzer-1.0.0.jar:/Users/borkdude/.m2/repository/org/ow2/asm/asm/5.2/asm-5.2.jar:/Users/borkdude/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.4/jackson-annotations-2.12.4.jar:/Users/borkdude/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar:/Users/borkdude/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar:/Users/borkdude/.m2/repository/org/clojure/core.cache/1.0.207/core.cache-1.0.207.jar:/Users/borkdude/.m2/repository/org/clojure/data.priority-map/1.0.0/data.priority-map-1.0.0.jar
``` 

Linux static: https://21294-201467090-gh.circle-artifacts.com/0/release/babashka-0.5.1-SNAPSHOT-linux-amd64-static.tar.gz

macOS: https://21290-201467090-gh.circle-artifacts.com/0/release/babashka-0.5.1-SNAPSHOT-macos-amd64.tar.gz

**Comment by ericdallo** [comment]
That's great!
I'll start to implement that on clojure-lsp side and let you know

**Comment by ericdallo** [comment]
@borkdude It works like a charm for clojure-lsp with bb.edn🎉, I need to improve that to auto resolve the source-paths checking `:paths` from bb.edn like I did before for lein and deps projects, and then later see the best approach to make it work with the shebang.
Thank you!

**Comment by ericdallo** [comment]
@borkdude let me know when this is released so I can merge https://github.com/clojure-lsp/clojure-lsp/pull/491

**Comment by borkdude** [comment]
ok, let's wait for a reaction from @cursive-ide as well and then we can probably release this.

**Comment by cursive-ide** [comment]
I haven't had a chance to test this in Cursive yet, but the format looks good to me and I don't anticipate any problems with this.

**Comment by borkdude** [comment]
Thanks for the feedback. I'll work on https://github.com/babashka/babashka/issues/957 and https://github.com/babashka/babashka.nrepl/issues/43 before the next bb release as these also affect Cursive. When do you plan to release something related to babashka, @cursive-ide? What is your release cadence, do you do any minor upgrades periodically as well?

**Comment by cursive-ide** [comment]
I don't do any releases at fixed periods, just as and when things are ready. I think it'll be probably a week or two before I release anything, and that will be an EAP (beta) release. It may be a bit longer because I also have some backend licence work to do. I'll then generally do a couple of quick releases fixing bugs and once things seem stable I'll wait a while to see if any major bugs crop up before doing a stable release.

**Comment by borkdude** [comment]
That sounds good.

**Comment by cursive-ide** [comment]
I've tested this using the binary from babashka/babashka.nrepl#43, and it looks good to me!

**Comment by geraldodev** [comment]
I've change the script a little bit so it:
* get the deps.edn from the tag of the babashka running version
* dissoc any :local/root variable from deps.edn
```
(require '[babashka.curl :as curl]
         '[babashka.deps :as deps]
         '[clojure.edn :as edn]
         '[clojure.java.shell :refer [sh]])

(def regex-version #"^babashka (v[0-9.]+)")

(defn get-deps
  "get the deps.edn from the tag of the running babashka"
  []
  (let [version (:out (sh "bb" "--version"))
        [_ version] (re-find regex-version version)
        url (str "https://raw.githubusercontent.com/babashka/babashka/" version "/deps.edn")
        ; _ (println url)
        ]
    (:body (curl/get url))))

(def deps-edn (get-deps))
; (def deps-edn (:body (curl/get "https://raw.githubusercontent.com/babashka/babashka/v1.0.168/deps.edn")))

(defn dissoc-local-dependencies
  "remove :local/root dependencies, so we it's not an issue if borkdude changes it"
  [m]
  (reduce-kv
   (fn [m k v]
     (if (get v :local/root)
       m
       (assoc m k v))) {} m))

(let [deps (edn/read-string deps-edn)
      deps (update deps :deps assoc
                   'babashka/fs {:mvn/version "0.0.5"}
                   'babashka/babashka.curl {:mvn/version "0.0.3"})
      ; deps (update deps :deps dissoc 'org.babashka/sci  'babashka/babashka.core)
      deps (update deps :deps dissoc-local-dependencies)
      deps {:deps (:deps deps)}
      ; _ (clojure.pprint/pprint deps)
      cp (with-out-str (deps/clojure ["-Spath" "-Sdeps" deps]))]
  (println cp))
```

**Comment by borkdude** [comment]
@geraldodev you can now use the `bb print-deps` command for this

**Comment by wilkerlucio** [comment]
In recent versions, there is no need to make the setup, just add a `bb.edn` to the directory and it works.

**Comment by BenitoEck** [comment]
**Update for Helix Editor users working with Babashka and clojure-lsp**

As of now I do not get full completions for `required` dependencies in Helix via `clojure-lsp`. 

Instead the following message is shown: `No project-root-uri was specified, some features will be limited.`  The presence for a `bb.edn` does not remedy this.

**Work-around:** 

This can easily be fixed by placing a minimal `project.clj` file in the script directory:
```clojure
(defproject ns-of-your-script "0.1.0-SNAPSHOT" 
  :main ns-of-your-script)
``` 
Now full completions for etc `(fs/...`) work.
