### ISSUE TITLE
How to do input redirection in java shell or Babashka?

### ISSUE THREAD

**Issue by WorldsEndless** [babashka/babashka#746]
I'm wrapping the OpenConnect cli interface with Babashka. In bash this program takes one of two control flows:

1.  run COMMAND, then be interactively prompted for PASS
2.  Use redirection like `PASS >> COMMAND`

The second is what I most want in Babashka since it would be a one-liner solution, but I realized I have no idea how to make #1 work, either. I'm open to links that solve #1, but most of all I would like to know how to apply input redirection like Bash `>>` via Babashka or clojure.java.shell.

**Comment by borkdude** [comment]
@WorldsEndless 

1. You can read input with `(read-line)` just like in normal Clojure.
2. You can read a string from stdin with `(slurp *in*)`

**Comment by WorldsEndless** [comment]
I'm trying to devise how to apply your answer; here's where I've made it:

```clojure
(defn connect []
  "Connect to the VPN using openconnect, then provide it your password on stdin"
  (let [openconnect-args ["sudo" "openconnect" "VPN.COM" "--background" "--authgroup=AUTHGROUP" "--user=ME"
			  "--passwd-on-stdin"]
	;openconnect-args ["sudo" "openconnect" "cmps-vpn.byu.edu" "--background" "--authgroup=General_Access" "--user=torysa"]
	]
    (apply sh openconnect-args)
    ;; It now expects to receive my passwd on stdin. In bash, this is done with `PASS >> openconnect-args`
    ; How do I serve it the string in Babashka?
    ))
```

**Comment by borkdude** [comment]
@WorldsEndless Ah so you are starting a child process. You can provide `:in` like documented here:

https://clojure.github.io/clojure/clojure.java.shell-api.html

If you need more advanced "shelling out" also check out https://github.com/babashka/babashka.process.

**Comment by WorldsEndless** [comment]
Ah! That was beautifully simple. My last remaining problem is that, although OpenConnect has the --backgound flag it should respect, in practice the process is actually bound to the Babashka one. I could pull it off with running my babashka script with a `&`, but that seems like it defeats the process. I've also tried `(System/Exit 0)`, but this kills the vpn process as well. Any idea how to let the backgroudn process go on while Babashka concludes gracefully?

**Comment by borkdude** [comment]
@WorldsEndless If you want the child process to go its own way, you should probably not use `clojure.java.shell`. It might work with `babashka.process` since that doesn't wait for the process to end. I'm not sure if the child process will remain a live, but it's worth a try.

**Comment by borkdude** [comment]
I know that sometimes child process can stay alive, this is why babashka.process includes `destroy` and `destroy-tree` which you can hook into `:shutdown-hook`, because I've seen child processes running on my system if I didn't do this.

**Comment by WorldsEndless** [comment]
Wish sh, I could use `:in` and the only failing was that the process couldn't be async. So instead I'm trying Babashka process, as follows. Here I seem to be getting nothing at all, though: either the process never really starts, or it is terminated immediately; I'm not sure which.

```clojure
(defn connect []
  "Connect to the VPN using openconnect, then provide it your password on stdin"
  (let [vpn-server "VPN.COM"
	userphrase "--user=ME"
	openconnect ["openconnect" vpn-server "--background" "--authgroup=General_Access" userphrase
			  "--passwd-on-stdin"]
	pass "PASS"
	proc (p/process openconnect {:inherit true
				     :shutdown p/destroy-tree})]
    (with-open [w (io/writer (:in proc))]
      (.write w pass))))
```

**Comment by borkdude** [comment]
@WorldsEndless You can pass `:in` like you can with `clojure.java.shell/sh` in the opts.

If you run the `connect` function, this will return the result of `(.write ...)` while the process is running in the background. But since you passed the `:shutdown p/destroy-tree` option, the child process will surely be killed once the script exits.

**Comment by WorldsEndless** [comment]
I originally went away from `:in` with `p/process` because I got this error, which from the examples I thought was because it needed in to be a streamy-thing:

```clojure
(defn connect []
  "Connect to the VPN using openconnect, then provide it your password on stdin"
  (let [vpn-server "cmps-vpn.byu.edu"
	userphrase "--user=torysa"
	pass "Moses 1:4 mwawe"
	openconnect ["openconnect" vpn-server "--background" "--authgroup=General_Access" userphrase
		     "--passwd-on-stdin" :in pass]
	proc (p/process openconnect {:inherit true})]
    proc))
;; fgets (stdin): Input/output error
```

**Comment by WorldsEndless** [comment]
# inline :in

I originally went away from `:in` with `p/process` because I got this error, which from the examples I thought was because it needed in to be a streamy-thing:

```clojure
(defn connect []
  "Connect to the VPN using openconnect, then provide it your password on stdin"
  (let [vpn-server "VPN.COM"
	userphrase "--user=ME"
	pass "PASS"
	openconnect ["openconnect" vpn-server "--background" "--authgroup=General_Access" userphrase
		     "--passwd-on-stdin" :in pass]
	proc (p/process openconnect {:inherit true})]
    proc))
;; fgets (stdin): Input/output error
```

**Comment by borkdude** [comment]
@WorldsEndless You need to pass `:in pass` as part of the options map.

**Comment by WorldsEndless** [comment]
> @WorldsEndless You need to pass `:in pass` as part of the options map.

OH. So that is the difference with the sh approach. However, I'm still getting the same fgets error with this change:

``` clojure
proc (p/process openconnect {:inherit true
                                     :in pass})
```

**Comment by borkdude** [comment]
@WorldsEndless Use `:out :inherit :err :inherit :in pass`. Don't use `:inherit true` + `:in` because this will also inherit stdin from the parent process.

**Comment by WorldsEndless** [comment]
without :inherit, it changed the error:

```clojure
proc (p/process openconnect {:out :inherit
			     :err :inherit
			     :in pass})
;; fgets (stdin): No such file or directory
```

**Comment by borkdude** [comment]
Can you put an `@` sign in front of the `(p/process ..)` call, to give the process some more time to read from stdin?

**Comment by WorldsEndless** [comment]
Whoa. That worked! Seems like we've wandered far beyond the documentation, but your help was fantastic! Next up I'll be seeking to include "sudo" as a part of "connect" that doesn't defeat `:in`, and then implementing the sibling disconnect and restart functions. But this is the major hurdle! Here is the working solution code for completeness:

```clojure
(defn connect []
  "Connect to the VPN using openconnect, then provide it your password on stdin"
  (let [vpn-server "VPN.COM"
	userphrase "--user=ME"
	pass "PASSWD"
	openconnect ["openconnect" vpn-server "--background" "--authgroup=General_Access" userphrase
		     "--passwd-on-stdin"]
	proc @(p/process openconnect {:out :inherit
				     :err :inherit
				      :in pass})]
    proc))
```

**Comment by WorldsEndless** [comment]
Thank you so much for your help. I detail the solution here: https://orys.us/u5

**Comment by borkdude** [comment]
@WorldsEndless Nice! I will add it to https://github.com/babashka/babashka#articles-podcasts-and-videos

**Comment by borkdude** [comment]
@WorldsEndless I think this is a better approach for writing input.

Below a `clojure` process is started. The process waits for input, which we write from the parent process. Then the child process sleeps for 1 second and then continues. But meanwhile the script has already exited.

``` clojure
(ns wait-for-input
  (:require [babashka.process :as p]
            [clojure.java.io :as io]))

(let [proc (p/process ["clojure" "-M" "-e" "(do (Thread/sleep 1000) (println (slurp *in*)) (Thread/sleep 1000) (prn :bye))"]
                      {:out :inherit
                       :err :inherit
                       ;; enable for killing process when script ends
                       ;; :shutdown p/destroy
                       })
      in (:in proc)]
  (binding [*out* (io/writer in)]
    (println ":hello")))

(println :exiting)
(System/exit 0)

;; invoke with:
;; bb wait-for-input.clj; echo $?

;; you will see:
;; :exiting
;; 0
;; :hello
;; :bye
```
