### ISSUE TITLE
Division by zero returns a Java exception instead of infinity

### ISSUE THREAD

**Issue by concastinator** [babashka/babashka#747]
**Version**: 0.2.8

**Platform**: Windows 10 64bit

**Problem**: Division by zero returns a Java exception instead of infinity.

**Code reproducing the problem**

`(/ 1 0.0)`
`(/ 1 -0.0)`

**Expected behavior**

Given that Clojure has `##Inf` and `##-Inf`, and that it also knows how to perform some arithmetic with them, I was expecting the above snippets to evaluate to `##Inf` and `##-Inf`, respectively. Instead, what I get is
`user=> (/ 1 -0.0)`
`java.lang.ArithmeticException: Divide by zero [at <repl>:1:1]`
`user=> (/ 1 0.0)`
`java.lang.ArithmeticException: Divide by zero [at <repl>:1:1]`

**Other languages**

The Clojure REPL returns signed infinities, as expected (version 1.10.1, as found on [jdoodle.com](https://www.jdoodle.com)). This means that Babashka diverges from the Clojure REPL, which is why I consider this a bug.

ClojureScript mistakenly returns `Infinity` in both cases (as found on [clojurescript.io](https://clojurescript.io)). Notice the absence of the minus sign, and the fact that `Infinity` is not the same as `##Inf`. Is this divergence from the Clojure REPL an intended feature, or a bug? Where should I report it?

A brief review about how other languages treat this can be found [here](https://lemire.me/blog/2021/03/04/how-does-your-programming-language-handle-minus-zero-0-0/).

**Comment by borkdude** [comment]
@concastinator Interesting find. I'll see what I can do about it. This has to do with how babashka evaluates clojure functions. You can compare it this in Clojure:

```
user=> (apply / [1 0.0])
Execution error (ArithmeticException) at user/eval1 (REPL:1).
Divide by zero
```

**Comment by concastinator** [comment]
The fact that `(/ 1 0.0)` and `(apply / [1 0.0])` return different results is troubling; should I report this as a bug in Clojure?

ClojureScript fares better, in that both snippets return `Infinity`.

**Comment by borkdude** [comment]
Maybe we could ask in the Clojure channel in Clojurians slack or ping @puredanger for insights.

**Comment by concastinator** [comment]
Sine I do not participate in any of these communities, could you please do it instead? Thank you.

**Comment by puredanger** [comment]
https://ask.clojure.org is the appropriate place to ask this question about Clojure. I suspect the known types are different in the two cases and you're seeing different paths of / (Long vs Object).

**Comment by concastinator** [comment]
@puredanger: Since I do not have an account on ask.clojure.org, and since I am only learning the basics of the language right now (and therefore I would be unable to understand an answer), I shall let @borkdude, or you, or anybody else reading this, take it over from here and investigate further. If this leads to the clarification of these aspects of Clojure, and maybe to the fixing of bugs, I declare myself satisfied.

**Comment by borkdude** [comment]
Will re-open if needed. For now I'm not taking any action on this.

**Comment by concastinator** [comment]
@puredanger, it seems that the situation is more convoluted than previously thought. Let us ignore Babashka for a moment, and only focus on Clojure proper (1.10.3):

- evaluating `(/ 1 0)` throws an exception, but evaluating `(/ 1 0.0)` returns `##Inf`
- evaluating `(apply / [1 0.0])` returns, as discussed above, an exception.

This means that we have not one, but two bugs in Clojure:

- different behaviours depending on whether the denominator is an integer or a decimal
- different behaviours depending on whether one uses `/` or `apply /`.

I do not have a JIRA account, and I shall not create one until you confirm that these are bugs and should be reported.
