### ISSUE TITLE
How to add sudo to a proc command?

### ISSUE THREAD

**Issue by WorldsEndless** [babashka/babashka#748]
I'm writing a wrapper over a CLI api. Some of the commands, like the termination command, just use `sh` and so I start them with sudo and, upon executing them, I receive the desired sudo login prompt and things are normal. However, the startup commands use a proc because they need to provide input before starting a daemon process (#746). The inconsistency is that for certain commands I can just run `./vpn.clj -x` and it sudoes itself, but for others I have to do `sudo ./vpn.clj -s"` to make it work. How do I add `sudo` to a proc command so they all have the same invocation pattern?

**Comment by borkdude** [comment]
What about:

```
$ bb -e '(babashka.process/process ["sudo" "ls"] {:out :inherit}) nil'
```

**Comment by WorldsEndless** [comment]
Somehow I had the idea that adding sudo to the proc made some incompatibility with later `:in` stuff, but after  your example I tried it and it works; the errors I saw yesterday must have been something else. Thanks!

Solution that makes sudo prompts when necessary:
``` clojure
(defn connect []
  "Connect to the VPN using openconnect, then automatically provide it your password on stdin"
  (let [vpn-server "VPN.COM"
        userphrase "--user=ME"
        pass "PASS"
	;; added the "sudo" below and it works
        openconnect ["sudo" "openconnect" vpn-server "--background" "--authgroup=General_Access" userphrase
                     "--passwd-on-stdin"]
        proc @(p/process openconnect {:out :inherit
                                      :err :inherit
                                      :in pass})]
    proc))
```
