### ISSUE TITLE
Error when using System/out directly for writing output

### ISSUE THREAD

**Issue by mogenslund** [babashka/babashka#754]
Babashka v0.2.8
Fedora Linux

If I execute this code:
`(.print (System/out) "Something")`
I get the following error:
```
----- Error --------------------------------------------------------------------
Type:     java.lang.IllegalArgumentException
Message:  No matching method print found taking 1 args for class java.io.PrintStream
Location: <expr>:1:1

----- Context ------------------------------------------------------------------
1: (.print (System/out) "Something")
   ^--- No matching method print found taking 1 args for class java.io.PrintStream
```
It works when executed using Clojure.

To reproduce, run:
`bb -e '(.print (System/out) "Something")'`

Expected behavior: "Something" to be printed in the terminal.

**Comment by borkdude** [comment]
Thanks. 

Should be fixed with https://github.com/babashka/babashka/commit/45faf1ec6302ed9717acdea771741fa6109fe085.

Still need to add a unit test for it.
