### ISSUE TITLE
Task runner / bb.edn

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#756]
Please post feedback to https://github.com/babashka/babashka/discussions/757.
----

## Problem statement

Babashka scripts have an API to set their source paths (babashka.classpath) and dependencies (babashka.deps).
Babashka also has a way to run functions from the command line using the `-m` or `--main` flag. These are fairly low level ways of exposing functionality to the command line. Available scripts with a `-main` and their way of invoking needs explicit documentation.

General issues:

- There is no way to declare source paths + deps
- Available tasks aren't easy to discover  
- No uniform way to consult documentation/docstrings from the command line for a specific task
- No cross-platform way of invoking tasks (bash scripts don't run on Windows) apart from `bb -m foo.bar`
- No concise / convenient way of invoking tasks from the command line á la `make`
- Complex invocations lead to writing bash scripts for rememberability 
- No way of running global scripts without putting them on the PATH 

## Scope

This won't be a full `make` replacement (yet) although perhaps the proposed solution can be a foundation to build such a thing on top.

## Evaluation

The final solution will be tested on these projects:

- [rewrite-clj](https://github.com/clj-commons/rewrite-clj)
- https://github.com/clojure/core.rrb-vector/blob/master/script/jdo
- https://github.com/liquidz/antq/blob/main/Makefile
- https://github.com/eerohele/sigel/blob/master/Makefile

## Alternatives:

- Use `make` or `just`, etc.
- Adopt `bb -M:foobar` and `bb -X:foobar`. We may _also_ do that, but this won't give us the ability to compose tasks?

## Proposed solution

Inspired by lein aliases, npm scripts and deps.edn, babashka will offer a `bb.edn` file with:

- `:paths` for declaring source paths (same as deps.edn)
- `:deps` for declaring dependencies (same as deps.edn)
- `:tasks`: a list of tasks suited for command line invocation 

A task is written in hiccup syntax like `[:task 1 2 3]` or with options `[:task {} 1 2 3]`. 

### main
 
A `main` task can declare a `:main` function:

``` clojure
{:tasks
  {:foo-bar [main foo.bar]}}
```

or using a fully qualified symbol `foo.bar/baz` so you can accommodate multiple main functions in one namespace.

When invoking babashka with this task name (as keyword) the main function of this task will be invoked:

``` clojure 
$ bb :foo-bar
```

Using keywords as task names will signal to the user that a task is being invoked.

### shell

Example:

``` clojure
[shell "rm" "-rf" "target"]
``` 

or:

``` clojure
[shell "rm -rf" "-rf target"]
``` 

The exit code of a shell task will be propagated to the exit code of babashka itself.

### babashka

Lower level task which invokes babashka (within the same process):

``` clojure
[babashka "-e" "(+ 1 2 3)"]
``` 

### clojure

Task which invokes clojure:

``` clojure
[clojure "-M" "-e" "(+ 1 2 3)"]
``` 

### Combining tasks

Multiple tasks can be invoked in succession:

```
$ bb :clean:foo-bar
```

which requires all preceding tasks to succeed successfully. 

Within `bb.edn` tasks can be combined using `do`:

``` clojure
[do 
 [:clean]
 [:foo-bar]]
``` 

In the case of invoking multiple `main` or `babashka` tasks, the side effects of each task remain visible to the next task.
This allows tasks to build up in memory state.

### Discoverability 

To discover all available tasks, one can run:

```
$ bb tasks
``` 

If tasks are defined using a top-level map with `:description`, the description value will be used for printing:

``` clojure
{:tasks {:clean {:description "Clean all the things!" :task [shell "rm -rf target"]}}}
```

```
$ bb tasks
The following tasks are available:

:clean Clean all the things!
```
### Documentation

Tasks can include a `:doc` key that will be displayed when invoking `:doc` with the task name:

```
{:tasks {:clean {:doc "Clean all the things!" :task [shell "rm -rf target"]}}}
```

```
$ bb :doc :foo-bar
```

In the case of a `:main` task the docstring of the main function will be automatically included.

### Global tasks (TODO)

Tasks configured in `~/.bb/bb.edn` can be invoked globally. 

E.g.:

``` 
$ bb :http-server
```

### Aliases (TODO)

Like `deps.edn` users can define `:aliases` to bring in extra dependencies. This is supported in `bb.edn` as well, but in `bb.edn` `:aliases` are only used to change the classpath. In the case of a global `:http-server` task one might not always want to bring in the sources of the http server on the classpath for all tasks.
So tasks can opt in to extra dependencies and paths using `:aliases [:http-server-deps]`. 

### Pods (TODO)

TBD

### Merging in deps.edn (TODO)

Optionally? TBD

### bb.edn projects as deps (TODO)

You write a lib, like an http server and you write a bb.edn for it, so you can easily invoke it with bb.
But now you want to include this library as a dep into your bb.edn via e.g. local/root. how...? Because bb.edn isn't regarded as a dependency thing by tools.deps.alpha, the lib would have to also write a `deps.edn`.

We could put the entire bb.edn config inside deps.edn.
On the other hand, if all kinds of tools start saving their config in deps.edn, this file could become pretty big and tedious to parse on every tool invocation, so that is probably not great either.

Proposed solution: add `{:merge-deps true}` and `{:merge-deps {:aliases [:foobar]}}` as an option in `bb.edn`.

thheller on Slack: FWIW deps.edn didn't exist when I started with shadow-cljs.edn but I would make the same choice again. I prefer having targeted configuration files over the all-in-one gigantic configs

**Comment by borkdude** [comment]
Interceptor model twist by @helins:

https://gist.github.com/helins/de21872849d4149282dbcfeec49a41bf

Interceptor model by @steveb8n:

``` 
(defn run!
  [{:keys [verbose]} steps]
  (let [all-results (atom {})]
    (doseq [step steps]
      (let [{:keys [action success?]} step
            result (action @all-results)]
        (println)
        (println ">>" (:name step))
        (when verbose
          (pprint result))
        (if (success? result)
          (swap! all-results assoc (:name step) result)
          (throw (ex-info "action failed" result)))))
    (println)
    (println "Success!")))
 
(utils/run! options
            [{:name     :get-tag
              :action   utils/step-get-git-tag
              :success? (fn [result]
                          (not (nil? (:latest-commit-tag result))))}
             {:name     :get-sha
              :action   utils/step-get-git-sha
              :success? (constantly true)}
             {:name     :compress-main-js
              :action   (fn [_]
                          (utils/compress-file! "./public/client-js" "main.js"))
              :success? (fn [result]
                          (> (:size-compressed result) 0))}
             {:name     :deploy-editor-js
              :action   (fn [results]
                          (let [sha (get-in results [:get-sha :sha])]
                            (utils/deploy-compressed-asset-to-s3!
                              {:region       bucket-region
                               :content-type "application/javascript"}
                              "main.js.gz"
                              (str  "/editor/main." sha ".js"))))
              :success? (fn [result]
                          (nil? (:Error result)))}
             ])
```

**Comment by borkdude** [comment]
I think the bb scripts in [rewrite-clj](https://github.com/clj-commons/rewrite-clj/tree/main/script) would lend itself well for a `bb.edn` test-drive.

https://github.com/clj-commons/rewrite-clj/blob/main/script/coverage.clj

- the add-classpath thing would become `{:paths ["script"]}`
- instead of invoking `script/coverage.clj` one could declare a task:
```{:tasks {:coverage {:task/type :babashka :args [-m coverage/main]}}}```
and then run with:
```$ bb :coverage```
Same for:
```$ bb :clj-watch```
etc.
And `$ bb :tasks` would then give an overview of your tasks.
For help you one do `$ bb :help :coverage` to see some help text defined in `bb.edn`.

**Comment by borkdude** [comment]
----
TODO: 

- [x] a `:do` task which allows you to compose a task from multiple other tasks (in order), similar to `lein do`:
   ```
   $ lein do exec -e '(prn (+ 1 2 3))', exec -e '(prn (+ 1 2 3))'
   ```

- [x] `:paths`
- [x] `:deps` 
- [ ] description + help text
- [ ] :help task 
- [x] prioritize user-defined names over built-in tasks
- [ ] pod config

```
for pods: not sure yet how to manage those in the bb.edn.
I mean you could declare that you would need those:
{:pods {org.babashka/hsqldb {:pod/version ...}}}
but not sure what to do: it might not make sense to always load every pod for every single namespace. so maybe a task could additionally declare that the pod should be loaded with :pods [org.babashka/hsqldb] or something
or maybe that pod config should go entirely in a task. something to think about still
```

Currently not in scope:

- [ ] make replacement
- [ ] consider interceptor model (see below)

----

Working prototype in bb-edn branch:

``` clojure
$ cat bb.edn
{:tasks {:eval-plus   {:babashka/args ["-e" "(+ 1 2 3)"]}
         :tree        {:babashka/args [:clojure "-Stree"]}
         :count-files {:babashka/process ["bash" "-c" "ls | wc -l"] }}}

$ bb :eval-plus
6

$ bb :count-files
       1

$ bb :tree | head
org.clojure/clojure 1.10.1
  . org.clojure/spec.alpha 0.2.176
  . org.clojure/core.specs.alpha 0.2.44
  ``` 

Keywords aren't likely to clash with filenames, this allows us a safe path to sub-parsing.

E.g. we can have:

``` clojure
bb :uberjar ...
bb :test ...
bb :clojure ...
``` 

while remaining backwards compatible with the current CLI parsing.

Pleas post ideas to: https://github.com/babashka/babashka/discussions/757

**Comment by borkdude** [comment]
Issue:

``` clojure
{:tasks {:bye [do [shell "echo bye"]]
         :dotask [do
                  [shell "echo hello"]
                  [:bye]]
         :entry [:dotask]}}
``` 

This spawns a REPL.

**Comment by borkdude** [comment]
Closing in favor of less DSL.

**Comment by levitanong** [comment]
Is the `less DSL` approach #778 ? Asking partly so that any visitor that drops by can be redirected to the right issue.

**Comment by borkdude** [comment]
Correct.
