### ISSUE TITLE
A command line switch like python's -x would be very helpful

### ISSUE THREAD

**Issue by primer-1** [babashka/babashka#766]
python's -x switch makes the interpreter ignore the first line of input.

This would be very helpful because it would facilitate the creation of Windows batch files that are self contained babashka scripts.  Such a switch is key to a workaround for Windows' lack of support for a shebang line in batch files.

See [this stackoverflow answer](https://stackoverflow.com/questions/17467441/how-to-embed-python-code-in-batch-script/29881143#29881143) for more details.

P.S.  Thanks so much for babashka!  As you may have guessed, I'm using it as a powerful scripting facility under Windows.

**Comment by borkdude** [comment]
@primer-1 

I am experimenting a bit like this:

shebang.bat:
```
@set BABASHKA_SKIPLINE=(binding,[*file*,(first,"""%~f0""")],(load-string,(str/join,(drop,2,(str/split-lines,(slurp *file*))))))
@SETLOCAL ENABLEDELAYEDEXPANSION & bb -e (load-string,(System/getenv,"""BABASHKA_SKIPLINE""")) %* & EXIT /B !ERRORLEVEL!

(println "Hello world!")
```

The issue here is that `%~f0` does not expand into a path that is a valid string in Java... any ideas?

**Comment by primer-1** [comment]
Very cool, but it doesn't quite work with command line arguments, e.g.,

@set BABASHKA_SKIPLINES=(binding,[*file*,(first,*command-line-args*)],(load-string,(str/join,(drop,2,(str/split-lines,(slurp *file*))))))
@SETLOCAL ENABLEDELAYEDEXPANSION & bb -e "%BABASHKA_SKIPLINES%" "%~f0" %* & EXIT /B !ERRORLEVEL!

(println (format "*%s*" (str *command-line-args*))))



The above batch file prints out its filename as the first command line argument in addition to the ones actually passed.
I would think that the "%~f0" would not be needed at all in this case since its original purpose was to pass the name of the file to the python interpreter.  That shouldn't be necessary since the script lines are now being slurped.

However, if I remove "%~f0" I then get a file not found error:
c:\prj\test>c:/bin/simple 123 456
----- Error --------------------------------------------------------------------
Type:     java.io.FileNotFoundException
Message:  123 456 (The system cannot find the file specified)
Location: 1:47

----- Locals -------------------------------------------------------------------
: nil

**Comment by primer-1** [comment]
We are very close!  For some reason, if I include a commented line by starting with a semicolon, all remaining input in the file is ignored.

@set BABASHKA_SKIPLINES= ^
 (binding [*file* (first *command-line-args*) ^
           *command-line-args* (next,*command-line-args*)] ^
  (load-string (str/join (drop 7 (str/split-lines (slurp *file*))))))

@SETLOCAL ENABLEDELAYEDEXPANSION & bb -e "%BABASHKA_SKIPLINES%" "%~f0" %* & EXIT /B !ERRORLEVEL!

(println "hello")

;; this is a comment

(println "hello 2") ; this will not be printed

this is a syntax error that will go unreported

**Comment by primer-1** [comment]
I guess that's happening because the input is being collapsed to a single line, so comment to end of line in this case means comment to end of input

**Comment by borkdude** [comment]
Oh, this can be easily fixed:

```
@set BABASHKA_SKIPLINES= ^
 (binding [*file* (first *command-line-args*) ^
           *command-line-args* (next *command-line-args*)] ^
  (load-string (str/join \newline (drop 7 (str/split-lines (slurp *file*))))))

@SETLOCAL ENABLEDELAYEDEXPANSION & bb -e "%BABASHKA_SKIPLINES%" "%~f0" %* & EXIT /B !ERRORLEVEL!

```

I'm not sure if the Windows escape stuff will accept `\newline`, but if it doesn't work you can try "\n" or "\r\n" instead.

**Comment by primer-1** [comment]
Yes, the change exactly as you made it works perfectly.  A recipe worthy of the babashka book, IMO! :-)

Thank you for your help

**Comment by borkdude** [comment]
@primer-1 This is awesome!

I also made deps.clj available as a .bat script now:

https://twitter.com/borkdude/status/1377550820443615233

See https://github.com/borkdude/deps.clj
