### ISSUE TITLE
Enhance pod download and setup for script distribution

### ISSUE THREAD

**Issue by arichiardi** [babashka/babashka#768]
**Is your feature request related to a problem? Please describe.**
At the moment it is a bit cumbersome to setup pods, cause you have to download stuff manually like in [this approach](https://github.com/eccentric-j/idle-parens/blob/8f4142d66698adadb321ace92da9ed79bbcbcedc/resources/blog/2021-01-27-clojure-like-its-php.md#download--install-babashka-postgresql-pod).

On top of that, given pods are OS dependent, you would need to fiddle with arch targets in the github releases json. Doable, but it's got some friction.

**Describe the solution you'd like**
Pasting from Slack, something like this would be nice to add to `bb.edn`:

```
(arichiardi)
Yeah specifying pods in bb.edn is a good option..what about this
{:paths ...
   :deps ...
   :pods {org.babashka/postgresql :github/version "0.0.5"}
And then
bb dump-pods <dir> <arch>
```

```
(borkdude)
Yeah, something like that might work.
Perhaps:
bb pods install /tmp/pods --arch ....
but then also:
{:pods {:dir "/tmp/pods" ....}}
if you want to load the pods from some specific dir
```

```
(arichiardi)
oh yes right good idea!
```

**Describe alternatives you've considered**

The alternative is to have a `install-deps.sh` script that inspects the pod releases and downloads the right one, storing it into a dir that you have to then refer to in your `.bb` files.

**Comment by borkdude** [comment]
Another conversation with @FieryCod:

```
Is there a way that I can say to babashka "Hey bb just download the pods! Don't do anything else!!"?

borkdude: Not right now. But we could make something like this in bb.edn: you declare the pods there and then you could say bb pods --download or something
```

**Comment by FieryCod** [comment]
For now, I will use `download_pods.clj` with pods declared and manually call bb on it. Nevertheless I'm looking forward to seeing something like `bb pods --download` which would automate the process

**Comment by borkdude** [comment]
@arichiardi and @FieryCod We now prepared "declarative" pod support, in `bb.edn`:

https://github.com/babashka/pods#in-a-babashka-project

With that in place, any bb usage will download the pods, e.g. `bb --version` will. 

Am I right that the major thing still missing here and in #1019 downloading/loading pods from a specific place, e.g. `BABASHKA_PODS_DIR=.project/pods`? If so, would adding that env var be sufficient for closing those issues?

**Comment by FieryCod** [comment]
Yeah, I still need `BABASHKA_PODS_DIR`.

**Comment by FieryCod** [comment]
@borkdude I think this is no longer required at least for me.

**Comment by borkdude** [comment]
@FieryCod I'll close these issues and we can assess new request based on what's there now in 0.8.0.
