### ISSUE TITLE
Consider adding rewrite-clj

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#769]
This could be useful for transforming or analyzing code in scripts.

Please leave some feedback if you would find this useful. 

A branch `feature-rewrite-clj` has been prepared to test feasibility and the total add was `1.9mb` binary size.

/cc @lread

**Comment by lread** [comment]
Obviously I'm in! 🙂

**Comment by laurio** [comment]
I'd like to write a Babashka script which uses rewrite-clj in order to sort all projects namespaces requires and imports alphabetically.

**Comment by borkdude** [comment]
Imagine hooking up such scripts right inside an elisp function (or some other editor's scripting language) :)

**Comment by justone** [comment]
I am definitely for adding this to babashka, seems quite useful.

**Comment by FelipeCortez** [comment]
I'd find this very useful as well!

**Comment by mike-thompson-day8** [comment]
We'd use it tomorrow.  Our usecase in re-com:  https://github.com/day8/re-com/tree/master/scripts/add-at-macro

**Comment by borkdude** [comment]
Merged to master now.
