### ISSUE TITLE
Use get-classpath rather than classpath arg when creating uberjar

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#776]
When creating an uberjar, the classpath from `bb.edn` should also be picked up. So rather than using the explicit `--classpath` arg, use `(cp/get-classpath)`.

There was also a bug when not setting the classpath (and not having a bb.edn) that all the files from the current directory were included.

**Comment by arichiardi** [comment]
I have had a brief look at this, it seems the classpath is effectively computed from `bb.edn` if missing...https://github.com/babashka/babashka/blob/master/src/babashka/main.clj#L577

Maybe I am using a version of `bb` that does not have that code yet?

**Comment by borkdude** [comment]
@arichiardi Correct, but the computed classpath isn't use over here:

https://github.com/babashka/babashka/blob/8e30cd350e529b0e057369feaa4436197d378ec5/src/babashka/main.clj#L732

**Comment by arichiardi** [comment]
I see, it seems simple enough for me to do that, and having a look at the other issue...

**Comment by borkdude** [comment]
Cool, thanks!
