### ISSUE TITLE
Uberjar: no classpath and bb.edn should not just include all files

### ISSUE THREAD

**Issue by arichiardi** [babashka/babashka#780]
**version**

v0.3.1

**platform**

linux-amd64

**problem**

There was also a bug when not setting the classpath (and not having a bb.edn) that all the files from the current directory were included.

**repro**

Don't have one sorry

**expected behavior**

It should probably error out saying that it can't create the uberjar.

**Comment by russmatney** [comment]
I ran into this today, looks like there are a couple of related issues.

## uberjar argument order

The [docs/babashka-book](https://book.babashka.org/#_uberjar) recommends building an uberjar like so:

```
bb -cp $(clojure -Spath) uberjar foo.jar -m foo
```

In practice this results in an error:

```
> bb -cp $(clojure -Spath) uberjar clawe.jar -m clawe.core
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  File does not exist: uberjar
```

For now, using `--uberjar` instead of `uberjar` seems to work fine.

## classpath-overrides leaves blank on classpath, resulting in adding the entire directory to the jar

This alias:

```
{:aliases
 {:remove-clojure
  {:classpath-overrides
   {org.clojure/clojure          nil
    org.clojure/spec.alpha       nil
    org.clojure/core.specs.alpha nil}}}
```

Used thusly:

```
clojure -A:remove-clojure -Spath
```

Builds a path with empty spaces `::` where the classpaths were overridden.

```
src::/home/russ/russmatney/ralphie/src:::/home/russ/.m2/repository/cheshire/cheshire/5.10.0/cheshire-5.10.0.jar:/home/russ/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.10.2/jackson-core-2.10.2.jar:/home/russ/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.10.2/jackson-dataformat-cbor-2.10.2.jar:/home/russ/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.10.2/jackson-dataformat-smile-2.10.2.jar:/home/russ/.m2/repository/tigris/tigris/0.1.2/tigris-0.1.2.jar
```

As far as I can tell, this results in adding the entire directory to the jar. Building with 

```
bb -cp $(clojure -Spath) --uberjar clawe.jar -m clawe.core
```
works as expected (Though it now includes all of clojure and spec).

**Comment by borkdude** [comment]
I asked this question in tools deps on Clojurians slack:

In some situations like when using `nil` `:classpath-overrides`, the classpath can and up having empty paths in between like `src::/home/russ/russmatney/ralphie/src:::/home/russ/.m2/repository/cheshire/cheshire/5.10.0/cheshire-5.10.0.jar`.
This has the effect that the local dir is added to the classpath. Demo:

```echo '(ns foo) (prn :foo)' > foo.clj
clj -Scp ":$(clojure -Spath)" -M -e "(require 'foo)"
:foo```
Is this a feature, or a bug?

**Comment by borkdude** [comment]
This commit https://github.com/babashka/babashka/commit/15e71b0807e265b78b4511430a5e31e3d746b6ef fixed the CLI parsing and throws when no classpath has been provided.

About the empty classpath entries, I will wait for a response. 

It's better to use `bb.edn` anyway with `:deps` and `:paths`.

**Comment by borkdude** [comment]
For now I've decided to ignore empty classpath entries (instead of treating them as the current dir)

**Comment by arichiardi** [comment]
> Is this a feature, or a bug?

IMHO an empty classpath entry (sandwitched `::`) should never map to current dir, cause current dir would be `:.:` with the dot. So imho it's a bug :smile:

**Comment by borkdude** [comment]
@arichiardi It might be the JVM who thinks otherwise, but babashka will not tolerate this unless users will object heavily.

**Comment by arichiardi** [comment]
@borkdude I am not sure I follow - what is that babashka does not tolerate?

**Comment by borkdude** [comment]
The empty sandwiched classpath entries. It will simply ignore them from now on.

**Comment by arichiardi** [comment]
Oh yes that's what I was hoping for!
