### ISSUE TITLE
Add `bound-fn` and `bound-fn*`

### ISSUE THREAD

**Issue by PEZ** [babashka/babashka#788]
**Is your feature request related to a problem? Please describe.**

When using dynamic vars an ergonomic way to handle the problem with the bindings used after they have expired, due to laziness:

```clojure
(def ^:dynamic *foo* :FOO)
(defn foo [x] [*foo* x])

(binding [*foo* :BAR]
  (map foo [1 2 3])) 
=> ([:FOO 1] [:FOO 2] [:FOO 3])
```

 is the `bound-fn*` function:

```clojure
(binding [*foo* :BAR]
  (let [bound-foo (bound-fn* foo)]
    (map bound-foo [1 2 3])))
=> ([:BAR 1] [:BAR 2] [:BAR 3])
```

However, babashka `0.3.4` does not support this function (nor the `bound-fn` macro).

**Describe the solution you'd like**

I'd like for babashka to have these functions. 😀

**Describe alternatives you've considered**

None. There is still `doall` and the option to avoid dynamic vars, of course.

**Additional context**

This seems to be needed for the example in #560 as well.

I added an example to ClojureDocs about dealing with laziness and `binding`: https://clojuredocs.org/clojure.core/binding#example-60746e7de4b0b1e3652d74c4

**Comment by borkdude** [comment]
@PEZ Will add them, but as a workaround: note that if you lookup the source for `bound-fn*` that will probably already work in bb if you copy paste this.

**Comment by PEZ** [comment]
Cool. I can give it a shot adding these, if you haven't started with it yet.

**Comment by borkdude** [comment]
@PEZ Added on master
