### ISSUE TITLE
Missing case throws an Exception instead of IllegalArgumentException

### ISSUE THREAD

**Issue by thiagokokada** [babashka/babashka#809]
**version**

babashka v0.3.5

**platform**

NixOS

**problem**

On Clojure, this returns a `IllegalArgumentException`:

```
user=> (#(case % :foo :bar) :qux)
Execution error (IllegalArgumentException) at user/eval146$fn (REPL:1).
No matching clause: :qux
```

On Babashka the same code returns a plain exception:

```
user=> (#(case % :foo :bar) :qux)
java.lang.Exception: No matching clause: :qux [at <repl>:1:3]
```

**repro**

```
(#(case % :foo :bar) :qux)
```

**expected behavior**

```
Execution error (IllegalArgumentException) at nucli.helpers.url/eval28247$fn (form-init13435618176996680441.clj:1).
No matching clause: :qux
```

[ Optional: if you or your organization is sponsoring this project, please write "**Sponsor**" in this ticket for higher priority. ]

**Comment by borkdude** [comment]
@thiagokokada Can you explain why the particular type of exception is important for you?

**Comment by thiagokokada** [comment]
@borkdude More like it was a surprising behavior, and I think most exceptions returns the exactly same exceptions as Clojure.

It is not affecting me right now, but I can see this being an issue if you needs to import some library that depends the correct exception to be raised on case.

**Comment by thiagokokada** [comment]
Maybe if for some reason it doesn't make sense to have the exactly same behavior as Clojure, documenting them on https://book.babashka.org/#differences-with-clojure would be a good idea :thinking: ?

**Comment by borkdude** [comment]
I think we could fix this.

**Comment by borkdude** [comment]
Fixed on master.
