### ISSUE TITLE
Tasks: ambiguity between core vars and task names

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#814]
``` clojure
{:tasks {:enter (prn (format "%s" 5))
         format (+ 1 2 3)
         }}
```

``` 
$ bb format
----- Error --------------------------------------------------------------------
Type:     java.lang.IllegalStateException
Message:  Attempting to call unbound fn: #'user1/format
``` 

I could see two ways to solve this:

1) bind task results in`let` instead of `def`
2) fully qualify all symbols in the global `:enter` and `:leave` first. 
3) require users to fully qualify conflicting core vars in `:enter` and `:leave` (not so user friendly)
But perhaps it's better to wait for more "interesting" cases like this.

I think the second option is pretty straightforward to implement:

```
user=> `(format "%s" 5)
(clojure.core/format "%s" 5)
user=> (eval `(format "%s" 5))
"5"
``` 

I wonder about the override in `doit`:
``` clojure
{:tasks {:enter (load-string "`(prn (format \"%s\" 5))")
         format {:task (+ 1 2 3)}
         doit {:depends [format]
               :enter (prn (format "%s" 1))}}}
```
I think in the case of `doit` it would be reasonable to require people to use a fully qualified symbol for `format`, since it's pretty clear that this is conflicting. Although you might still have access to that symbol if you indirectly depend on it.

**Comment by borkdude** [comment]
From @mikeananev:

> fully qualified symbols are simple and straightforward. no complex behaviour under the hood.

Do you mean, option 3 is fine and do nothing?

**Comment by mikeananev** [comment]
I have less experience than you but if  you _fully qualify all symbols in the global :enter and :leave first_ then you may be introduce more complex solution inside babashka? You need to remember "this", "that", "why?" in different places.
But if 2 solution is not so complex in your code then introduce it as more user friendly.

**Comment by borkdude** [comment]
I added this to the documentation in https://github.com/babashka/babashka/issues/778. That should be sufficient for now.
