### ISSUE TITLE
Document and add crispin to tests

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#817]
https://github.com/dunaj-project/crispin

**Comment by bobisageek** [comment]
Can this one also be closed? Is there anything else you'd like to see added?

**Comment by borkdude** [comment]
@bobisageek Thanks, closed. Anything else: not sure... If you are looking for stuff to do, there is a project here:

https://github.com/babashka/babashka/projects/1

with stuff on the left, but really any open issue you can look at and if desirable, discuss with me, either here, Github discussions or on Slack, if you have questions.

The issue I'm a bit stuck on myself right now is: https://github.com/babashka/babashka/issues/922
If you want, you could also take a look at this and help me debug.
