### ISSUE TITLE
babashka.deps needs PATH to be set, else there will be an NPE

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#820]
`env -i` clear the env. invoking babashka afterwards while deps have not been downloaded gives an NPE because `PATH` isn't set, which is used to detect the `java` installation.

Should be fixed here:

https://github.com/borkdude/deps.clj/blob/9e0ca8002cca486223a962c06865dbbe3bc1917a/src/borkdude/deps.clj#L165

Maybe fall back to just `"java"` if `PATH` isn't set.

EDIT: don't fall back, a message will be printed if java cannot be found.

/cc @ieugen

**Comment by ieugen** [comment]
I think some options are:

* Stop execution with specific error 
* Continue with a "default" path of current working directory and issue a warning
* Use a default path of current directory without warning

**Comment by borkdude** [comment]
There is already error handling if java cannot be found. Just gracefully handling the non-existent env variable as an empty string will do it.
