### ISSUE TITLE
Static binary for linux should be linked against musl

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#826]
See https://github.com/oracle/graal/issues/2691#issuecomment-670010352
Linking against the host glibc is a bad idea, we should link against musl for all of our static builds.
Then perhaps all the weird segmentation faults etc are over...

@lispyclouds will try to do this for `pod-babashka-aws` first.

/cc @thiagokokada @ericdallo @lispyclouds

**Comment by thiagokokada** [comment]
Found this comment here of an alternative way to build Native Image with musl: https://github.com/oracle/graal/issues/1898#issuecomment-763275747
