### ISSUE TITLE
Add `:error-fn` hook to `shell` 

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#836]
This will be triggered on non-zero exit codes or when `:continue` returns a non-truthy value.
The `:error-fn` function receives a map with `:proc`, `:task` and `:babashka/exit`. The map can be re-thrown using `ex-info` to get the same error handling as the original error handler of `shell`.

cc @pithyless

**Comment by pithyless** [comment]
cc @lread - This may be relevant to your https://github.com/lread/rewrite-clj/blob/main/script/helper/shell.clj

**Comment by lread** [comment]
Cool! Thanks for the ping @pithyless!
