### ISSUE TITLE
Add executable-name

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#859]
Returns the executable name of the current executable:

`(org.graalvm.nativeimage.ProcessProperties/getExecutableName)`

**Comment by bobisageek** [comment]
I've been playing around with this idea a little bit as a challenge for myself, and I'm curious about what you had in mind...

- the question that might make other questions moot: the `ProcessHandle$Info` additions from #873 seem to make this maybe redundant - we can get the same info (the executable path) and more from ProcessHandle (which also works in a non-native execution), so is this worth it?
- I might have read way too far into the issue title, but an idea that popped into my head was adding a (pseudo-)dynamic var called `*executable-name*` that would return the executable path - is this the type of thing you had in mind, or just making the class/method available, similar to `ProcessHandler$Info`? This is one of those cases where the idea of the var came into my mind, but what didn't come along with it was much of a use case where we'd want to use it, so I imagine we'd want to have a compelling rationale before adding a var.

**Comment by borkdude** [comment]
Thanks. Yeah, this issue is stale because you can now do the same with `ProcessHandle$Info` and I had not considered it when I made this issue. I'm also learning new things every day :).

**Comment by borkdude** [comment]
I don't think the use case is common enough to introduce a new function or var for it.
