### ISSUE TITLE
GitHub Actions now natively supports `[skip ci]`

### ISSUE THREAD

**Issue by frenchy64** [babashka/babashka#860]
Since I stole your implementation of `[skip ci]`, I though you might like to know it's now supported natively: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

Just a note, feel free to close this issue.

**Comment by borkdude** [comment]
Does babashka do anything special with that part in the commit message? I thought all CIs picked up automatically on that.

**Comment by frenchy64** [comment]
Yes I think so. These conditionals for example:

https://github.com/babashka/babashka/blob/512a6f2220a0e54ab585ead1dec2b10995f637f9/.github/workflows/build.yml#L11

**Comment by borkdude** [comment]
Ah yes, we did that manually because only CircleCI and Appveyor supported it back then. Thanks!

**Comment by borkdude** [comment]
And thanks for sponsoring!
