### ISSUE TITLE
pods in bb.edn

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#863]
We can have a pod config in bb.edn:

```
{:pods {org.babashka/mysql {:pod/version "0.0.6"}}}
```

When bb starts, we will check if all pods are already available. 

To load the pod, you no longer have to provide the version:

```
(load-pod 'org.babashka.mysql)
```

As a second step, we could list the namespaces when the pod should be loaded in bb.edn?

In the case of creating an uberjar, we'll have to remember the pod versions in order to be able to load them. Maybe insert the pod versions into the manifest?

**Comment by FieryCod** [comment]
@borkdude Maybe it would be easier to just include bb.edn in uberjar instead?
