### ISSUE TITLE
Bump image used to build Native Image after Debian 11 is released

### ISSUE THREAD

**Issue by thiagokokada** [babashka/babashka#866]
**Is your feature request related to a problem? Please describe.**
Nowadays we use old stable version of Debian (`stretch`, or Debian 9). There will be no more support after 30 June 2022, so it makes sense that we should update it eventually.

It doesn't make much sense to update it right now to Debian 10 since this will not bring much benefits (the most impactful thing would be the upgrade from GCC 6.3 to GCC 8.4). However with the release of Debian 11 we will have two things that we end up using:

- `gcc` will be upgraded to 10.2
- `musl-tools` will be upgraded to 1.22

Today we backport `musl-tools` from unstable, but since the version from unstable and the version from Debian 11 are the same (1.22), it means that after Debian 11 we can drop [this hack](https://github.com/babashka/babashka/blob/master/script/setup-musl#L15-L36) and just install `musl-tools` directly from repositories.

So I think upgrading Debian 11 after its release will be worth it.

**Describe the solution you'd like**
Change the image from [`Dockerfile`](https://github.com/babashka/babashka/blob/master/Dockerfile#L1) to whatever version is released on Clojure official images after Debian 11 is released. Also need to update the image used on CircleCI.

This probably also means we need to upgrade `leiningen` to a newer version (since newer images are generally only build with the latest `leiningen` available). The current version is 2.9.6, but this may change after Debian 11 is released.

**Describe alternatives you've considered**
We can continue to build binaries using Debian 9, however eventually we will need to update the image after Debian 9 stops receiving updates.

**Additional context**
N/A

**Comment by thiagokokada** [comment]
This issue can probably have a `blocker` label or something, since there is still some months until Debian 11 is finally released.

**Comment by thiagokokada** [comment]
One thing that I remember is that bumping Debian will also bump the `glibc` version (Debian 9 uses 2.24, Debian 11 uses 2.31). This shouldn't be too much a problem since 2.24 and 2.31 have the same minimum kernel version (3.2), and AFAIK Debian compiles `glibc` explicitly with this minimum version.

But something to keep in mind to test after switching.

**Comment by thiagokokada** [comment]
CC @lispyclouds.

**Comment by ieugen** [comment]
Debian 11 release in 1 week.

**Comment by thiagokokada** [comment]
Opened an issue on `docker-clojure` repository for Debian 11 (bullseye) is used on the image instead of Debian 10 (stretch): https://github.com/babashka/babashka/issues/866

Once they fix the issue I can do the migration work.

**Comment by borkdude** [comment]
This can be closed right @thiagokokada ?
