### ISSUE TITLE
Method user on class java.lang.ProcessHandleImpl$Info not allowed

### ISSUE THREAD

**Issue by github-dr** [babashka/babashka#872]
**version**

$ bb --version
babashka v0.4.3

**platform**

Linux and Windows

**problem**

Accessing methods on java.lang.ProcessHandle$Info is not possible.

**repro**

(.user (.info (first (iterator-seq (.iterator (java.lang.ProcessHandle/allProcesses))))))
Method user on class java.lang.ProcessHandleImpl$Info not allowed! [at <repl>:1:8]

**expected behavior**

Should return string of user owning the first process returned by java.lang.ProcessHandle.allProcesses()

**Comment by borkdude** [comment]
TIL! This will be pretty useful:
```
$ bb -e '(vec (.get (.arguments (.info (java.lang.ProcessHandle/current)))))'
["-e" "(vec (.get (.arguments (.info (java.lang.ProcessHandle/current)))))"]
``` 
Will add the necessary classes.

**Comment by borkdude** [comment]
Fixed on master.

**Comment by github-dr** [comment]
That was fast!  Thank you.
