### ISSUE TITLE
`.wait` and `.notify` support on base Clojure collections

### ISSUE THREAD

**Issue by IGJoshua** [babashka/babashka#879]
**Is your feature request related to a problem? Please describe.**
Complex thread coordination sometimes requires `.wait` and `.notify`, and it's not always convenient to need to keep a mapping from collections you'd like to lock on and `java.lang.Object`s that you use to lock on.

**Describe the solution you'd like**
Only for the base collections in Clojure, I'd like `.wait` and `.notify` to be permitted. So persistent hash maps, sorted maps, persistent lists, persistent vectors, hash sets, and sorted sets.

**Comment by borkdude** [comment]
Should work on master.
