### ISSUE TITLE
`ref` and `dosync` support

### ISSUE THREAD

**Issue by IGJoshua** [babashka/babashka#880]
**Is your feature request related to a problem? Please describe.**
While most thread-coordinated state updates can be handled by `atom`s, in certain contexts, especially when coordination is required between multiple threads for more than simply handing off data, `ref`s and `dosync` offer greater flexibility and result in easier to follow code.

**Describe the solution you'd like**
An implementation of STM to expose the `ref`-related functions from `clojure.core`.

**Additional context**
The particular code that requires this is from the library [farolero](https://github.com/IGJoshua/farolero), which I would like to port to babashka. In farolero there is a default system debugger implementation which requires negotiating access to the user from multiple threads which may be in an error state simultaneously. See [this file](https://github.com/IGJoshua/farolero/blob/master/src/cljc/farolero/core.cljc#L1192-L1269) for context. In implementing this negotiation, I make use of two `ref`s which must make several transactional read-writes which would be difficult to express with atoms and would result in more verbose and less readable code.

**Comment by borkdude** [comment]
Added `dosync` and `ref` and `ref-set`. Any more?

**Comment by IGJoshua** [comment]
`alter` and `commute` would be useful

**Comment by borkdude** [comment]
Already added `alter`. Just pushed `commute`.
