### ISSUE TITLE
passing certain forms on command line throws on Windows (without -e)

### ISSUE THREAD

**Issue by bobisageek** [babashka/babashka#889]
First off, definitely no sense of urgency on this - it's not a big deal, and `-e` is certainly not a burden...

**version**

0.4.5

**platform**

Windows 10

**problem**

"one-liners" that contain "illegal" path characters throw on Windows, if you don't use -e (behavior is not reproducible on Linux `bb`)

**repro**

Windows behavior:
```
# expected
> bb -e "(zero? 1)"
false

# unexpected
> bb "(zero? 1)"
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <?> at index 5: (zero? 1)
```

**expected behavior**

Linux behavior (0.2.8 on Ubuntu running in WSL):
```
$ bb -e "(zero? 1)"
false
$ bb "(zero? 1)"
false
```

**cursory analysis**
This came out of work on #235 - some of the test in `b.main-test` encounter this issue on Windows. This appears to stem from:
`b.main/main -> b.main/parse-opts -> b.fs/regular-file? -> b.fs/as-path -> File.toPath`, and `File.toPath` throws on Windows when the filename contains certain characters (appears to be any of #{ <>:"|?* } and trailing spaces).

**Comment by borkdude** [comment]
@bobisageek Fixed on master. Feel free to provide the test / mark it with `:windows`.
