### ISSUE TITLE
Consider adding `clojure.tools.logging` to babashka

### ISSUE THREAD

**Issue by dharrigan** [babashka/babashka#925]
At the moment, I'm using a library and trying to invoke it as part of babashka tasks, but it falls over since the `clojure.tools.logging` isn't available, i.e.,

```
❯ bb run docker-compose
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  Could not resolve symbol: clojure.lang.LockingTransaction/isRunning
Location: clojure/tools/logging.clj:59:15
Phase:    analysis

----- Context ------------------------------------------------------------------
55:   [logger level throwable message]
56:   (if (case *force*
57:         :agent  true
58:         :direct false
59:         (and (clojure.lang.LockingTransaction/isRunning)
                  ^--- Could not resolve symbol: clojure.lang.LockingTransaction/isRunning
60:              (*tx-agent-levels* level)))
61:     (send-off *logging-agent*
62:       (fn [_#] (impl/write! logger level throwable message)))
63:     (impl/write! logger level throwable message))
64:   nil)
```

It would be super neat if babashka could support clojure.tools.logging.

**Comment by borkdude** [comment]
Can you elaborate which library is using tools.logging as a dep? I’ve also seen this with the nrepl library which I’m considering to fork to make it work with bb. Adding a logging library to bb should IMO be done because we want to have logging. But we can see if making tools.logging work from source is another option.

**Comment by dharrigan** [comment]
Hi,

An internal library, something tooling we use inside my company.

**Comment by borkdude** [comment]
@dharrigan An quick workaround for now could be to use `:bb` reader conditionals to strip out the calls to tools.logging.
