### ISSUE TITLE
Run lib_tests in CI on Windows

### ISSUE THREAD

**Issue by bobisageek** [babashka/babashka#932]
**Is your feature request related to a problem? Please describe.**

No specific problem - just hoping to expand on the Windows testing.

**Describe the solution you'd like**

I'd like to run (more or less) the same lib tests that run on Linux CI on Windows CI.

**Describe alternatives you've considered**

The alternative is not doing the testing I guess... it's probably not 100% needed, but in messing around with setting it up, I've found one small thing that 'breaks' on Windows in the current tests (not counting line endings and curl's ":compressed" thing).

**Additional context**

Setup - there's a small hiccup here, in that as far as I know, the AppVeyor machine doesn't have the Clojure CLI available. A potential workaround here (that's maybe not the prettiest) is to use `bb clojure` (using the bb we've built) to compute the classpath from deps.edn. Because of this, maybe we just run the lib tests with the native bb.

Actual tests - there's one little path handling thing in a Selmer test that can be fixed pretty easily, and one or two line ending things, but other than that, the only 'problem' is compression with curl - to start with, my plan was to just skip those on Windows.

I currently have some tweaks in my local workspace where all the tests (minus the skipped curl tests) pass on Windows.

Questions: Any interest in running the lib tests on Windows? Are you ok with relying on the bb that was just built being a dependency for building the classpath?

**Comment by borkdude** [comment]
Yes, this seems good to me!

**Comment by borkdude** [comment]
> Are you ok with relying on the bb that was just built being a dependency for building the classpath?

Yes.
