### ISSUE TITLE
Add tests for clojure.tools.logging + timbre

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#935]
TODO: 

- [x] test below file using spit appender
- [x] make `(with-out-str (timbre/info :hello))` work, this requires a patch for the println-appender

I tested it locally using:

``` clojure
(ns dude)
(require '[clojure.tools.logging :as log])
(require '[taoensso.timbre :as timbre])

(defn test-fn
  []
  (log/debug "test ctl debug level")
  (log/info "test ctl info")
  (timbre/debug "test timbre debug level")
  (timbre/info "test timbre info"))

(println "before setting log level")
(test-fn)

(alter-var-root #'timbre/*config* #(assoc %1 :min-level :info))

(println "after setting log level to :info")
(test-fn)

(println "with-level :debug")
(timbre/with-level :debug
  (test-fn))

(timbre/set-level! :debug)
(println "after setting log level to :debug")
(test-fn)

(timbre/infof "Hello %s" 123)
(log/infof "Hello %s" 123)

(timbre/swap-config! assoc-in [:appenders :spit] (timbre/spit-appender {:fname "/tmp/timbre.log"}))
(log/infof "Hello %s" 123)
```

To incorporate this into a unit test it's probably best to use a spit-appender in the entire test and then check the contents of the file afterwars.

Is this something you might be interested in doing @bobisageek?

**Comment by borkdude** [comment]
cc @justone, if you have more feedback please post it here

**Comment by bobisageek** [comment]
Yeah - work is a little heavy this week, so it might be the weekend before I really dig into it, but I have a small battery of tests forming in my head. I just want to confirm one little thing to save any headaches later on: given that timbre and tools.logging are directly integrated (i.e. they're lein dependencies with namespace impls in babashka.main), do we want to target the 'main' tests (as opposed to lib tests)?

I guess I can sort of see an argument for either case, and of course I'd rather agree on an expectation than spend extra test cycles moving tests around. :)

**Comment by borkdude** [comment]
@bobisageek OK, I'm going to release this probably tomorrow, and I'm going to add a few preliminary tests for it, but we can enhance the tests with more later on and you're welcome to do it whenever it suits your schedule. No obligations whatsoever of course. I just asked you since I thought you might be interested, considering your recent efforts :).
