### ISSUE TITLE
Windows tests: disabled lib tests

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#940]
FYI @bobisageek, I kept getting this problem in CI:

<img width="972" alt="Screenshot 2021-07-15 at 16 40 00" src="https://user-images.githubusercontent.com/284934/125807110-0198baa5-8778-400f-be8f-e0e797ca4df7.png">

I didn't investigate yet why this happened, but I decided to turn off the lib tests.

I also disabled the JVM tests for now on Windows to make the build slightly faster: if the native tests pass I think that's sufficient.

**Comment by bobisageek** [comment]
I'm able to re-create this, but only on newer commits (based on a bisect). The symptom I'm seeing locally is that for a reason (that I don't currently know), the output of `bb clojure...` doesn't get put into the variable, so most of the classpath is missing.

I'm currently thinking about how to minimize the reliance on Windows batch behavior, in large part because I can't repro the behavior on the same revs where appveyor exhibits it.

**Comment by borkdude** [comment]
I probably broke it myself in the process of getting 0.5.0 out the door, sorry... :)
I'm looking forward to your thoughts of relying less on Windows .bat. Perhaps we could just make a script in Clojure and run it on the JVM, although that will be a tad slower.

**Comment by borkdude** [comment]
Or just use the compiled bb for scripting, I would be fine with that. If the native tests succeed on Windows, I'm convinced that the JVM tests would also have succeeded, so we can just start from the native.

**Comment by bobisageek** [comment]
To avoid the "for loop" thing, I put together a little bb script that does a stripped-down version of what the clojure command does - read deps.edn and merge the deps/paths with lib-tests alias deps and paths, and then I'm just spitting that out to a file to be used as a bb.edn.

Just a quick question - I'm a bit unclear on why `test-resources/lib_tests` is added to the classpath in the shell scripts themselves - I'm wondering if it would make sense to add that path to `:extra-paths` in deps.edn instead, and then both of the lib-test scripts wouldn't need that manually added to the classpath. I can make it work either way, but if you agree that moving the path to deps.edn is cleaner, then those scripts get just a little bit nicer IMO.

**Comment by borkdude** [comment]
> Just a quick question - I'm a bit unclear on why test-resources/lib_tests is added to the classpath in the shell scripts themselves 

Can you show me where this happens?

**Comment by bobisageek** [comment]
In `script/lib_tests/run_all_libtests` (and the Windows batch file of the same name), we (effectively or exactly) run `clojure -A:lib-tests -Spath` to get a classpath, and then we add another path to the classpath at https://github.com/babashka/babashka/blob/2282b2922d2588599e9c2fd7b2096cc365c15bf5/script/lib_tests/run_all_libtests#L14

My proposal would be to move that path spec to the `:extra-paths` of the lib-tests alias https://github.com/babashka/babashka/blob/2282b2922d2588599e9c2fd7b2096cc365c15bf5/deps.edn#L52-L53

... and then the `clojure` call would include that path. I don't see the lib-tests alias used elsewhere, so I don't see a down side to it off-hand.

**Comment by borkdude** [comment]
@bobisageek I think that makes sense. I don't remember why I did this the way it is now.
