### ISSUE TITLE
with-open fails on java.io.PrintWriter

### ISSUE THREAD

**Issue by ivarref** [babashka/babashka#953]
**version**

```
babashka v0.5.0
```

**platform**

```
Ubuntu 20.04.2 LTS
```

**problem**

`with-open` fails on `java.io.PrintWriter` with error message
```
----- Error --------------------------------------------------------------------
Type:     java.lang.IllegalArgumentException
Message:  No matching method close found taking 0 args for class java.io.PrintWriter
Location: 1:1
```

**repro**

```bash
$ bb '(with-open [writer (java.io.PrintWriter. (java.io.ByteArrayOutputStream.))])'
----- Error --------------------------------------------------------------------
Type:     java.lang.IllegalArgumentException
Message:  No matching method close found taking 0 args for class java.io.PrintWriter
Location: 1:1
```

**expected behavior**

```bash
$ clojure --eval '(with-open [writer (java.io.PrintWriter. (java.io.ByteArrayOutputStream.))])'
$ bb '(with-open [writer (java.io.OutputStreamWriter. (java.io.ByteArrayOutputStream.))])'
```
both works.

**notes**

According to how IntelliJ shows PrinterWriter.close() from `jdk-11.0.5+10`, the close method does not declare throwing any exceptions. Might that be the cause of this behaviour?

Thanks for a lot of excellent work on Clojure tools @borkdude !

**Comment by borkdude** [comment]
@ivarref The issue has to do with reflection support in the GraalVM compiled binary. I only added partial support for this class to save space, but I'll add full support so all methods will be available.

**Comment by borkdude** [comment]
@ivarref You can find a new build in the CircleCI builds: https://circleci.com/gh/babashka/babashka/21250?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
