### ISSUE TITLE
Printing control dynamic vars not implemented in bb

### ISSUE THREAD

**Issue by cursive-ide** [babashka/babashka#959]
**version**

0.5.1-SNAPSHOT, 0.4.6

**platform**

MacOS

**problem**

When writing code to implement a REPL in userspace, there are some useful vars which are used in the prepl implementation in Clojure (`*flush-on-newline*` and `*print-readably*`). These don't seem to be implemented in bb.

**Comment by borkdude** [comment]
Added support for the above mentioned vars.

**Comment by borkdude** [comment]
@cursive-ide Mac binary for testing: https://21617-201467090-gh.circle-artifacts.com/0/release/babashka-0.5.2-SNAPSHOT-macos-amd64.tar.gz
