### ISSUE TITLE
Support form-level location metadata when reading

### ISSUE THREAD

**Issue by cursive-ide** [babashka/babashka#960]
In Clojure, there's a little-documented feature in 1.10+ which can be used to specify location metadata for individual forms. It's discussed in cursive-ide/cursive#2113 and that's the only place I can actually find an accurate description of how it works. Briefly, forms can have metadata like:
```clojure
^{:clojure.core/eval-file "a/b/foo.clj", :line 100, :column 1} (hi 1)
``` 
and this will ensure that the correct location metadata is set. This is important for being able to send forms from an editor to a REPL, and still have exceptions from the new code make sense.

**Comment by borkdude** [comment]
```
$ clj
Clojure 1.11.0-alpha1
user=> ^{:clojure.core/eval-file "a/b/foo.clj", :line 100, :column 1} (hi 1)
Syntax error compiling at (a/b/foo.clj:100:1).
Unable to resolve symbol: hi in this context
user=> ^{:file "a/b/foo.clj", :line 100, :column 1} (hi 1)
Syntax error compiling at (REPL:100:1).
Unable to resolve symbol: hi in this context
user=>
```

**Comment by borkdude** [comment]
```
$ clj
Clojure 1.11.0-alpha1
user=> (defmacro foo [expr] (prn (meta expr)))
#'user/foo
user=> (foo ^{:file "a/b/foo.clj", :line 100, :column 1} (hi 1))
{:line 100, :column 1, :file "a/b/foo.clj"}
```

**Comment by borkdude** [comment]
Should work now.

**Comment by borkdude** [comment]
@cursive-ide Binary for testing:

https://21625-201467090-gh.circle-artifacts.com/0/release/babashka-0.5.2-SNAPSHOT-macos-amd64.tar.gz

(also includes the print vars)
