### ISSUE TITLE
Method getName on class java.lang.reflect.Method not allowed

### ISSUE THREAD

**Issue by whatacold** [babashka/babashka#969]
**version**

Babashka v0.5.1, downloaded from https://github.com/babashka/babashka/releases/download/v0.5.1/babashka-0.5.1-linux-amd64.tar.gz.

**platform**

Linux

**problem**

I'm not 100% sure if this is a bug, but it works on Clojure `clj` with the following code snippet:
```clojure
(defn class-methods [x]
 (let [c (if (class? x) x (class x))]
  (-> (map #(.getName %1)
           (.getMethods c))
      ;; seq
      sort
      distinct)))

(class-methods \a)
```

It will return something like `("charCount" "charValue" ... "valueOf" "wait")`

**repro**

Here is the evaluations of the code snippet in `bb`:
```
$ bb
Babashka v0.5.1 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (defn class-methods [x]
 (let [c (if (class? x) x (class x))]
  (-> (map #(.getName %1)
           (.getMethods c))
      ;; seq
      sort
      distinct)))
#'user/class-methods

user=> (class-methods \a)
Method getName on class java.lang.reflect.Method not allowed! [at <repl>]
```

**expected behavior**

Return the Java class methods as in `clj`.

**Comment by borkdude** [comment]
@whatacold Babashka has a subset of classes from the Java ecosystem available: it hasn't got all of them as this would make the binary bigger. So if classes are useful for scripting they will get added. I will see how much this method adds to the image.

**Comment by borkdude** [comment]
It adds about 10mb in the macOS native image when I add this class. I could try restrict access to the `.getName` method. Perhaps it's better to ask: why would it be important to have this in bb?

**Comment by borkdude** [comment]
OK, I've added the getName method only, that doesn't really trigger a big increase in binary size, so the above example will work with bb master now.

**Comment by whatacold** [comment]
Wow, thanks for the quick fix.

> It adds about 10mb in the macOS native image when I add this class. I could try restrict access to the .getName method. Perhaps it's better to ask: why would it be important to have this in bb?

Sorry for the late reply.

I was not sure if this is an issue, but now I understand that bb has a consideration to limit its size. I found this error when I played around with Clojure and bb, so I can't say I must have `getName`, but it would be nice to explore Java methods in bb REPL if possible.
