### ISSUE TITLE
Add support for java.net.http client

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#979]
By @grzm:

PR for size comparison. (Locally it checks in at 87M, compared with 83M without the new classes)

Still some open issues:

 - [x] figure out how to access java.net.InMemoryCookieStore
 - [ ] test executor
 - [ ] test proxy
 - [ ] test websockets
 - [x] add tests
 - [ ] :revoked 200 ;; TODO: fix, "sun.security.cert.CertificateRevokedException"

I'd also like to add a helper function to handle requests with input-stream bodies along the lines of the following:

```clojure
(ns babashka.http-helper
  (:import
   (java.util.function Supplier)))

(defn input-stream-supplier [^java.io.InputStream is] (reify Supplier (get [_] is)))
```

**Comment by borkdude** [comment]
From the first PR:

@grzm I added the first test at babashka.java-http-client-test. Feel free to add more tests, even failing ones which should succeed and then we can make them work.

Funnily enough, the difference in the macos binary is much smaller.

```
macos:
master: 86569320
jdk-11-http-client: 86671992
diff: .1mb

linux static:
master: 87016288]
jdk-11-http-client: 91669344
diff: 4.6MB
```

**Comment by grzm** [comment]
Glad to see you're seeing smaller macOS binaries. I'm seeing 91259568 with be5822928c665e76bf82fa6ce0a1424891bad7b6 on my Catalina machine.

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1323

$ java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode, sharing)

echo $GRAALVM_HOME 
/Users/grzm/dev/graalvm-ce-java11-21.1.0/Contents/Home
```

**Comment by borkdude** [comment]
I'm seeing that now too, so for all OSes it seems to be around 4.8MB or so.

**Comment by borkdude** [comment]
@grzm One test was failing so I added this as a TODO:

:revoked 200 ;; TODO: fix, "sun.security.cert.CertificateRevokedException"

**Comment by grzm** [comment]
Here's my current burn-down list:
## HttpClient
- [ ] executor
- [ ] priority
- [ ] proxy
- [ ] sslContext
- [ ] sslParameters
- [ ] timeout
- [ ] allow insecure certs
- [ ] revoke cert failure
- [ ] sendAsync

## HttpRequest
- [ ] expectContinue
- [ ] header
- [ ] headers
- [ ] timeout
     Use postman-echo.com/delay ?
- [ ] version

## HttpRequest$BodyPublishers
- [ ] ofByteArray
- [ ] ofFile
- [ ] ofString with Charset

## HttpResponse$BodyHandlers
- [ ] ofByteArray
- [ ] ofFile
- [ ] ofFile with OpenOption
- [ ] ofFileDownload
- [ ] ofInputStream
- [ ] replacing
## WebSockets
- [ ] ...

**Comment by grzm** [comment]
Regarding including `java.util.function.Function` with reify, I only included the `apply` method. There are [a couple more.](https://docs.oracle.com/javase/8/docs/api/java/util/function/Function.html) I noticed in some other cases some interfaces were not included in the reify definition. Adding only `apply` gets us a smoke test success for using `sendAsync`. Maybe we want the other methods as well?

**Comment by borkdude** [comment]
@grzm Sure. We could also handle that in a follow up issue with separate test cases specifically for that.

**Comment by grzm** [comment]
I'm adding `java.nio.file.StandardOpenOption` as part of `HttpResponse$BodyHanders/ofFile` with `OpenOption`. I see that the other java.nio.file stuff is under `features/java-nio?` feature flag, so I've included it there. There are a couple of other java.nio.file packages (i.e,. `java.nio.file.attribute.FileAttribute`, `java.nio.file.Files`) that I'm using that are in there as well. Should we reorganize those packages or make a note or somesuch? How would you like to handle that?

**Comment by borkdude** [comment]
> I see that the other java.nio.file stuff is under features/java-nio? feature flag, so I've included it there. 

OK.

I'm not sure how you would like to re-organize? Both features will be enabled by default. If people want to build bb without either feature, they should just expect that nio classes won't be there even if those are important for interacting with the http client.

**Comment by grzm** [comment]
> > I see that the other java.nio.file stuff is under features/java-nio? feature flag, so I've included it there.
> 
> OK.
> 
> I'm not sure how you would like to re-organize? Both features will be enabled by default.

Sounds good to me. Just wanted to bring it to your attention.

**Comment by borkdude** [comment]
@grzm Merged the branch to master now. Feel free to follow up with incremental PRs to master.

**Comment by borkdude** [comment]
Closing for now, let's continue in new issues for enhancements/bugfixes.
