### ISSUE TITLE
clojure.tools.logging.readable

### ISSUE THREAD

**Issue by corasaurus-hex** [babashka/babashka#981]
It would be nice to have [clojure.tools.logging.readable](https://github.com/clojure/tools.logging/blob/master/src/main/clojure/clojure/tools/logging/readable.clj) included with the bundled clojure.tools.logging. It's just for convenience, but it is _so_ convenient. This namespace provides logging where if you do `(log/info & args)` and any of the `args` aren't strings then each non-string `arg` is run through `pr-str` before being concatenated with the rest of the message. This means you can log most anything without having to wrap it in a `(pr-str)` yourself manually.

**Comment by borkdude** [comment]
Fixed by @bobisageek, thanks!
