### ISSUE TITLE
Add support for --init command line similar to clojure/cjr

### ISSUE THREAD

**Issue by digash** [babashka/babashka#998]
**Is your feature request related to a problem? Please describe.**
Clojure command line support --init command line that allows preload .clj file.
Common usage is to do something like this on command line:
`clojure --init /full/path/to/bla.clj --main bla arg1 arg2`

**Describe the solution you'd like**
Doing the same command line for bb would make it easier to run scripts with bb by just substituting bb for clojure.

**Describe alternatives you've considered**
It is possible to get same behavior with bb, but it is less concise and not as obvious.
`BABASHKA_PRELOADS="(load-file \"/full/path/to/bla.clj\")" bb --main bla -- arg1 arg2`

**Additional context**
Another usage in shabang scripts:
```
#!/bin/sh
#_(-*- clojure -*- sorcery to allow to run this script as executable on Linux/Unix
       BABASHKA_PRELOADS="(load-file \"$0\")" exec bb --main bla -- "$@"
       #_exec clojure -J-Xms256m -J-Xmx256m -J-client -M --report file --init "$0" --main bla "$@")
(ns bla)
```

**Comment by bobisageek** [comment]
I was doing some exploration of this, and thought I'd throw out a couple questions/comments for feedback:
- `--init` is supported by clojure (according to the usage doc) on the `-M` and `clj` "paths", which would probably most closely correspond to the `--eval` and `--main` paths of bb - would there be a desire to support `--init` in exactly those two paths, or some other set of execution paths? There's maybe a case for having `--init` available with some of the subcommands, or maybe just handling it more like BABASHKA_PRELOADS (if they're there, run them)
- the counter-point (maybe) to "if they're there, run them" is a question of parity with clojure with regard to ordering - passing multiple `-e`s with a `--init` thrown in there loads the file in the order things show up on the command line:
```shell
$ clojure -e '(def x 1)' --init <(echo '(println "x is" x)') -e '(println "second")'
#'user/x
x is 1
second
```
... so in this context, `--init` kind of acts like "-e (the contents of the file)" (plus namespace magic*). To that end, this starts feeling a bit like `-f` in bb, if `-e` and `-f` and `-m` all played nicely together. Is it worth considering that? If it were possible to do something like:
```shell
$ bb -f <(echo '(ns inited) (defn -main [] (println "hello from inited"))') --main inited
hello from inited
```
... then `--init` would be close to an alias for `--file`

But then again, maybe I'm overthinking it and/or that drastic of a change is a bit risky... I'm just looking for feedback on the ideas.

"namespace magic" - it looks like clojure remembers the namespace before loading an init file:
```shell
$ clj -e '(ns cheese)' --init <(echo '(ns inited) (println (ns-name *ns*))') -e '(println (ns-name *ns*))'
inited
cheese
```

**Comment by borkdude** [comment]
Good thoughts. 

What makes this more complex is `--stream` which also takes into account `-e` or -f` but since that is a bb-only feature, we can make up our own rules regarding combinations of `--init` and `--stream`: I'd say run `--init` always only once, regarding `--stream` or not. 

> on the -M and clj "paths"

What exactly do you mean by `clj "paths"`? `clj on its own isn't valid anymore, you should always use `-M` to invoke clojure with an expression or file  + optional init.

**Comment by bobisageek** [comment]
> What exactly do you mean by clj "paths"?
I was thinking of a REPL with an `--init`, but you're right, that should still be a `-M`.

**ordering**
As mentioned, `--stream` can cause each `-e` to get executed multiple times. I'm not sure that it would feel intuitive if `--init` could get executed after all the executions of `-e`, or between them somehow (if there were multiple `-e`s with an `--init` in the middle somewhere), so I'd propose extending the statement about `--init` always and only once to say "before the `-e`/`-f`/`-m`". Note that there are some (fairly esoteric) cases where this would behave differently from the Clojure CLI (see the '-e --init -e' example above). I think this slight difference could be made more obvious by calling `--init` a 'global-opt', which would imply that `--init` should always come before the `-e`/`-f`/`-m` opts. I'm pretty sure we can get it to where clojure and bb behave the same way without a bunch of inconsistent/confusing edge cases, as long as `--init` comes before the evaluation opts.

I might take a first swing at this this week if no one else does (dependent on other workloads) - I'll definitely be adding a bunch of tests for this to try and cover as many interaction possibilities as I can think of.
