### ISSUE TITLE
Provide a mechanism to override `str`/`toString` on defrecords

### ISSUE THREAD

**Issue by plexus** [babashka/babashka#999]
**Is your feature request related to a problem? Please describe.**

lambdaisland.uri relies on a `toString` implementation on the `URI` record, so that calling `str` on it gives you back the URI as a string. There is currently no mechanism to make this work in bb. See https://github.com/lambdaisland/uri/pull/22

**Describe the solution you'd like**

I can imagine two different scenarios, either explicitly supporting `(defrecord Foo [] Object (toString [this] ...))`, or providing a mechanism to hook into `clojure.core/str`, e.g. a custom protocol or multimethod which dispatches on type.

**Comment by borkdude** [comment]
@plexus Supported on master. If you want to test prior to new release:

linux: https://23355-201467090-gh.circle-artifacts.com/0/release/babashka-0.6.5-SNAPSHOT-linux-amd64-static.tar.gz

macOS: https://23358-201467090-gh.circle-artifacts.com/0/release/babashka-0.6.5-SNAPSHOT-macos-amd64.tar.gz
linux:
